### ISSUE TITLE
Add Jasinga Sundanese

### ISSUE THREAD

**Issue by Maramukiri** [glottolog/glottolog#1004]
The Jasinga dialect is one of the Sundanese dialects spoken in Bogor Regency, at the western end, precisely in the former Kawedanan ​​Jasinga. This is different from the Bogor dialect in general and is more egalitarian in nature and does not recognize language levels, and has a close relationship with the Bantenese dialect.

References:

Sakti, Hari (2018). Pemetaan Bahasa di Kecamatan Jasinga Kabupaten Bogor 
Jawa Barat: Sebuah Kajian Dialektologi. Skripsi. Jakarta: Fakultas Bahasa dan 
Seni. Universitas Negeri Jakarta. January 2018.

Accessed in http://repository.unj.ac.id/1237/1/Skripsi%20Hari%20Sakti%202125140274.pdf

**Comment by d97hah** [comment]
This thesis compares 16 lects within Jasinga. Is there some other source
that describes the difference of (all?) Jasinga lects from those of the
rest of Bogor?

Pada tanggal Kam, 20 Jul 2023 pukul 20.19 Maramukiri <
***@***.***> menulis:

**Comment by Maramukiri** [comment]
Yantu, Yuli (2020). Analisis Dialek Kata Kampung Pamalang Kampung Bagoang dan Kampung Sipak di Kecamatan Jasinga Kabupaten Bogor (Kajian Dialektologi). Tangerang Selatan: Universitas Pamulang.

Accessed in https://repository.unpam.ac.id/9687/

**Comment by Maramukiri** [comment]
Kurnia, Atep (2021). Het Soendaneesch Vereischte: Bahasa Sunda bagi para Pegawai Perkebunan di Priangan, 1890-1928. Lopian: Jurnal Pengetahuan Lokal, December 2021 Vol. 1 No. 2.

Accessed in https://jurnal.unpad.ac.id/lopian/article/download/37568/16738

**Comment by d97hah** [comment]
Does this reference really describe the differences between (those three)
Jasinga lects and other Bogor lects? The abstract suggests it does not have
such a comparison. Please do not reply with yet more references unless you
are sure they are of the kind that do describe the differences you raised
in the original issue.

Pada tanggal Jum, 21 Jul 2023 pukul 14.13 Maramukiri <
***@***.***> menulis:

**Comment by Maramukiri** [comment]
It does not suggest a comparison of lects but rather explains the differences in vocabulary in the Jasinga dialect.
