### ISSUE TITLE
Is kolp1236 really spoken in Vanuatu?

### ISSUE THREAD

**Issue by tihomirrangelov** [glottolog/glottolog#1011]
Kol (Papua New Guinea) | kolp1236 | NG area | 151.583 | -5.21042 | NA | PG;VU | NA

**Comment by d97hah** [comment]
No it certainly isn't, I'll fix for next version. (Not sure how it
happened, maybe a name confusion done in auto somewhere long ago). Thanks
for noticing. all the best, H

Pada tanggal Sab, 19 Agu 2023 pukul 10.57 Tihomir Rangelov <
***@***.***> menulis:

**Comment by xrotwang** [comment]
The relation between Kol and Vanuato came in via information from ElCat. https://endangeredlanguages.com/lang/10809 is located in "Vanuatu" in the download file provided by ElCat. Not sure how we want to manage that in the future. We could have an exclusion list, with languages for which **not** to update metadata from ElCat, or an inclusion list, with languages for which we want updates. Or - considering that ElCat isn't changing much anymore - not add metadata from ElCat in the future and fix the problems that have crept in last time (like this one) one at a time.

**Comment by d97hah** [comment]
Don't update metadata from ElCat should be the simplest solution

Pada tanggal Kam, 24 Agu 2023 pukul 15.19 Robert Forkel <
***@***.***> menulis:
