### ISSUE TITLE
Correction in reference for Mirandese

### ISSUE THREAD

**Issue by inigourrestarazu** [glottolog/glottolog#1012]
Hi there!

A reference for Mirandese, Satoshi 2010, is not right. It says `Journal of the International Studies`, but it is `Journal of the Intercultural Studies`.

The bibtex would be like this:

@article{123471,
  address    = {Lisboa},
  author     = {Terao, Satoshi},
  journal    = {Journal of Intercultural Studies},
  pages      = {101-126},
  publisher  = {Impr. Nacional},
  title      = {Mirandese as an Endangered language},
  volume     = {35},
  year       = {2010},
  bestfn     = {eurasia\terao_mirandese2010_o.pdf},
  besttxt    = {ptxt2\eurasia\terao_mirandese2010_o.txt},
  cfn        = {eurasia\terao_mirandese2010_o.pdf},
  fn         = {eurasia\terao_mirandese2010.pdf, eurasia\terao_mirandese2010_o.pdf},
  hhtype     = {grammar_sketch},
  inlg       = {English [eng]},
  lgcode     = {Mirandese [mwl]},
  macro_area = {Eurasia},
  src        = {hh}
}

**Comment by d97hah** [comment]
Thanks I've fixed that for next version! H

Pada tanggal Sab, 19 Agu 2023 pukul 11.52 Iñigo Urrestarazu-Porta <
***@***.***> menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/commit/278250c2700#diff-10734eff36dea31b55c3a24b82a3f94d3f5ba6e967c65e9e87992dc217c08ae1R880116
