### ISSUE TITLE
Timok Vlach

### ISSUE THREAD

**Issue by aluca1932** [glottolog/glottolog#1014]
There is a signifant issue with Timok Vlach included as such in glottolog. Namely, the main issue here is that in Eastern Serbia two subdialects of Daco Romanian are spoken, which immense differences and cannot be lumped together in any way.
Namely, in western part of Eastern Serbia (Branicevo, Pomoravlje and small part of Bor Disrict) Northern group of Daco Romanian subdialects is spoken represented by Banat Romanian (please noe that same dialect is spoken both in Serbian part of Banat and south of Danube in Eastern Serbia) and Southern group of subdialects represented by Oltean spoken in most of Borski and Zajecar District, but  also in northwestern Bulgaria.

These facts are known already at the beginning at the end of 19th and begining of the 20th century, through a research made by Gustav Weigand (Gustav Weigand, Linguistischer Atlas des dacorumänischen Sprachgebiets, Leipzig, Barth, 1909; Gustav Weigand, Die rumänischen Dialekte der kleinen Walachei, Serbiens und Bulgariens, Leipzig, Johann Ambrosius Barth, 1899).

These facts are well known and repeated numerous times by Romance languages linguist. Recently Academia Română has published 4 volume Linguistic Atlas of these dialects which show this split. Find atlases at http://inst-puscariu.ro/alti.html
This is a subject of current research on Romanian dialects south and north of Danube by Academia Română 
https://lingv.ro/2021/08/12/pn-iii-p4-id-pce-2020-0451_rodial-aldro-summary/
And contributions to the Atlas Linguarum Europea https://lingv.ro/atlas-linguarum-europae/
I didnt mention even 1 % of the research on this dialects, which I can provide upon request.
Further, it is a clear political project with the intention to represents Romanian diaĺects as a single dialect which can serve for the development of the new language.
This doesnt necessarily have to be bad, but is done in unprofessional manner by non-linguist as none of the linguist neither in Serbia nor abroad wants to participate in this. Even linguist mentioned in some recessions of the publications negated any participation in this.
More on this and the opinion of community members on this process please find in two volumes on politicization of this dialects as a single language published by Helsinki Committee in Serbia in Gacović, Slavoljub, From vlachized Serbs to Vlach language, second volume, Belgrade, 2019, 

https://www.helsinki.org.rs/serbian/doc/Knjiga%205-2.pdf

particularly in chapters 7. About "Vlach" script and deception of standardization of "Vlach language" and   9.  On publishing policy of all convocation of Vlach National Councils  and contribution to this volume by Ana Samardzic in chapter 10. LEXICOGRAPHIC AND TEXTBOOK LITERATURE IN "VLACH" AND ABOUT "VLACH LANGUAGE" - LINGUISTIC PERSPECTIVE 

For Glottolog is particularly relevant chapter 7. on deception of standardization.

On the reference material Glotolog mentions please find more in chapter 10 and 9

Also in the first volume https://www.helsinki.org.rs/serbian/doc/Knjiga%205-1.pdf

a detailed lexicography on the dialects spoken can be found in subchapter "Is the Vlach language a mother tongue of Romanians (Vlachs) of Eastern Serbia"

If relevant, I would like to bring your attention that this population was considered Romanian before 1945 ( from 1878) by Serbian and Yugoslav authorities and that there was no doubt that they are speakers by Romanian (more on official documents from that period at digital archive pretraziva.rs  and in two volumes by Gacovic). Also, Serbian scholars in this period never raised a doubt that they are Romanian speakers (Ðorđević, Tihomir, Kroz naše Rumune, Belgrae
Overall what is relevant in this case is that it impossble to create one language duet to significant differences between two dialects and that the process of creation of Vlach language doesnt have any genuine interest to preserve these dialects but to contribute to the final assimilation of the community, as community refuses to use the Vlach language, but due to the existence of this language, education and official use of Romanian is not possible.

Also I would like to bring your attention that first convocation adopted the decision that a standard Romanian should be the language of education and that due attention will be given to preservation of subdialects through cooperation with subdialect speakers in Romania, Vojvodina and Bulgaria.

Also, I would like to draw attention to the speakers of Banat Romanian who already developed a number of publications and a dictionaries www.vorbireabanata.com, which also includes collaboration of Eastern Serbia community experts, whose field work was included in the dictionary of Banat Romanian http://www.vorbireabanatana.ro/wp-content/uploads/2015/12/referinte_bibliografice.pdf

Although, I can provide you with numerous material and number of other articles (A. Sorescu Marinkovic, M. Huțuanu, O. Hedeşan from which I would single out recent book published by Austrian Academy of Science The VLACHS* of Eastern Serbia, Ideological Faction and Standardizaton of Vlach Language, https://www.austriaca.at/0xc1aa5576_0x003e362f.pdf ) I dont expect that glottolog will change the decision on including Timok Vlach as a separate category, knowing that Romanians are one of the most hated people o f Europe and that Glottolog giving legitimacy to this assimilation policies is something that can be expected. It is highely unlikely that Glottolog is not aware of the facts above, and that your policies have a clearly anti-Romanian character.
*VLACH here is not ethnic designation but the name of the project Vanishing Languages and Cultural Heritage

Allow me to cite part of article on the Vlach language written by professors of University of Belgrade, Department for Romanian language, Mariana DAN and Minerva TRAJLOVIĆ-KONDAN, Romanian Language Literacy in Vojvodina  and in Eastern Serbia. Premises and Consequences of Linguistic Languages and Political Dialects in Philologica Jassyensia”, an XII, nr. 1 (23), 2016, p. 151–168 

https://scholar.archive.org/work/gxk2wzv3ojhsdinmtvit63yli4/access/wayback/http://www.philologica-jassyensia.ro/upload/XII_1_Dan.pdf

to stay as a written trace of the shameful policies Glottolog fully suports and is through giving legitimacy (as in the future based on your data, we can expect that this creation receives a separate ISO language code)

The key element is its description what is Vlach language

In order to illustrate the situation, as transposed into English, imagine a textbook written in an idiom of the English language, let’s say, a cockney English manual, half written in the Latin alphabet, half in the Cyrillic, in which the same words, denominating the same thing, are written differently, in the same textbook, etc.

Further of grave consequences

The recommendations regarding minorities in Serbia are optimistic: “COUNCIL of EUROPE Committee of Ministers calls upon Serbia to PROVIDE TEACHING in/of all the MINORITY LANGUAGES at all levels, strengthen the teacher training and provide adequate teaching materials

Hovever, FACTS show DIFFERENTLY.

 We have had the opportunity to leaf through the newly issued manual of ‘Romanian language with elements of national culture’, dedicated to the children of Eastern Serbia. Standard Romanian being avoided (which is not the case of the Romanian language taught in Vojvodina), some strange texts have been issued, entitled, for example:“Panda învacă kung-fu” (Panda learns kung-fu). Those texts have been obviously produced by authors who are NEITHER PHILOLOGISTS, nor TEACHERS by profession, although the respective textbook is supposed to be USED by UNIVERSITY educated teachers in the process of teaching.

 In order to ILLUSTRATE the situation, as transposed into English, IMAGINE a textbook written in an IDIOM of the ENGLISH language, let’s say, a COCKNEY English manual, HALF WRITTEN in the LATIN alphabet, HALF in the CYRILLIC, in which the SAME WORDS, DENOMINATING the SAME thing, are WRITTEN DIFFERENTLY, in the same textbook, etc

. The intention of this textbook is, probably – at least judging by the title of the object of study (‘Romanian language with elements of national culture’) – supposed to support and preserve the anonymous oral cultural ‘legacy’ of the ‘Vlach’ rural tradition from immemorial times as ‘national culture’ and present it to the children of Eastern Serbia of today. However, the ‘tradition’ becomes here the subjective 

CREATION of its UTTERLY INCOMPETENT authors, who were probably NOT INTERESTED THEMSELVES in getting literate in their own mother tongue, or they COULDN’T ’t. 

After all, what is the character Panda representative for, as far as the Romanian tradition of Eastern Serbia is concerned? The same question can be asked about ‘kung-fu’. Moreover, the adopted form of writing, cannot be found in any software, and 

looks like a CIPHERED WRITING CODE, in which the letters ‘î’ and ‘ă’ are taken from the Romanian alphabet, while the Romanian letter ‘ţ’ is replaced by ‘c’. 

Therefore, the text CAN be READ only by a PERSON who is both LITERATE and FLUENT in ROMANIAN (LEVEL C1 AND C2), and in the course of reading it, the person can ’GUESS ’ the real WORDS, by noticing the UTTER MISTAKES made by the text authors.

 If we are well-meant, we can ask ourselves if the authors intended to make a sort of INNOVATIONAL EXPERIMENT with the children from Eastern Serbia, as if they were GUINEA PIGS – which is UNACCEPTABLE, CRUEL and SAD at the same time. What other conclusion can one draw in such circumstances of EXPERIMENTING not only with orthography, but with HUMAN RIGHTS as well? Not only does the textbook lack in literate texts, but it also lacks in RELEVANCE, both in the field of tradition and innovation. Moreover, it lacks a cultural orientation, a cultural framework and pedagogical methodology.  Any POSSIBILITY of TEACHING the children from Eastern Serbia something NEW and VALUABLE in their mother TONGUE is EXCLUDED. On the contrary, ‘The Tales for Children’, in the very title, are the first time mentioned as ‘ПОВЈЕСТЈИЈ дје копиј’ povjestjij dje kopij] 4 , and the second time (the same title) as ‘POVJEŠĆ dî kopij’ 5– the tales, as a genuine children’s nightmare, for which the grown-up authors have no excuse. As there is no explanation why the Latin alphabet is mixed up with the Cyrillic one, while teaching a language of Latin origin – and even doing so, why the SAME WORDS are presented with a DIFFERENT PRONUNCIATION (in the Cyrillic and in the Latin alphabet respectively) in the same textbook title? Does this situation show ANY GOOD WILL to synchronize this ethnic community with the rest of the world, as it was the case with the Romanian minority from Vojvodina? How can one possibly talk about DEMOCRATIC STANDARDS in EDUCATION, and not of DISCRIMINATION, if the solution was found for the education of the initially illiterate ROMANIAN minority of VOJVODINA in the thirties of the last century, while, for the ROMANIAN population of EASTERN SERBIA, SPEAKING the SAME IDIOMS of the Romanian language, it has not been found yet?  Having been deprived of school education in their mother tongue, of literacy, that is, having been deprived of the possibility of linguistic and cultural evolution and synchronization with the contemporary world, the Romanians from Eastern Serbia HAVE BEEN LEFT to live in ethno-linguistic ENCLAVES, to use an archaic/popular Romanian language with Slavic neologisms at home. Therefore, unlike the Romanian minority from Vojvodina, the Romanians from Eastern Serbia have been LARGELY ASSIMILATED by the majority Serbian population. Although there is PRACTICALLY NO DIFFERENCE between the ROMANIAN IDIOM from VOIVODINA and that from the EASTERN SERBIA, except for the degree of the speakers’ literacy in their mother tongue, the linguistic and cultural policy of the MAJORITY POPULATION is inclined to DEFINE the Romanian idiom from Eastern Serbia as a QUITE DIFFERENT ‘LANGUAGE ’: a ‘new’ language of NON-ROMANIAN IDENTITY.

 Is the Romanian IDIOM spoken in Eastern Serbia REALLY a different linguistic language, REQUIRING even the INVENTION of a NEW ALPHABET and ORTHOGRAPHY, or is it a new ‘POLITICAL DIALECT ’, ENHANCING a new, SERBIAN, IDENTITY of its speakers? If the Serbo-Croat linguistic identity (of ex-Yugoslavia) fell apart into more ‘political dialects’ (as R. Bugarski puts it), this seems to be the case of the Romanian idiom spoken in Eastern Serbia. IRONICALLY, the POLICY of ASSIMILATION is, probably, the only EXPLANATION WHY during the classes of ‘Romanian language with elements of national culture’, the CHILDREN from Eastern Serbia ARE TAUGHT about ‘PANDA ’ and ‘KUNG-FU ’. 

3.2. Criteria for Romanian National Minorities Textbooks

  It is obvious that the CRITERIA for choosing the texts for the Romanian minority of Vojvodina and those for Eastern Serbia are DIFFERENT. The difference is cultural policy, or ASSIMILATION. In the FIRST CASE, the Romanian language and culture are presented within the inevitable process of evolution, which is necessarily and ceaselessly going on in each and every nation. The AIM of the respective textbooks is to UPDATE the children, enabling them to make the RECEPTION not only of literary texts, but also of texts containing NOTIONS pertaining to the MODERN SCIENCES, represented in schools by the different objects of study in their mother tongue.

 In the SECOND CASE, the EXISTING TEXTBOOKS and CURRICULA view the Romanian language and folklore traditions as STATIC and DEAD phenomena, which must be preserved as such, as today ‘we have finally become aware’ that we are dealing with valuable cultural facts, undergoing a process of extinction. Although EXTINCTION goes hand in hand with the POLICY of ASSIMILATION, and although ‘the Vlachs’ from Eastern Serbia were NOT ALLOWED to open SCHOOLS and CHURCHES in their mother tongue, they are MADE RESPONSIBLE for their NOT having PRODUCED written TEXTS in their mother tongue… However, the rural Romanian minority of Vojvodina had not produced texts in their mother tongue either and, still, it was allowed proper education in their mother tongue. The textbooks of Vojvodina have had normal textbooks, suited to the vocabulary of each subject matter (as the majority population textbooks are). Even children belonging to the majority population learn modern, scientific terminology, which is one of the reasons why they are supposed to attend school. In this case, the ARGUMENT that the ROMANIANS from EASTERN SERBIA did not have a WRITTEN language CANNOT STAND either. It is not necessary to produce literary auctorial written works in order to be allowed to attend the contemporary subject matters in one’s mother tongue. Comparing the TEXTBOOKS of the majority Serbian population, and the textbooks of the Romanian minority of Vojvodina, the textbooks from Eastern Serbia seem to be a BIASED and INCOMPETENT MOCKERY, as shown above. Nowadays, having got university education themselves, teachers of Romanian tend to use, in their pedagogic practice, the manuals from Vojvodina to teach the children from Eastern Serbia, as the officially issued textbooks for this population are not practicable.   

3.3. The ISSUES of LANGUAGE, COGNITION and the SUBJECT Matters as Texts 

. Although the EUROPEAN DEMOCRATIC SOCIETY of today should give ALL individuals EQUAL CHANCES in having EDUCATION and textbooks for the different subject matters in their mother tongue, the ROMANIAN POPULATION from Eastern Serbia HAS BEEN LEFT BEHIND in this PROCESS of SYNCHRONIZATION with the global SCIENCE and CULTURE in their MOTHER tongue. THEIR FORM of SPEECH can be ONLY the POPULAR one, USED in CHILDHOOD, at HOME, in their linguistic ‘ENCLAVE ’. ‘Their’ ONLY ‘CHOICE ’ is to HAVE ONE PREPARATORY YEAR before attending SCHOOL, during which they LEARN SERBIAN, the majority population language in order to achieve literacy. As the evolution of the language goes hand in hand with the evolution of human society, the CHILDREN that live in LINGUISTIC ENCLAVES and do not have SCHOOLBOOKS in their mother TONGUE are COMPELLED to REMAIN further on in BACKWARD societies, UNLESS they decide to CHANGE their IDENTITY by studying in the language of the dominant culture, which they are COMPELLED to LEARN before attending school. In the discussion about literacy there is another aspect, which has been rarely mentioned, as a very DELICATE PERSONAL question is related to it: the COMPLEX of INFERIORITY of the ILLITERATE person belonging to an ETHNIC MINORITY group. We usually HEAR HOW how WONDERFUL a POPULAR LANGUAGE and ETHNIC culture HERITAGE IS and this statement is always related to the wonderfully preserved folkloric traditions in the enclaves. In FACT, the LITERATE people MOCK at the illiterate ones. The reason for mocking at them is not so much the ‘funny’ popular language they use, but the UNSCIENTIFIC, cognitive APPROACH.
…….

. The POINT is that the MAJORITY SERBIAN ethnic language community and the ROMANIANS from VOJVODINA have been GIVEN the possibility and the CHOICE to IMPROVE their LANGUAGE skills and, at the same time, ACQUIRE contemporary COGNITION of the WORLD – IF they WANT to; they have had textbooks for the different subject matters. As far as the ROMANIANS from EASTERN SERBIA are concerned, a DISCRIMINATING policy is still APPLIED, as their ONLY chance to become LITERATE is by RENOUNCING their MOTHER TONGUE, that is – RENOUNCING their IDENTITY. If the Romanian population from Serbia REMAINS ILLITERATE, such INADEQUATE ways of THINKING REMAIN a PROBABILITY, not only a POSSIBILITY. 

CAN we, then, SPEAK of the ‘BEAUTY ’ of the VLACH FOLKLORE and their well-known magic and ‘spells’, while we DO NOT ALLOW THEM to GET LITERATE in their MOTHER tongue? Are we CANDID when we say that we APPRECIATE their TRADITION, or their ‘traditional’ way of thinking, which might be as HILARIOUS as the case of the illiterate Serb mentioned above? Can we, therefore, ASSERT that such ‘FOLKLORE ’ WAYS of COGNITION are ‘characteristic’ of the ENTIRE ROMANIAN population of Eastern SERBIA, UNLESS it gets ASSIMILATED by attending Serbian schools, where they ACQUIRE a MODERN, updated COGNITION of the world? 

The CHILDREN from EASTERN SERBIA should not be DISCRIMINATED against, they should have the SAME RIGHTS as those from Vojvodina. 

5. Literacy and the INFERIORITY Complex  

5.1. Textbooks in One’s Mother Tongue from a Dyachronical Perspective 

 The HILARIOUS aspect of ILLITERACY in one’s MOTHER tongue, paralleled by an obsolete or INADEQUATE way of thinking (COGNITION) has CREATED INFERIORITY COMPLEXES within the inhabitants of all the Balkan countries, as Maria Todorova explains in her extensive study Imagining the Balkans (Todorova 2006: 105–106). Being an INHABITANT of the Balkans means being LOOKED DOWN at, not only by the world, the respective INHABITANTS themselves have an inferiority complex, as they themselves ADOPT ’the OTHER ’s’ OPINION about THEM and would LIKE to be ‘DIFFERENT ’, to be ‘SOMEBODY ELSE ’. 

The same goes for the Romanian speaking population of Eastern Serbia: they WOULD rather BE ‘SERBS ’, and have ACCESS to EDUCATION, than been LOOKED DOWN on.  What Todorova does not ponder upon sufficiently while speaking of the inferiority complex of the inhabitants of the Balkan countries is the fact that, due to historical hardships (the Ottoman and Austro-Hungarian Empire occupation, for example), the Balkan countries had relatively late access not only to mass education, but also to the standardization of the respective languages. It was only in the 19th century that the standardization of the majority national languages of the Balkans underwent the process of massive education in schools, relying on textbooks which made possible the same way of pronouncing (reading) and writing, in order to be able to acquire the basis of the contemporary cognition of the world. It was only in this way that the population of the national states of Eastern Europe was enabled to their synchronization with the Western European society.

 It WAS EDUCATION in one’s MOTHER tongue that laid the basis of ACQUIRING an equally standardized SCIENTIFIC CORPUS, by ENRICHING the childhood LANGUAGE with new notions.

……..

. Therefore, they SHOULD NOT BAN the LITERACY in their MOTHER tongue of the MINORITIES having LIVED TOGETHER with them for CENTURIES. The more so as the ROMANIAN minorities from Vojvodina and Eastern Serbia have always been FAITHFUL and DEDICATED to the majority Serbian aims in history.  

5.2. Dominant versus Non-Dominant Cultures of the Region. 

Assimilation and Auto-Assimilation

 The non-dominant cultures of the region, existing within the dominant ones, have had troubles in this process of synchronization with the European standards. 

In spite of all RHETORIC promoting DEMOCRACY and human RIGHTS, the countries that have recently become sovereign and independent seem to, practically CONSIDER the ethnic MINORITIES as an IMPEDIMENT to their own national enthusiasm and would rather ASSIMILATE them, which is a process founded on DEPRIVING those minorities of their national IDENTITY, by NOT allowing them to OPEN SCHOOLS, printing houses, and have religious service in their mother tongue, by not ALLOWING them to DECIDE by THEMSELVES what nation they IDENTIFY with. 

Let’s look, for example, nowadays at Croats, fighting to ban the traditional Serbian Cyrillic writing, used by the Serbian minority in Croatia (in the town Vukovar, for example). The paradox is that Croats and Serbs speak linguistically the same language, but, obviously, two different ’political dialects’, as R. Bugarski puts it. The same relation between majority and minority population is to be noticed in Serbia, trying to impose the cyrillic writing to the Vlach population, speaking a Romance language, of Latin origin, for which the Latin alphabet is probably better suited; the same goes for the endeavor to differentiate the Romanian minority of Vojvodina and the one from Eastern Serbia, that PRACTICALLY SPEAK the SAME ROMANIAN language IDIOM and can be JUDGED SEPARATELY only from the POINT of view of the LEVEL of LITERACY they can achieve in their mother tongue.  As opposite to the tendency of the dominant cultures to synchronise with the modern world, the process of ENCLAVISATION of the ROMANIANS from Eastern Serbia leads to their INFERIORITY COMPLEX, due to ILLITERACY in their mother tongue, that is, due to the RESTRICTED POSSIBILITIES of THOUGHT and EXPRESSION in it. What Maria Todorova defined as the INFERIORITY COMPLEX of the populations in the Balkan countries, who take over and adopt the negative opinion about them produced within the dominant cultures, is EQUALLY valid as a process, when the RELATION between a MAJORITY and a MINORITY POPULATIONof the same country are concerned. It is ILLITERACY that INDUCES the INFERIORITY COMPLEX in the MINORITY population, which ENGENDERS the need ’to be SOMETHING ELSE ’ within this population,– that is, to CHANGE language, change IDENTITY in order to get EDUCATED. ASSIMILATION can be therefore, practically regarded as AUTO-ASSIMILATION. Therefore, the very PROCESS of ASSIMILATION is founded, in the first place, on BANNING ACCESS to LITERACY in one’s mother tongue, which INDUCES an ETHNIC INFERIORITY complex, FINALLY leading to one’s RENOUNCING one’s own native IDENTITY and ASSIMILATION into majority population identity. The VLACH INTELLECTUALS, academically educated and living in an urban background together with the majority Serbian population, will RATHER NOT MENTION their true ORIGIN, which is silently RELATED to the fact of being BACKWARD. In one of his poems in Serbian, Adam Puslojić, a famous Vlach poet, mentions ‘sir i sifilis’/‘CHEESE and SYPHILIS ’, as a NEGATIVE IDENTITATARY connotation for the Vlachs. The INFERIORITY complex GOES so FAR that, for example, INTELLECTUALS of  BELGRADE of the same VLACH origin AVOID speaking to EACH OTHER in their mother tongue.  Unfortunately, the poverty of the Vlach/Romanian language is a mere truth, unless the Vlach attend education in the non-maternal, Serbian language, or German, if the family emigrates to Germany or Austria, usually leaving entire villages bare. On the other hand, the children of Vlach parents origin who live in Belgrade, usually cannot speak Romanian; they might understand it a little, if their grandmothers came to town to take care of them. It is hard to say how they feel about their own identity, but they would RATHER GIVE up their ROMANIAN ORIGIN and be ‘SOMEBODY ELSE ’, as they are AWARE of the ILLITERACY in their MOTHER TONGUE with a feeling of SHAME.  The VLACH IDENTITY issue is not only FOUNDED on ILLITERACY, but also on the POLITICALLY MAINTAINED CONFUSION of terminology, as an ALIBI in the process of ASSIMILATION. If one asks a Vlach in Romanian the question ‘What are you?’ (’CE EŞTI TU?’), they will say ‘EU mi’s RUM N ’ (’I’m a Romanian’), but if one asks the same question in Serbian: ‘Šta si ti?’, they will answer ‘Ja sam VLAH ’ (‘I am a Vlach’), which is the name the MAJORITY Serbian population uses to DEFINE the ethnic origin of the ROMANIANS from Eastern SERBIA. And it is ONLY in that WAY that they are ‘DIFFERENT ’ from the Romanian minority of Vojvodina, who will ANSWER even in SERBIAN that they ARE ROMANIANS. It is evident that, as Maria Todorova puts it, the ROMANIANS from Eastern SERBIA ADOPT (when speaking in Serbian, i.e. with Serbs) the OPINION of the MAJORITY population ABOUT THEM, while, the more LITERATE ROMANIANS of the Romanian minority of Vojvodina DO NOT. This HAPPENS in SPITE of the fact that the TWO populations are PRACTICALLY of the SAME ORIGIN, as we have shown above. However, if one asks WHAT LANGUAGE they speak, the REPRESENTATIVES of both Eastern Serbia region and Vojvodina WILL SAY they SPEAK ROMANIAN. If, for the moment, we ignore the identity issues and look at the terminological difference between the notions of Vlachs and Romanians, we COME to a LINGUISTIC ISSUE occurring FREQUENTLY: the USE of DIFFERENT WORDS/names for the SAME reality. For example, the same town of Vienna (Wien-germ.) is called differently in various languages; the town is known as Beč in Serbian. Similarly, the same ethnic Romanian idiom speaking individuals of Eastern Serbia are called in Serbian ‘Vlachs’, while they call themselves ‘Romanians’, when speaking Romanian. If asked what language they speak, they will say they speak Romanian. In the past, the SOUTHERN part of today’s ROMANIA, which is North of the river Danube used to be called VALLACHIA, which points to another PARADOX: by NAMING the population SOUTH of DANUBE as VLACH, the Serbs do NOT DEFINE it as NON-ROMANIAN, as it INTENDS to, but AS a LINGUISTICALLY ROMANIAN population, while, in practice, it MAKES an INADEQUATE discrimination between this population and the Romanians from Vojvodina, as far as literacy in one’s mother tongue is concerned. We must mention the fact that Romania has never had any territorial requests from Serbia in history, and vice versa, and the good Serbo-Romanian relations stand as an outstanding example of historical friendship – which is also an important argument to allow the population of Eastern Serbia get literate in their mother tongue. With respect to the excellent Serbo-Romanian relations, the famous Romanian historian, Nicolae Iorga (also one of the founders of the Institute for Balkan Studies within the Serbian Academy) said that Romania has got only two valuable friends at its territorial borders: the Serbs and the Black Sea.  The ethnic DILLEMA of the Romanians of Eastern Serbia has been BUILT UP. The REAL DIFFERENCE between the Romanian minority from VOJVODINA and the VLACH population is the fact that the FIRST has ATTENDED at least elementary SCHOOL in Romanian, while the SECOND was NOT GIVEN the right to, on the PREMISES that VLACHS are SOMETHING DIFFERENT than the Romanians. However, if literacy itself is left aside, CHILDREN from ROMANIA, children from VOJVODINA, and children from EASTERN SERBIA could VERY WELL UNDERSTAND each other. After attending school in their mother tongue, ADULTS from ROMANIA and from Vojvodina could express more abstract thoughts, while those from EASTERN SERBIA could do that to a MUCH SMALLER EXTENT, which REFLECTS their being DISCRIMINATED AGAINST. WHY should a child from VOJVODINA have the PRIVILEGE to learn a common Romanian language, at least, while the child from EASTERN Serbia should ADOPT in school the LANGUAGE of ‘THE OTHER ’?   ASSIMILATION of the non-dominant cultures by the dominant ones seems to be an INEVITABLE process, in the long run – this is a statistic fact. Moreover, in the era of mass-media, globalization, multiethnic and multicultural communication, ethnic enclaves disappear. The younger population belonging to both Romanian ethnic minority from Vojvodina, and to Eastern Serbia, usually speaks Serbian fluently. Hovever, a DIFFERENCE in BEHAVIOR can be IDENTIFIED, while comparing the representatives of the two Romanian minority groups: while the persons from the FIRST GROUP will TALK about their ROMANIAN IDENTITY, the individuals of the SECOND will rather HIDE their ORIGIN – we have noticed this behavior PATTERN even among OUR STUDENTS, who chose Romanian as an object of academic studies. Having had the possibility of being educated in their mother tongue, in elementary school at least, by means of appropriate textbooks, the Romanian minority population of Vojvodina do not feel the urge to hide their mother tongue and origin, while the Vlachs do. Moreover, this kind of approach to education in one’s mother tongue, as practiced in Voivodina, does not diminish the students’ bilingual skills, as they are usually fluent in both Serbian and Romanian, while the representatives of the Vlach population are not. 

 6. Conclusion as Question for Eastern Serbia Textbook Authors

 The question ‘WHY the poet of Vlach origin ADAM PUSLOJIĆ is NOT PRESENT in Eastern Serbia textbooks?’ – brings us back to the beginning of this paper, where the issue of RECEPTION is discussed. Literary reception is a complex process, tied to the recognition of cultural values. However, as language goes hand in hand with the process of cognition, in order to attain that STAGE of VALUES AWARENESS, it is essential for a community to LINGUISTICALLY (i.e. in terms of cognition) EVOLVE from the stage of the POPULAR language, through the stage of COMMON language, to that of LITERARY language (Capidan 1943: 4). Textbooks for the Eastern Serbia children are NOT SUPPOSED to CONTAIN literary TEXTS in elementary school. But they are supposed to present, at least, texts of common language, in which elementary scientific ideas are given to improve the child’s vocabulary and cognition of the contemporary world – as those ideas are given to Serbian, or Romanian children from Vojvodina. By acquiring at least the ’common language’ skills, children from Eastern Serbia are not supposed to read their co-national poems in Romanian, but could at least get informed that Adam Puslojić is a valuable poet of Vlach origin, writing equally in Serbian and Romanian – which is, culturally speaking, at least as important for the Vlach community as Panda and kung-fu...   With the EXISTING TEXTBOOKS, made up by INCOMPETENT AUTHORS, who preferred to remain ANONYMOUS, we ASK ourselves if the VLACHS WILL EVER be ABLE to read Adam Puslojić’s poetry written in Romanian, his and their mother tongue, or they must have the verse transposed into the Romanian popular idiom they use in childhood, as written in the cyrillic form, as it is ’desirable’ for the architects of the ’new-born’ Eastern Serbia political dialect. For now, we will give our translation of this identity ’Vlach’ tragedy from Romanian into English,: ‘…

My writing is my coffin, not/  anything else. A sign,/ Logos, a word/  of a beginning./ I’m starting now./ I’m writing/ a coffin, a new coffin/.’ (‘…Scrisul meu/ este sicriul meu, nu/ altceva. Un semn/ un Logos, un cuvânt/ al începutului. / Încep acum. Scriu/ un sicriu, un nou sicriu./’ Scris înăuntru/ Written inside) 6(Puslojić 1995: 13). 

The Vlach textbooks INVENTING NEW ROMANIAN ‘LANGUAGE STANDARDS ’, new alphabets, etc., NOURISH a CONFUSED IDENTITY of the respective minority population. Therefore, the Vlach identity issue is NOT LIKELY to be SOLVED soon, metaphorically representing, as the Vlach poet Adam Puslojić puts it: ‘a COFFIN, a NEW COFFIN ’. It seems that this population’s LITERACY in their mother tongue is a VAIN, almost POETICAL, DREAM – while for the Vlachs the ONLY REAL and TRUE solution is ‘to WRITE INSIDE ’, i.e. to KEEP their IDENTITY for themselves. It is interesting to note, in Romanian, the alliteration between ‘scriu’ and ‘sicriu’ (‘I write’ and ‘coffin’). The dominant culture has now finally allowed the production of textbooks for the children of Eastern Serbia. However, those INCOMPETENT and BIASED textbooks are OBVIOUSLY ‘NEW COFFINS ’ for the Vlach ETHNIC, LINGUISTIC and CULTURAL IDENTITY, as the children are not taught to write in their mother tongue – as if WRITING in ROMANIAN were a sort of a ‘DEAD ISSUE ’

So, the proposal is to reclassify Timok Vlach as it does not exist from a simple that these are two distinct dialects which under no circumstances can be lumped together. For the same reason Timok Romanian is equally inadequate name, as it is imposing non existent language unity

Only appropriate terms would be Banat Romania in Serbia including both speakers from Vojvodina and part of East Serbia and Oltean in Serbia and Bulgaria including the most eastern area of Serbia and north western Bulgaria.

**Comment by d97hah** [comment]
I will indeed split Timok as requested for next version, but I can't
comment on the remainder of the message. all the best, H

Pada tanggal Sel, 22 Agu 2023 pukul 22.54 aluca1932 <
***@***.***> menulis:

**Comment by aluca1932** [comment]
Please let me know if you a you would like me to provide with a very abudant dialectological material on these two dialects

**Comment by aluca1932** [comment]
I made a mistake by labelling as not closed
