### ISSUE TITLE
Isolate confusion clarification for next release please

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#1015]
For the next glottolog release, could you consider either or both of these suggestions please.

```
a) add a field called "Isolate" which is true or false if the languoid is an Isolate. This value should be TRUE for the top-level node (for example basq1248) and its descendants (for example alto1238), i.e. both for languoids of the level "language" and "dialect".

b) add documentation somewhere regarding the way level and Family_ID works for Isolates. Afaik these statements are true:

* Isolates have no top-level languoid that is of the level "Family". Instead, they have a languoids of level "language" as the first glottocode in the classification tree. If there are dialects, the dialects have a Family_ID that maps onto this languoid parent that is of the level "language". This makes their Family_IDs unusual, in that they map onto a glottocode that is of the level "language" instead of "family. Other dialects, for example amer1259, have a Family_ID glottocode that maps onto a languoid of the level "Family".
* the top level languoid in an isolate has missing value for Family_ID and has the level "language". They can be identified in this manner, as all other languoid with missing Family_ID are of the level "family".
* the descendants of Isolate languages (dialects) cannot be as easily identified as isolates, as one needs to look up the level of the Family_ID glottocode.
* if (a) is implemented, add "Isolates can be identified by the column/field 'Isolate'"

```
I've had to explain this multiple times to collaborators who don't understand this structure and are confused when they use language tables in various cldf-datasets. I would prefer it if both (a) and (b) could be implemented to reduce confusion. 

Thank you.

**Comment by xflr6** [comment]
Thanks Hedvig.

> add documentation somewhere regarding the way level and Family_ID work

IIUC, this is about https://github.com/glottolog/glottolog-cldf/blob/master/cldf/languages.csv, so maybe then this issue could be moved to https://github.com/glottolog/glottolog-cldf?

There is no proposal here to change in organization in the curated data or to change the glottolog.org website, correct?

> the descendants of Isolate languages (dialects) cannot be as easily identified as isolates

I am not completely sure I follow why we should consider/tag dialects of isolates as isolates, would't that be confusing (IIRC, currently isolates are just language-level languoids that to not have a family, i.e. a parent, so they are at the top-level)? 

+1 that if dialects of isolates have the isolate as `Family_ID` then maybe something like `Parent_ID` might be better.

**Comment by HedvigS** [comment]
> Thanks Hedvig.
> 
> > add documentation somewhere regarding the way level and Family_ID work
> 
> IIUC, this is about https://github.com/glottolog/glottolog-cldf/blob/master/cldf/languages.csv, so maybe then this issue could be moved to https://github.com/glottolog/glottolog-cldf?
> 
> There is no proposal here to change in organization in the curated data or to change the glottolog.org website, correct?

Depends on how you want to proceed. I'd add a field "Isolate" to the md.ini files in glottolog/glottolog, but you may chose another approach.

> I am not completely sure I follow why we should consider/tag dialects of isolates as isolates, would't that be confusing (IIRC, currently isolates are just language-level languoids that to not have a family, i.e. a parent, so they are at the top-level)?

I don't understand what you mean. Dialects who are daughters of isolates are isolates. Unless dialect means something else than what I've understood dialect to mean before in Glottolog? 

> +1 that if dialects of isolates have the isolate as Family_ID then maybe something like Parent_ID might be better.

I don't think that needs to change.

There is already Language_ID (which i've lobbied for to be changed to Language_level_ID) which tracks the glottocode of the parent of a dialect which itself has the level language. In a way, if Language_ID == Family_ID, that's one way of knowing that a dialect is the daughter of an Isolate :)

**Comment by xflr6** [comment]
>>     There is no proposal here to change in organization in the curated data or to change the glottolog.org website, correct?

> I'd add a field "Isolate" to the md.ini files in glottolog/glottolog, but you may chose another approach.

That won't be necessary IIUC that the column you would like to add to `languages.csv` can be derived from the existing information (the data repo should be normalized, i.e. avoid repetition where possible to avoid update anomalies).

>  Dialects who are daughters of isolates are isolates.

My uderstanding is that 'isolate' implies/requires language -- so the term would not be applicable to dialects (to me 'isolate dialect' sounds odd). But let's see what others think.

**Comment by HedvigS** [comment]
@xflr6 whatever you can do to clarify this would honestly help, I'm a bit tired of explaining it again and again ^^!

**Comment by d97hah** [comment]
Like sebastian says, the information on which languoid is an isolate is
derivable from information already in the repo so we won't add that. The
solution to the practical demand could be better with a ready implemented
predicate in pyglottolog or the corresponding R package if there is one.
The same goes for dialects (to me 'isolate dialect' rings wrong too but
anyone is free to define their own terminology). all the best, H

Pada tanggal Sen, 28 Agu 2023 pukul 14.04 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
If you want to avoid confusion among cldf-users in language tables, I would strongly suggest making a col like "Isolate" a part of the way LanguageTable is rendered. Perhaps that's a question for pycldf ro cldfbench, that's up to you.

I do not think that making a function in pyglottolog or in a corresponding R-package would be enough, I'm afraid. I can suggest one to @SimonGreenhill 's rcldf if you think that'd help.

**Comment by HedvigS** [comment]
Function suggested to rcldf https://github.com/SimonGreenhill/rcldf/pull/31
