### ISSUE TITLE
reference and update for Tibetic Languages

### ISSUE THREAD

**Issue by eroux** [glottolog/glottolog#1021]
A new open access book has been published on the whole Tibetic family: 

Nicolas Tournadre and Hiroyuki Suzuki. 2023.
The Tibetic Languages: an introduction to the family of languages derived from Old Tibetan
Publications, Collection Diversités des langues, 1151 p. 17 maps, ISBN : 978-2-490768-08-0
https://lacito.cnrs.fr/the-tibetic-languages/

It might have an upated "family tree" for this family

**Comment by d97hah** [comment]
Yes I am going through it. It's tree is similar to the combination of
Suzuki and Tournadre's earlier writings so no major changes, but more
details added.

Pada tanggal Rab, 20 Sep 2023 pukul 11.46 Elie Roux <
***@***.***> menulis:
