### ISSUE TITLE
Change Mara Chin dialect

### ISSUE THREAD

**Issue by Beilaitei** [glottolog/glottolog#1022]
Mara language is spoken by the Mara people who live in Chin State, Myanmar, and Chhimtuipui district in India. The Mara people in Myanmar are used to being called 'Mara Chin,' but this term is not used in India. It is better to change the name of the 'Mara Chin' dialect to simply 'Mara' since the Mara people who live in India outnumber those in Myanmar, and they do not refer to themselves as 'Mara Chin.'

**Comment by Beilaitei** [comment]
Additionally, the Mara language can be studied here:
Wikipedia: https://en.wikipedia.org/wiki/Mara_language
The book: A Phonetic, Phonological, and Morphosyntactic Analysis of the 
Mar Mara Language by Arden, Michelle J. (2010)
https://scholarworks.sjsu.edu/cgi/viewcontent.cgi?article=4740&context=etd_theses

**Comment by d97hah** [comment]
There's a number of other languages in the world called Mara and Glottolog
has global view on namespaces so calling this one Mara Chin is a suitable
disambiguator even if the Mara in India do not use this name. The Arden
thesis is already in the Glottolog refs. all the best, H

Pada tanggal Sab, 23 Sep 2023 pukul 10.38 Teitei ***@***.***>
menulis:
