### ISSUE TITLE
Split Mosetén-Chimane into different varieties

### ISSUE THREAD

**Issue by Tarotis** [glottolog/glottolog#1024]
Current glottocode: mose1249

According to Sakel (2009, Mosetén & Chimane (Tsimane')), Mosetén and Chimane should be considered separate entities. Linguistically, there are three different varieties: Mosetén of Covendo, Mosetén of Santa Ana, Chimane. The Santa Ana variety is mutually comprehensible with both of the other two, which is not the case for Mosetén (Covendo) and Chimane. Ethnologically, however, the Mosetén identify as a single people. As I am not sure what kind of evidence is preferred, I think these would be two options:

a) Add three dialectal glottocodes for each variety, to correctly refer to the individual varieties.
b) Split Mosetén and Chimane to two languages, according to the ethnological identification.

Covendo: [-15.7901, -66.9754](https://www.openstreetmap.org/#map=16/-15.7901/-66.9754)
Santa Ana: [-15.4961, -67.2162](https://www.openstreetmap.org/#map=14/-15.4961/-67.2162)
Chimane: [-15.214, -66.6431](https://www.openstreetmap.org/#map=11/-15.214/-66.6431)

**Comment by d97hah** [comment]
The claim of non-intelligibility is somehow contradicted by Sakel 2009 and
the Chimane missionaries. I've also asked for clarification from other
linguists working in Bolivia. But will add the dialectal glottocodes
(option a) for next version. all the best, H

Pada tanggal Sab, 30 Sep 2023 pukul 22.18 Frederic Blum <
***@***.***> menulis:

**Comment by Tarotis** [comment]
Thanks! Totally fine with the dialectal glottocodes, as I have no primary information about the intelligibility.

**Comment by xrotwang** [comment]
Partly addressed in https://github.com/glottolog/glottolog/commit/81e346a37d4634be8c713ea4426adc68f03d6d70
@d97hah Do we want to include the geocoords given by @Tarotis above, too?

**Comment by d97hah** [comment]
Yes, since we don't have dialect coordinates systematically I didn't bother
putting them in, but can do, or if you beat me to it, feel free to do so! H

Pada tanggal Jum, 6 Okt 2023 pukul 15.27 Robert Forkel <
***@***.***> menulis:
