### ISSUE TITLE
add code for Thiek?

### ISSUE THREAD

**Issue by quail4sale** [glottolog/glottolog#1028]
I am requesting a code for the Thiek variety of Hmar on behalf of a linguist in the process of adding Thiek documentation to the CoRSAL archive. She is hoping to avoid conflation with Khawsak, Hmar's literary variety, represented by hmar1241/ISO 639-3 hmr.

My understanding is that Thiek's relationship to Khawsak/other Hmar varieties has not been studied, though her preliminary investigation suggests substantial differences. Here is the information she's provided from her recent field trip and local contacts, plus what I've found in the literature:

Thiek is a variety of Hmar spoken by around 3000 people throughout 20-30 villages in Assam, India. Speakers are concentrated in the Dima Hasao and Cachar districts of Assam, and also reported to live in Manipur and Meghalaya. Alternate names include ‘Khawthlang’ and ‘Thiekatuol.’ Thiek is minimally covered in linguistic or ethnographic publications beyond its status as a Hmar sub-clan. The people are among the largest Hmar sub-clans (Borah, 2017; Khawbung, 2021a); the variety is the most widely spoken other than Khawsak (Infimate, 2019).

Dr. Vanlalthluonga Bapui is a linguist from a Thiek village in the Cachar district of Assam. He claims that Thiek constitutes a unique variety, if not a separate language altogether. He cites related Hmar sub-clans which are recognized as linguistically distinct from Khawsak (e.g., Sakachep, Hrangkhol, Saihriem, Chothe). His early work was on Khawsak (grammar, Hmar-English dictionary). More recently, he formed the Thiek Pahnam Association, a literature society promoting further research and development of written resources. Although no writing system has been formalized, Dr. Bapui published the volume ‘Thiek Tawng: Thiek tawnga lekhabu um sun’ in 2016 using the roman alphabet.

Khawbung (2021b) includes some samples of spoken Thiek in the short documentary ‘Thiek Tawng.’ Khawbung reports that speakers use Khawsak in public settings, leading to decreased use of Thiek overall. Still, in certain areas like Huonveng village, Thiek is spoken across generations in various domains–at play, in the home, in local shops, and even in church and school to some degree (Khawbung, 2021b).

References
- Bapui, Vanlalthluonga. (2016). Thiek Tawng. Thiek Pahnam Association.
- Borah, Ashim. (2017). Ethnographic Report on the Hmars of Assam. Assam Institute of Research for Tribals and Scheduled Castes. https://repository.tribal.gov.in/handle/123456789/74137?viewItem=browse.
- Infimate, Marina L. (2019). Clause structure in Hmar. [Unpublished dissertation]. North-Eastern Hill University, Department of Linguistics. http://hdl.handle.net/10603/341250.
- Khawbung, Margaret L. (2021a). Traditional Institutions of the Hmar Tribe in Northeast India. Kanchioli Journal of Humanities and Social Sciences, 1(1): 42-55. https://lgcjournal.in/issue/1/Paper_5.pdf.
- Khawbung, Grace R. (2021b). Thiek Tawng. University of Delhi, Department of Anthropology. https://youtu.be/tN9wZutq6G0?si=c4NDgsPeXVSJ6kYj.

**Comment by d97hah** [comment]
I'll add Thiek as a dialect for next version. The code will be thie1234. As
a dialect rather than a language because from what you write
unintelligibility to Khawsak cannot be asserted. In fact, Baruah & Bapui
(1996:3) say "... Khosak, Thiek, Hrangkhol, Biete, Faihrlem, and Sakachep.
The differences among them, however, are marginal." where the second author
is that same DLT Bapui from Thiek village. Of course, the claim that the
differences are marginal might in the end be wrong (and some doubt is cast
on it by the fact that other authors say the others varieties are more
different than marginal and have their own iso and glottocodes), so I'd be
happy to learn more in the future.

Baruah, P. N. Dutta & V. L. T. Bapui. (1996) Hmar Grammar. Mysore: Central
Institute of Indian Languages.




Pada tanggal Rab, 11 Okt 2023 pukul 20.55 quail4sale <
***@***.***> menulis:

**Comment by quail4sale** [comment]
I agree that dialect is best until more information is available. Thanks so much, that's a huge help!

**Comment by quail4sale** [comment]
Realizing I had accidentally marked the issue 'closed' with my reply--apologies for any confusion!

**Comment by xrotwang** [comment]
See
```
$ glottolog tree hmar1241
INFO    glottolog/glottolog at /home/robert/projects/glottolog/glottolog
Sino-Tibetan [sino1245]
   └─ Kuki-Chin-Naga [kuki1245]
      └─ Kuki-Chin [kuki1246]
         └─ Central Kuki-Chin [cent2330]
            └─ Core Central Kuki-Chin [cent2005]
               └─ Mizoic [mizo1244]
                  └─ Hmaric [hmar1240]
                     └─ Hmar-Saihriem [hmar1242]
                        └─ Hmar [hmar1241]
                           ├─ Khawsak [khaw1234]
                           └─ Thiek [thie1234]
```
