### ISSUE TITLE
Ná-Meo most closely related to Southern Qiandong Miao according to Hsiu 2015 (computational lexical analysis of Hmong-Mien languages using SplitsTree 4)

### ISSUE THREAD

**Issue by Arctic-Circle-System** [glottolog/glottolog#1031]
According to _[The classification of Na Meo, a Hmong-Mien language of Vietnam](https://zenodo.org/records/1127804)_, written by Andrew Hsiu, [Ná-Meo](https://glottolog.org/resource/languoid/id/name1237) is most closely related to Southern Qiandong Miao, and that Northern and Eastern Qiandong Miao are more closely related to each other than to Southern Qiandong Miao. In addition, the same analysis also suggests that Younuo is a [Sheic](https://glottolog.org/resource/languoid/id/jion1235) language rather than a [Bahengic](https://glottolog.org/resource/languoid/id/pahe1239) language, with She being most closely related to Jiongnai Bunu rather than Pa Na, and Pa Na being more closely related to Jiongnai Bunu and She than to Younuo.

**Comment by d97hah** [comment]
Thanks I had seen the Na-Meo paper and concluded it was close enough to S
Qiandong Miao (migration in the 1800s) to count as the same language, and I
had forgotten it had its own ISO 639-3 from the time when there was no data
on it. The separate ISO 639-3 entry might be justified if the separation of
Na-Meo and the non-Zhenmin varieties of S Qiandong Miao is deeper than the
1800s plus some contact induced change, which ight well be the case. I'll
adjust for next version. Re the clf of Yuonuo, the 2015 handout has a lex
sim phylogram which is not the best indicator of genealogical relationship
(there are indeed some other minor differences to the Glottolog tree). I
have on my to-get list the book by Li (2018), and when I get it I will
update as needed. all the best, H

Pada Jum, 20 Okt 2023 pukul 08.42 Arctic Circle System <
***@***.***> menulis:

**Comment by Arctic-Circle-System** [comment]
Thank you for your response. Should I leave the issue open or close it until the relevant changes are implemented?

**Comment by Arctic-Circle-System** [comment]
Also, if I may ask, what sorts of studies are generally considered good indicators of genealogical relationships?

**Comment by d97hah** [comment]
You can close it wrt to https://github.com/glottolog/glottolog/pull/1034

Pada Sel, 24 Okt 2023 pukul 23.00 Arctic Circle System <
***@***.***> menulis:

**Comment by d97hah** [comment]
see https://glottolog.org/glottolog/glottologinformation point 6

Pada Kam, 26 Okt 2023 pukul 22.07 Arctic Circle System <
***@***.***> menulis:

**Comment by xrotwang** [comment]
see #1034
