### ISSUE TITLE
Genealogical relationship between the Chibchan and Macro-Jê languages proposed by Matthias Pache

### ISSUE THREAD

**Issue by Arctic-Circle-System** [glottolog/glottolog#1032]
Matthias Pache recently proposed a genealogical relationship between the Chibchan and Macro-Jê languages in an article in the International Journal of American Linguistics, _[Evidence For A Chibcha-Jê Connection](https://www.journals.uchicago.edu/doi/abs/10.1086/723641)_. According to the abstract, "The Chibchan and Macro-Jê forms discussed here reflect regular sound correspondences and, additionally, include shared idiosyncrasies, such as corresponding suppletion."

**Comment by d97hah** [comment]
Unfortunately this paper fails to prove such a relationship. It's nowhere
near fulfilling the basic requirements. all the best, H

Pada Kam, 26 Okt 2023 pukul 22.29 Arctic Circle System <
***@***.***> menulis:
