### ISSUE TITLE
Errors in documentation statuses (Nakh-Daghestanian)

### ISSUE THREAD

**Issue by timur-maisak** [glottolog/glottolog#1043]
There are some unsatisfactory decisions concerning the documentation status of some Nakh-Daghestanian languages:
- Merdanova, S. and Daniel', M. 2001 is not a GRAMMAR of Agul, it is just one of (dozens) short papers on Agul grammar. There are quite a few publications on Agul, some of them can be treated as "real" grammars here, see e.g. here: https://ru.wikipedia.org/wiki/Агульский_язык#Грамматика 
- T'ogo E. Gudava 1962 is a GRAMMAR of Botlikh, why grammar sketch?
- Magomedbekova, Zagidat M. 1967 is a GRAMMAR of Northern Akhvakh, why grammar sketch?
- why do you treat Velieva, Èl'mina Abasovna 2007 and Abdulaeva, I. A. 2001 as grammar sketches, not grammars? By the way, these are not "MA theses", but rather "PhD theses"
- Shamilov, Saidamin and Paskushova, Elza 2005 is not a LONG GRAMMAR, this is a book on verbal conjugation only
- Kazenin, K. I. 2013 is not a LONG GRAMMAR, this is a book on syntax only
- Maria Polinsky 2015 is not a LONG GRAMMAR, this is a book on syntax only
- Uslar, Petr K. 1979 is a long grammar written in the 19th c. (published in 1979), there are much more recent sources on Tabasaran, including "long grammars"

**Comment by d97hah** [comment]
Pada Min, 26 Nov 2023 pukul 13.46 Timur Maisak ***@***.***>
menulis:

> There are some unsatisfactory decisions concerning the documentation
> status of some Nakh-Daghestanian languages:
>
>    - Merdanova, S. and Daniel', M. 2001 is not a GRAMMAR of Agul, it is
>    just one of (dozens) short papers on Agul grammar. There are quite a few
>    publications on Agul, some of them can be treated as "real" grammars here,
>    see e.g. here: https://ru.wikipedia.org/wiki/Агульский_язык#Грамматика
>
>
This is because of computerized assignment
https://glottolog.org/meta/glossary. They do more good than harm but for
high-fidelity documentation status one needs to take out all computerized
assignments. Anyway, I've fixed the individual case for next version.


>
>    - T'ogo E. Gudava 1962 is a GRAMMAR of Botlikh, why grammar sketch?
>    - Magomedbekova, Zagidat M. 1967 is a GRAMMAR of Northern Akhvakh, why
>    grammar sketch?
>    - why do you treat Velieva, Èl'mina Abasovna 2007 and Abdulaeva, I. A.
>    2001 as grammar sketches, not grammars? By the way, these are not "MA
>    theses", but rather "PhD theses"
>
> I believe these cases are consistent with the definition of grammar_sketch
vs grammar used. I'll fix the degree type. NB: I have not seen Abdulaeva
2001, do you happen to have a pdf?

>
>    - Shamilov, Saidamin and Paskushova, Elza 2005 is not a LONG GRAMMAR,
>    this is a book on verbal conjugation only
>
> Computerized assignment.

>
>    - Kazenin, K. I. 2013 is not a LONG GRAMMAR, this is a book on syntax
>    only
>    - Maria Polinsky 2015 is not a LONG GRAMMAR, this is a book on syntax
>    only
>
> Indeed, I'll downgrade them for next version of Glottolog.


>
>    - Uslar, Petr K. 1979 is a long grammar written in the 19th c.
>    (published in 1979), there are much more recent sources on Tabasaran,
>    including "long grammars"
>
> Yes, and I believe those are in Glottolog already, or at least in the
repos.

all the best, H

**Comment by timur-maisak** [comment]
Thank you for clarifications! Here's [Abdulaeva 2001](https://disk.yandex.ru/i/YGIJrsjXVevE-Q).

**Comment by d97hah** [comment]
Thanks! H

Pada Sen, 27 Nov 2023 pukul 20.15 Timur Maisak ***@***.***>
menulis:
