### ISSUE TITLE
add code for Wui?

### ISSUE THREAD

**Issue by quail4sale** [glottolog/glottolog#1044]
I am requesting a code for the Wui language on behalf of a linguist in the process of adding Wui documentation to the CoRSAL archive. Here is the what the depositor has shared so far with references to relevant literature:

Wui is spoken by under 1000 people in a single village (~150 households) on the Patsho Range in eastern Noklak District, Nagaland, India. Speakers are considered members of the Khiamniungan tribe, and commonly speak Patsho Khiamniungan and Nagamese as well. Marrison (1967) claimed it was a dialect of Yimkhiung (yimc1240/ ISO 639-3 yim). However, they found Wui was not intelligible to Yimkhiung speakers during a recent field trip. Coupe (2023) describes Wui's sound system and includes a preliminary dataset. He proposes a Central Naga classification.

References: 
- Coupe, Alexander R. (2023). Preliminary Report on Wui: An Undocumented Language of Eastern Nagaland. 56th International Conference on Sino-Tibetan Languages and Linguistics, 10-12 October 2023. Chulalongkorn University, Bangkok.
- Coupe, Alexander R. (2023). "Swadesh 100 list comparisons – Wui v. Aoic & Patsho Khiamniungan". Supplementary material in Preliminary Report on Wui: An Undocumented Language of Eastern Nagaland. 56th International Conference on Sino-Tibetan Languages and Linguistics, 10-12 October 2023. Chulalongkorn University, Bangkok.
- Marrison, Geoffrey Edward. 1967. The Classification of the Naga languages of North-East India. Vol. I (Texts) and Vol. II (Appendices). Unpublished PhD dissertation, SOAS, University of London.

**Comment by d97hah** [comment]
It's already there see

https://github.com/glottolog/glottolog/blob/3746b397ba4454fd7f62901d020b581004f6c6dc/languoids/tree/sino1245/kuki1245/anga1312/aoic1235/wuii1234/md.ini

Pada Sel, 28 Nov 2023 pukul 00.14 quail4sale ***@***.***>
menulis:

**Comment by quail4sale** [comment]
Great, thanks!
