### ISSUE TITLE
New Uru-Chipaya variety Ts'imu

### ISSUE THREAD

**Issue by FredericBlum** [glottolog/glottolog#1048]
Following Cerron-Palomino (2016), I propose to add a new variety to the Uru-Chipaya family (uruc1242): Ts'imu. The now extinct language was spoken at the west coast of the Lake Titicaca, at the coast of Puno. The language has some important properties that distinguish it from the other two, Bolivian varieties, and would likely play an important role in a reconstruction of Proto-Uru-Chipaya.

Coordinates: -15.813, -69.994

Reference: El Uro de la bahía de Puno. Por Rodolfo Cerrón-Palomino (con la colaboración de Jaime Barrientos Quispe y Sergio Cangahuala Castro). Lima: IRA-PUCP, 2016, 238 pp

Alternative Name: Chimu

**Comment by d97hah** [comment]
Sure, added in this new PR

https://github.com/glottolog/glottolog/pull/1049

Pada Sel, 30 Jan 2024 pukul 10.31 Frederic Blum ***@***.***>
menulis:

**Comment by FredericBlum** [comment]
Cool, thanks
