### ISSUE TITLE
[Inconsistency] Cross-data inconsistency between Glottolog, ISO and Phoible

### ISSUE THREAD

**Issue by Lavmint** [glottolog/glottolog#1050]
Good afternoon, I have problems with a few languages

Glottolog ISO codes inconsistency:
1. `dit` -> dif (Dieri / Dirari)
2. `kxl` -> kru (Kurukh / Nepali Kurux)
3. `krm` -> bmf (Bom-Kim / Krim)

Phoible glottocode inconsistency:
1. Same ISO `drl` for `band1337` and `darl1243`
2. Same ISO `khk` for `dark1243` and `halh1238`

In glottolog's [glottolog_languoid.csv.zip](https://cdstar.eva.mpg.de//bitstreams/EAEA0-B701-6328-C3E3-0/glottolog_languoid.csv.zip) and [languages_and_dialects_geo.csv](https://cdstar.eva.mpg.de//bitstreams/EAEA0-B701-6328-C3E3-0/languages_and_dialects_geo.csv):

```
halh1238,Halh Mongolian,khk,language,Eurasia,48.32397,106.28874
dira1238,Dirari,dit,dialect,Australia,-28.7992,138.078
nepa1253,Nepali Kurux,kxl,dialect,Eurasia,26.72057,86.00255
krim1238,Krim,krm,dialect,Africa,7.24116,-11.8393
darl1243,Paakantyi,drl,language,Australia,-32.7021,142.695
```

Phoible project (https://github.com/phoible/dev)
```
191,"halh1238","khk","Khalkha"
2256,"dark1243","khk","Darkhat"
2876,"darl1243","drl","Southern Paakintyi"
2875,"band1337","drl","Bandjigali"
2750,"dira1238","dif","Thirarri"
868,"nepa1253","kru","Dhangar"
1307,"krim1238","bmf","Krim"
```

ISO 639-3 (https://iso639-3.sil.org/code_tables/download_tables)
```
khk				I	L	Halh Mongolian	
dif				I	E	Dieri
kru	kru	kru		I	L	Kurukh
bmf				I	L	Bom-Kim	
drl				I	L	Paakantyi
```

Phoible ref https://github.com/phoible/dev/issues/371

**Comment by d97hah** [comment]
What is the problem? Afaict these cases are intended behaviour, though I
can't speak for Phoible. all the best, H

Pada Sab, 3 Feb 2024 pukul 07.14 Aleksei Averkin ***@***.***>
menulis:
