### ISSUE TITLE
Mru location

### ISSUE THREAD

**Issue by gldrk** [glottolog/glottolog#1056]
It appears to be completely wrong.  Mru is reportedly spoken in the extreme southeast of Bangladesh, inside the panhandle, right next to its closest relative Anu-Hkongso in Myanmar: see [this map](https://www.researchgate.net/profile/Tania-Rahman/publication/232940772/figure/fig1/AS:382166384037888@1468126974254/Languages-of-Bangladesh-Source-wwwethnologuecom.png) from Ethnologue.

**Comment by d97hah** [comment]
Indeed, thanks, I'll fix that for next version. all the best, H

Pada Rab, 21 Feb 2024 pukul 14.05 gldrk ***@***.***> menulis:
