### ISSUE TITLE
Dialect ~ language

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#1057]
Do I recall correctly that @d97hah tends to use a cut-off at 71-80% basic vocab overlap to determine, for glottolog purposes, if something is a dialect of something or its own language?

If so, cold it please be added here: https://glottolog.org/glottolog/glottologinformation

Thank you!

**Comment by d97hah** [comment]
You are probably misremembering, but discussions on how lexicostatistical
percentages correlates with intelligibility can be found in, e.g.

Simons, Gary F. (1979) Language Variation and Limits to Communication
(Working Papers for the Language Variation and Limits to Communication
Project 3). [Ithaca]: Cornell University and Summer Institute of
Linguistics.

Korjakov, Yurij B. (2017) Problema "Jazyk ili dialekt" i popytka
leksikostaticeskogo podxoda.  Voprosy Jazykoznaniya 2017(6). 79-101.


Pada Sab, 24 Feb 2024 pukul 18.00 Hedvig Skirgård ***@***.***>
menulis:

**Comment by HedvigS** [comment]
Right, yes of course. I was just thinking of Glottolog specific decisions.
