### ISSUE TITLE
Dispose of Malayo-Sumbawan

### ISSUE THREAD

**Issue by gldrk** [glottolog/glottolog#1060]
The evidence presented in [Adelaar’s 2005 paper](https://www.jstor.org/stable/3623345) is weak.  The only interesting pieces are *q > h, *əC- > *əNC- and a dual reflex of *-ay (if not a retention), all of which are shared by Javanese and overtly lacking in some of the included branches (they can only be assumed as intermediate stages by _presupposing_ a Common Malayo-Sumbawan).  The proposal was subject to detailed criticism by [Blust (2010)](https://www.jstor.org/stable/40783586) and doesn’t figure in most recent classifications such as [Blust (2013)](https://openresearch-repository.anu.edu.au/handle/1885/10191) and [Smith (2017)](https://www.jstor.org/stable/26408513).  A conservative classification would have Sundanese, Madurese and BSS as primary branches of Malayo-Polynesian.

I sadly have no access to [Adelaar (2023)](https://minerva-access.unimelb.edu.au/items/510659f1-7ba1-4fd3-80e5-59fa5555354d/full), which should reflect the most up-to-date assessment.

**Comment by d97hah** [comment]
Yes, you are right, I'll update for next edition. I don't have access to
Adelaar 2023 (2024?) either but will read when out. all the best, H

Pada Jum, 1 Mar 2024 pukul 16.55 gldrk ***@***.***> menulis:

**Comment by xrotwang** [comment]
Addressed by #1061
