### ISSUE TITLE
Padayodi, Cecile Mamalinani 2010 - fix language

### ISSUE THREAD

**Issue by dmgerasimov** [glottolog/glottolog#1068]
[Padayodi 2010](https://glottolog.org/resource/reference/id/55731) is currently listed in the bibliography for [Mullu Kurumba](https://glottolog.org/resource/languoid/id/mull1244) (kpb/mull1244, Dravidian).
It is actually a dissertation on [Kabiyé](https://glottolog.org/resource/languoid/id/kabi1261) (kbp/kabi1261, Gur<Atlantic-Congo).

**Comment by d97hah** [comment]
Thanks I've fixed that (which was a typo) for next version. all the best, H

Pada Jum, 15 Mar 2024 pukul 18.42 dmgerasimov ***@***.***>
menulis:

**Comment by dmgerasimov** [comment]
Great, thank you! All the best, D.

**Comment by xrotwang** [comment]
To be corrected in Glottolog 5.1
