### ISSUE TITLE
Alorese language

### ISSUE THREAD

**Issue by JoeMustafa73** [glottolog/glottolog#1069]
Please complete the dialect chain in Alorese. These are some of the dialects based on differences in vocabularies and lexicons.

Alor Besar
Alor Kecil
Bana
Baranusa
Beaong Onong
Dulolong
Helandohi
Kabir
Kalabahi
Marisa
Munaseli
Pandai
Pulau Buaya
Pulau Ternate
Wailawar

**Comment by d97hah** [comment]
Where do you get this list/information from?

Pada Sab, 30 Mar 2024 pukul 15.40 JoeMustafa73 ***@***.***>
menulis:

**Comment by JoeMustafa73** [comment]
https://vici.marianklamer.org/uploads/1/2/4/7/124768088/moro_kaiping_et_al_detecting_papuan_loanwords_in_alorese.pdf

**Comment by JoeMustafa73** [comment]
or maybe based on geographical location and proximity of dialects the classification could be like this.

-Alorese
--West Alor
---Alor Besar
---Alor Kecil
---Dulolong
---Kalabahi
---Pulau Buaya
---Pulau Ternate
--East–North Pantar
---Bana
---Helandohi
---Kabir
---Munaseli
---Pandai
---Wailawar
--West Pantar–Marisa
---West Pantar
----Baranusa
----Beaong Onong
--Marisa

**Comment by d97hah** [comment]
Glottolog doesn't aim to be complete with respect to dialects and
certainly not with respect to localities. If there is a reasonable
dialect understanding or if the current inventory is obviously flawed
we can fix it. But you make a lot of seemingly random dialect addition
issues from lists of names you have seen in the title of a book or
somewhere on the internet. In this case the list you have is just a
list of sample localities. It's true that there is some lexical
variation at all these localities but if there is a dialect
understanding to it, its chapter 5.8 of Sulistyono 2022 which does not
mathc your geographic groups. I don't want to put in the time to
do an exegesis if all you suggestions and I will ignore them in the
future unless accompanied by reasoning that is well grounded in the
literature. all the best, H

Pada Sab, 30 Mar 2024 pukul 17.22 JoeMustafa73 ***@***.***>
menulis:
