### ISSUE TITLE
Bekasi Sundanese

### ISSUE THREAD

**Issue by JoeMustafa73** [glottolog/glottolog#1070]
Add the Bekasi Sundanese dialect on the Northern Coast Sundanese.

• Tawangsih, M.R.M. (1987). Bahasa-Bahasa di Bekasi. Jakarta: Yayasan Panca Mitra. [OCLC](https://id.m.wikipedia.org/wiki/OCLC) [65053140](https://www.worldcat.org/oclc/65053140).
• Sudjana, A.S.H.; Marzuki, A.; Abas, A.; Jayawiguna, R. (1983). [Struktur Bahasa Sunda Pesisir Utara Jawa Barat](https://repositori.kemdikbud.go.id/3618/). Jakarta: Pusat Pembinaan dan Pengembangan Bahasa. [OCLC](https://id.m.wikipedia.org/wiki/OCLC) [14379200](https://www.worldcat.org/oclc/14379200).

**Comment by d97hah** [comment]
North Coast Sundanese [nort3412]


Pada Sab, 30 Mar 2024 pukul 15.49 JoeMustafa73 ***@***.***>
menulis:

**Comment by JoeMustafa73** [comment]
Yes, that is a classification in North Coast Sundanese, parallel to Karawang Sunda.
