### ISSUE TITLE
Makasae and Makalero languages

### ISSUE THREAD

**Issue by andrewlkline** [glottolog/glottolog#1072]
The Glottlog page on the "[Makasae-Makalero Language](https://glottolog.org/resource/languoid/id/maka1316)" should be split into Makasae and Makalero as individual languages, not dialects of one language. They have seperate ISO 639 codes (Makasae: mkz and Makalero: mjb, and the literature justifies Makalero as it's own language (see Schapper 2017 and Huber 2011).

Huber, Juliette. 2011. A grammar of Makalero: a Papuan language of East Timor. Leiden University Doctoral Thesis. https://scholarlypublications.universiteitleiden.nl/handle/1887/17684.
Schapper, Antoinette. 2017. Makalero and Makasae. In _The Papuan Languages of Timor, Alor and Pantar: Volume 2_. Vol. 2. pg. 267-352. 3 vols. De Gruyter Mouton. https://doi.org/10.1515/9781614519027.

**Comment by d97hah** [comment]
Unfortunately the literature etc does not justify them as separate
languages in the sense of unintelligibility, and that's why they are
counted as the same language in Glottolog. all the best, H

Pada Jum, 26 Apr 2024 pukul 02.23 andrewlkline ***@***.***>
menulis:

**Comment by andrewlkline** [comment]
“Due to the high number of cognates, mutual intelligibility between Makalero and Makasae is possible to a certain degree, although it is highly dependent on a speaker’s familiarity with the other language. Makalero speakers tend to have less trouble understanding Makasae than vice versa, a fact that can be explained through (i) the lower degree of morphological complexity of Makasae and (ii) the fact that Makasae is more widespread, so that most Makalero speakers have a higher degree of exposure to Makasae than vice versa.” (Schapper, 2017, p. 269)
