### ISSUE TITLE
Error in locations of Trans-Himalaya languages

### ISSUE THREAD

**Issue by monsoonforest** [glottolog/glottolog#1080]
Hello

The correct geographical location of the point for Sarli Bangru is here :27.9515088,93.1608014 where the village Sarli is located and where Bangru is a spoken as a language.

Also here are accurate geographical coordinates for the follow languages, based on my research in Arunachal over many years. Hope it can be of use!

▼[Puroikic (2)](https://glottolog.org/resource/languoid/id/puro1234)

    ▼[Eastern Puroik](https://glottolog.org/resource/languoid/id/sulu1241)
        ▼[Chayangtajoic](https://glottolog.org/resource/languoid/id/chay1250)
            [Chayangtajo](https://glottolog.org/resource/languoid/id/bugu1245) : 27.6802977,93.1302774
            [Lasumpatte](https://glottolog.org/resource/languoid/id/lasu1234) : 26.9527787,92.965784
        [Kurung Kumey](https://glottolog.org/resource/languoid/id/kuru1311)  : 27.9041107,93.3393983
        [Sario Saria](https://glottolog.org/resource/languoid/id/sari1249) : 27.7729778,92.8960868
    ▼[Western Puroik](https://glottolog.org/resource/languoid/id/west2873)
        [Bulu](https://glottolog.org/resource/languoid/id/bulu1255) : 27.4488607,92.4299111
        [Kojo Rojo](https://glottolog.org/resource/languoid/id/kojo1234) : 27.505162,92.7984331
        [Rawa (Puroik)](https://glottolog.org/resource/languoid/id/rawa1269) :27.5984412,92.9236222

I really appreciate the effort going into building this webresource and would be happy to contribute to making it so resourceful!

best wishes
Chintan

CHINTAN SHETH (he/him) | PhD Student 

The University of Sydney, Australia
Discipline of Linguistics
School of Humanities (SOH) 
Faculty of Arts and Social Sciences

**Comment by d97hah** [comment]
Thanks I've updated/added them for next version! all the best, H

Pada Rab, 5 Jun 2024 pukul 03.42 Chintan Sheth ***@***.***>
menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/pull/1081
