### ISSUE TITLE
Update glottolog of Wolayttattuwa/Wolaytta language 

### ISSUE THREAD

**Issue by Kehaa1998** [glottolog/glottolog#1090]
Currently, Wolayttattuwa is named under the term Wolaytta (Glottocode:wola1242) which is something that is considered a less accurate term for the family of the language spoken in Wolayta Ethiopia. It would be really nice to have its glottolog default name changed to Wolaytatuwa, or in the language itself "Wolayttattuwa". 
Why this change is reasonable:
The Wolayttattuwa is spoken by a large number of ethnic groups in the Southern Ethiopia specially in Wolayta Governorate and thus calling it "Wolaytta" is inaccurate as while the Wolaytans are an ethnic group for the the language, and their land also called Wolaytta. Wolayttattuwa speakers refer the language as Wolayttatto Doonaa or simply Wolayttattuwa.

**Comment by haspelmath** [comment]
I would think that we should change a Glottolog name only if there are linguists who have used the new name in some publication. Or if there is some official decision, e.g. by a government. There are many Glottolog language names that are in some way problematic, so the default should be to keep the traditional language name in Glottolog until a new one is reflected in the scientific/academic literature (or officially adopted).

**Comment by Kehaa1998** [comment]
We can refer the name of the language in the following publication https://web.archive.org/web/20120426015835/http://www.world-lang.osaka-u.ac.jp/user/liccosec/africa/AF_Wakasa_DrDissertation.pdf
[https://www.academia.edu/49078004/Research_paper_for_journal_published
These publications cite the language name is also called Wolayttattuwa. And this specific name is widely used by native speakers.
