### ISSUE TITLE
Madurese dialects in Sumbawa Island 

### ISSUE THREAD

**Issue by ReksaTresna** [glottolog/glottolog#1091]
There are 3 dialects of Madurese spoken in Sumbawa Island. Brang Bara, Bugis, and Luar dialects.

Ref:
Ryen Maerina
Distribusi dan Pemetaan Varian-Varian Bahasa Madura di Kabupaten Sumbawa
Vol. 1 No. 1 (2007): Mabasan
https://doi.org/10.62107/mab.v1i1.147

**Comment by d97hah** [comment]
Thanks!

Pada Min, 8 Sep 2024 pukul 19.37 ReksaTresna ***@***.***>
menulis:
