### ISSUE TITLE
Malay varieties in Western Kalimantan

### ISSUE THREAD

**Issue by ReksaTresna** [glottolog/glottolog#1092]
These several dialects of Malay in Western Kalimantan.

-(Western Kalimantan)
--Sanggau (ref 1, 2)
--Sambas (ref 3)
--Pontianak (ref 4)
--Ketapang

Ref 1:
Azharie Arief
Morfologi dan sintaksis bahasa Melayu Sanggau
Departemen Pendidikan dan Kebudayaan, 1989

Ref 2:
Evi novianti, Martina, Harianto, Purwiati , Khairul Fuad, Dewi Juliastuty, Yeni Yulianti 
Kamus Dialek Melayu Sanggau
Balai Bahasa Provinsi Kalimantan Barat : Pontianak, 2010
978 979 069 046 7

Ref 3:
Kamus Bahasa Melayu Sambas-Indonesia
Agus Syahrini, Dedy Ari Asfar, Hambali , Revalino, Hafiz Novialdi
Pontianak : ILBI., 2018
9786025180224

Ref 4:
Morfologi dan sintaksis bahasa Melayu Pontianak
Mustafa Kamal
Jakarta: Pusat Pembinaan dan Pengembangan Bahasa Depdikbud, 1986

**Comment by d97hah** [comment]
Thanks 1 and 4 are already in Glottolog. I'll add the other two. all the
best, H

Pada Min, 8 Sep 2024 pukul 20.19 ReksaTresna ***@***.***>
menulis:
