### ISSUE TITLE
Adding new Aztec languages

### ISSUE THREAD

**Issue by carlosgm02** [glottolog/glottolog#1093]
There are more languages in Aztec (azte1234) that have not been considered before because they are extinct or nearly extinct.

**Coahuila Nahuatl**:

Uto-Aztecan > Southern Uto-Aztecan > Corachol-Aztecan > Aztec > Western Nahuatl > Central Nahuatl > Tlaxcala-Southeastern Puebla Nahuatl

Glottolog: coah1254
Level: language
Latitude: 25.42
Longitude: -101.00
Links: https://www.wikidata.org/wiki/Q114680388
Macroareas: North America
Countries: MX
AES status: extinct
Comment: Nahuatl, Coahuila = 10 (Extinct)

Ref 1:
Jiménez Moreno, W. (2016). El náhuatl de los tlaxcaltecas de San Esteban de la 
Nueva Tlaxcala. _Tlalocan_, 3(1), 84-86. https://132.247.70.45/tlalocan/index.php/tl/article/view/354 (Wordlist)

**Jalisco Nahuatl**:

Uto-Aztecan > Southern Uto-Aztecan > Corachol-Aztecan > Aztec > Western Nahuatl > Western Periphery-North Guerrero Nahuatl > Western Periphery Nahuatl

Glottolog: jali1245
Level: language
Latitude: 19.50
Longitude: -104.33
Links: https://www.wikidata.org/wiki/Q6047324
Macroareas: North America
Countries: MX
AES status: nearly extinct
Comment: Nahuatl, Jalisco = 8b (Nearly extinct)

Ref 1:
Valiñas Coalla, Leopoldo (2011). El náhuatl en Jalisco, Colima y Michoacán. _Anales De Antropología, 16_. https://www.revistas.unam.mx/index.php/antropologia/article/view/24198 (Comparative-historical Study, Wordlist)

Ref 2:
Valiñas Coalla, Leopoldo (2013). El náhuatl actual en Jalisco. _Tlalocan_, 9. https://revistas-filologicas.unam.mx/tlalocan/index.php/tl/article/view/53/53 (Comparative-historical Study, Wordlist)

Ref 3:
Juan Guerra (1692). Arte de lengua mexicana que fué usual entre los indios del obispado de Guadalajara y de parte de los de Durango y Michoacán. http://cdigital.dgb.uanl.mx/la/1080013823/1080013823.PDF (Grammar)

Ref 4:
Cortés y Zedeño, Jerónimo (1765). Arte, vocabulario y confessionario en el idioma mexicano, como se usa en el Obispado de Guadalaxara. https://ia600407.us.archive.org/14/items/artevocabularioy00cort/artevocabularioy00cort.pdf (Grammar, Wordlist)

**Guatemala Nahuatl**:

Uto-Aztecan > Southern Uto-Aztecan > Corachol-Aztecan > Aztec > Western Nahuatl > Guatemala-Chiapas Nahuatl [guat1250]

Glottolog: guat1254
Level: language
Latitude: 14.30
Longitude: -90.79
Macroareas: North America
Countries: GT
AES status: extinct
Comment: Nahuatl, Guatemala = 10 (Extinct)

Ref 1:
Teotamachilizti iny iuliliz auh yni miquiliz Tu Temaquizticatzim Iesu Christo quenami in quim pua teotacuiloque tech teomauxti. (1600). https://commons.wikimedia.org/wiki/File:Teotamachilizti_iny_iuliliz_auh_yni_miquiliz_Tu_Temaquizticatzim_Iesu_Christo_quenami_in_quim_pua_teotacuiloque_tech_teomauxti._%3D_%C3%93_sea_(IA_teotamachiliztii00bras).pdf (Text)

Ref 2:
Arte de la lengua vulgar mexicana de Guatemala qual se habla en Ezcuintla y otros pueblos de este reyno. (1700). https://commons.wikimedia.org/wiki/File:Arte_de_la_lengua_vulgar_mexicana_de_Guatemala.pdf (Grammar)

Ref 3:
Proceedings, American Philosophical Society (vol. 24, 1887), 366-377. https://books.google.com.mx/books?id=E1cLAAAAIAAJ&pg=PA366&lpg=PA366#v=onepage&q&f=false (Overview, Comparative-historical Study, Wordlist)

Ref 4:
Sergio Romero & Margarita Cossich (2014). El Título de Santa María Ixhuatán: un texto del siglo XVII en náhuatl centroamericano. _XXVIII Simposio de Investigaciones Arqueológicas en Guatemala_. https://www.academia.edu/43024970/El_T%C3%ADtulo_de_Santa_Mar%C3%ADa_Ixhuat%C3%A1n_un_texto_del_siglo_XVII_en_n%C3%A1huatl_centroamericano (Overview, Text)

Ref 5:
Sergio Romero (2017). Los manuscritos en náhuatl centroamericano. _Anales de la Academia de Geografía e Historia de Guatemala_. https://www.academia.edu/39991196/Los_manuscritos_en_n%C3%A1huatl_centroamericano_y_la_historia_cultural_de_Guatemala (Information On A Language)

**Chiapas Nahuatl**:

Uto-Aztecan > Southern Uto-Aztecan > Corachol-Aztecan > Aztec > Western Nahuatl > Guatemala-Chiapas Nahuatl [guat1250]

Glottolog: chia1267
Level: language
Latitude: 16.89
Longitude: -92.93
Macroareas: North America
Countries: MX
AES status: extinct
Comment: Nahuatl, Chiapas = 10 (Extinct)

Ref 1:
Los mayas del sur y sus relaciones con los Nahuas meridionales. _Mesa Redonda de la Sociedad Mexicana de Antropología_. (1959). https://drive.google.com/file/d/1ur-Hl69euHESMUSjpzCkKvJcbLcCpHmB/view?usp=sharing (Overview, Wordlist)

**Honduras Nahuatl**:

Uto-Aztecan > Southern Uto-Aztecan > Corachol-Aztecan > Aztec > Eastern Nahuatl > Isthmus-Pipil Nahuatl

Glottolog: hond1245
Level: language
Latitude: 15.03
Longitude: -86.07
Macroareas: North America
Countries: HN
AES status: extinct
Comment: Nahuatl, Honduras = 10 (Extinct)

Ref 1:
Atanasio Herranz (2017). Proceso de nahuatlización y nahuatlismos de uso en Honduras. _Editorial Universitaria - Honduras_ (408 pgs). ISBN: 978-99979-56-03-3. (Information On A Language, Wordlist)

**Niquiran**:

Uto-Aztecan > Southern Uto-Aztecan > Corachol-Aztecan > Aztec > Western Nahuatl > Central Nahuatl

Glottolog: nica1253
Level: language
Latitude: 11.49
Longitude: -85.56
Macroareas: North America
Countries: NI
AES status: extinct
Comment: Niquiran = 10 (Extinct)

Ref 1:
F. D. Pimentel 1862-1865 (1862). Cuadro Descriptivo y Comparativo de la Lenguas Indígenas de México. https://www.cervantesvirtual.com/obra-visor/cuadro-descriptivo-y-comparativo-de-las-lenguas-indigenas-de-mexico-o-tratado-de-filologia-mexicana-vol-i--0/html/a663411c-080f-4008-9a70-9564c5c3384c_14.html#a038 (Overview, Wordlist)

Ref 2:
Ephraim G. Squier (1990). Observations on the Archaeology and Ethnology of Nicaragua. https://antharky.ucalgary.ca/mccafferty/sites/antharky.ucalgary.ca.mccafferty/files/Squier_1990.pdf (Overview, Wordlist)

**Caxcan**:

Uto-Aztecan > Southern Uto-Aztecan > Corachol-Aztecan > Aztec > Western Nahuatl > Western Periphery-North Guerrero Nahuatl > Western Periphery Nahuatl

Glottolog: zaca1243
Level: language
Latitude: 21.36
Longitude: -103.12
Macroareas: North America
Countries: MX
AES status: extinct
Comment: Caxcan = 10 (Extinct)

Ref 1:
Soriano López, Sergio (2012). Distribución de la toponimia indígena en la República Mexicana. _Universidad Nacional Autónoma de México_. https://ru.dgb.unam.mx/bitstream/20.500.14330/TES01000686512/3/0686512.pdf (Overview, Information On A Language)

Ref 2:
Daisy Ocampo (2019). Spiritual Geographies of Indigenous Sovereignty. Connections of Caxcan with Tlachialoyantepec and Chemehuevi with Mamapukaib. _University of California Riverside_. https://escholarship.org/content/qt0635007k/qt0635007k_noSplash_5547b9628a0d363dca062ddf465ffc16.pdf (Overview, Information On A Language)

Ref 3:
Valiñas Coalla, Leopoldo (2013). El náhuatl actual en Jalisco. _Tlalocan_, 9. https://revistas-filologicas.unam.mx/tlalocan/index.php/tl/article/view/53/53 (Some Very Small Amount Of Data)

**Comment by d97hah** [comment]
Thanks! Are you suggesting any of these as language-level entries? Most of
these references are in Glottolog already, tagged accordingly.  Thanks for
the rest.  We don't aim to be complete wrt to dialects but could add some
or all of these. Btw Where in Pimentel 1862 is there a vocabulary of
Niquiran? all the best, H

Pada Sen, 16 Sep 2024 pukul 20.08 Carlos González ***@***.***>
menulis:

**Comment by carlosgm02** [comment]
Yes, all of these are different Nahuatl languages just like Eastern Durango Nahuatl or Tabasco Nahuatl. And Pimentel 1862 has a brief vocabulary of Niquiran on pages 67-68.

**Comment by d97hah** [comment]
Do you mean different languages as in mutually unintelligible to any of the
language-level entries in Glottolog? If so, what is the evidence for this
(in each case)? E.g. for Jalisco Valiñas 1981:302 gives the opposite
impression. (Nevermind the fact that some Nahuatl language-level entries in
the existing Glottolog are intelligible, this will be adjusted in future
versions).

I can't find a Niquiran vocabulary in Pimentel 1862 Cuadro Descriptivo y
Comparativo de la Lenguas Indígenas de México on p 67-68 (in the section
about Mixtec), nor in vol 2:67-68. Can you double check?



Pada Sel, 17 Sep 2024 pukul 22.08 Carlos González ***@***.***>
menulis:

**Comment by carlosgm02** [comment]
For example, for Jalisco Nahuatl, INALI considers it its own "language" or linguistic variety. Moreover, it is true that many of them are mutually intelligible. I have never met a speaker of Eastern Huasteca Nahuatl who did not understand a speaker of Western or Central Huasteca Nahuatl. The same is true for Eastern and Western Durango Nahuatl. In fact, they consider themselves to speak the same language. I propose Coahuila, Jalisco, Guatemala, Chiapas, Honduras, Niquiran, and Caxcan as language-level entries because of those examples.

This is the Niquiran Vocabulary in Pimentel 1862:
https://www.cervantesvirtual.com/obra-visor/cuadro-descriptivo-y-comparativo-de-las-lenguas-indigenas-de-mexico-o-tratado-de-filologia-mexicana-vol-i--0/html/a663411c-080f-4008-9a70-9564c5c3384c_14.html#a038

**Comment by carlosgm02** [comment]
There are also many words that are different from those in other Nahuatl languages. In Coahuila Nahuatl, "we" is used to mean "yes," while in other varieties, "kemah" or "kena" is used. In Coahuila, "nichkararoa" is used to mean "I like," while in other varieties, "nechpaktia" or "nikamati" is used. The same goes for the other Nahuatl languages. For example, Guatemala Nahuatl has different meanings and syntax than other Western Nahuatl languages, but it is not an Eastern Nahuatl language, because it has the main common features of the Western branch. Also, they use "ayak" to say "no", not "ahmo", the plural of "siwatl" is "siwatkeh", not "siwameh", it has loanwords from the Kaqchikel language, etc.

**Comment by d97hah** [comment]
Pada Rab, 18 Sep 2024 pukul 17.23 Carlos González ***@***.***>
menulis:

> For example, for Jalisco Nahuatl, INALI considers it its own "language" or
> linguistic variety. Moreover, it is true that many of them are mutually
> intelligible. I have never met a speaker of Eastern Huasteca Nahuatl who
> did not understand a speaker of Western or Central Huasteca Nahuatl. The
> same is true for Eastern and Western Durango Nahuatl. In fact, they
> consider themselves to speak the same language. I propose Coahuila,
> Jalisco, Guatemala, Chiapas, Honduras, Niquiran, and Caxcan as
> language-level entries because of those examples.
>
Ok but just to double check, do you argue for any of the to be or have been
unintelligible to language-level Nahuatl entries already in Glottolog?



> This is the Niquiran Vocabulary in Pimentel 1862:
>
> https://www.cervantesvirtual.com/obra-visor/cuadro-descriptivo-y-comparativo-de-las-lenguas-indigenas-de-mexico-o-tratado-de-filologia-mexicana-vol-i--0/html/a663411c-080f-4008-9a70-9564c5c3384c_14.html#a038
>
OK, thanks (NB: This is not Pimentel 1862 but the 2nd edition from 1874).

all the best, H

**Comment by carlosgm02** [comment]
Yes, I propose all of these as different Nahuatl languages. Thanks!

**Comment by d97hah** [comment]
This is not what I asked. What I asked was if you would argue that any of
the suggested varieties are/were *unintelligible* to all language-level
Nahuatl entries in Glottolog and if so on what evidence? If you don't know
that's fine, i'll do my own investigations...

Pada Kam, 19 Sep 2024 pukul 03.33 Carlos González ***@***.***>
menulis:

**Comment by carlosgm02** [comment]
There are also many words that are different from those in other Nahuatl languages. In Coahuila Nahuatl, "we" is used to mean "yes," while in other varieties, "kemah" or "kena" is used. In Coahuila, "nichkararoa" is used to mean "I like," while in other varieties, "nechpaktia" or "nikamati" is used. The same goes for the other Nahuatl languages. For example, Guatemala Nahuatl has different meanings and syntax than other Western Nahuatl languages, but it is not an Eastern Nahuatl language, because it has the main common features of the Western branch. Also, they use "ayak" to say "no," not "ahmo," the plural of "siwatl" is "siwatkeh," not "siwameh," the word for "fire" is "moskot," not "tletl," it has loanwords from the Kaqchikel language, etc.

All these Nahuatl languages, in addition to being very far from each other, were different because they were isolated for centuries, they evolved independently like Tabasco Nahuatl and the variants of the Isthmus or Pipil, for example. Many of them have not been studied properly because they have become extinct, but this is clearly the same situation as with living languages. If they were still alive, they would be considered different Nahuatl languages ​​today. As a Nahuatl speaker, I have been studying the differences myself and reading about these languages, comparing them to others as I read about them.
