### ISSUE TITLE
Gallo-Italian languages spoken in Sicily are not Western

### ISSUE THREAD

**Issue by cristianolongoodhl** [glottolog/glottolog#1094]
Hi glottologgers, I hope this is the right means to discuss my issues in adding some Gallo-Italian languages spoken in Sicily, described in https://www.mdpi.com/2226-471X/8/3/163.  Currently, in the languoid tree some Gallo-Italian languages are listed in the subtree labeled as [Gallo-Italian](https://glottolog.org/resource/languoid/id/gall1279). But, in turn, Gallo-Italian is categorized as a children of [Western Romance](https://glottolog.org/resource/languoid/id/west2813) , whereas Gallo-Italian varieties of Sicily are obviously _Southern_. 

Thus, should it be appropriate to create a new Gallo-Italian node under [Southern Romance](https://glottolog.org/resource/languoid/id/sout3158) which just replicate the existing one, and then put here the Gallo-Italian varieties spoken in Sicily

**Comment by cristianolongoodhl** [comment]
I suppose that the same issue affects [Sassarese Sardinian](https://glottolog.org/resource/languoid/id/sass1235)

**Comment by d97hah** [comment]
What do you mean? If they are Gallo-Italian they belong to the subgroup
Western Romance even if they travelled to a greographically southern
location. all the best, H

Pada Min, 22 Sep 2024 pukul 16.15 cristianolongoodhl <
***@***.***> menulis:

**Comment by cristianolongoodhl** [comment]
Great, thanks
