### ISSUE TITLE
rupi1234 should be under kokb1239

### ISSUE THREAD

**Issue by patkaiist** [glottolog/glottolog#1100]
Rupini `rupi1234` should be listed as a Kokborok `kokb1239` variety. They are tribally classified as Halams (rang1267), a sort of ethnological label relating to old tribal politics and relationship to a particluar ruler, but not something with any consistent linguistic correlation.  This is discussed in:

>  Rupini, Upendra. 1998. _Rupini Samajer Ruprekha._ Tribal Research & Cultural Institute. Tripura

(unfortuantely only in Bangla)

Basically a number of Kokborok-speaking subgroups ascribed to the Halam political order and are today considered by other Kokborok speakers (e.g. Debbarma, the dominant sociocultural group) to be Halams, not Kokboroks, but lingusitically there is no question that their language varieties are nearly identical.

Also discussed in 
> van Dam, KP & Rupini, M (2022) "The position of Old Rupini: Analysing the linguistic evidence for a substratum reflecting Palaungic origins". 12th International Conference of North East Indian Linguistics Society (NEILS12). Guwahati, India

Corresponding slides for this are temporarily available here: https://github.com/patkaiist/teaching/blob/main/NEILS%20-%20Old%20Rupini-1.pdf (Spoiler: No evidence found for a non-Kokborok stratum). 

HH: I **think** I've sent you some slides previously that show the 99%+ posterior probability between Debbarma and Rupini previously. Will send again or for the first time if needed.

**Comment by d97hah** [comment]
Thanks, I've moved it to Kokborok for next version:

https://github.com/glottolog/glottolog/pull/1101

I might be that you already sent slides. I may have missed it either
deliberately (dialect inventory of Glottolog is not actively maintained) or
indeliberately.

all the best, H

Pada Rab, 9 Okt 2024 pukul 19.03 KP van Dam 柯禕藍 ***@***.***>
menulis:
