### ISSUE TITLE
Document policy on Glottocodes

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#243]
We should have our policy on Glottocode assignment and maintenance documented somewhere (also in the web app).

1. Language level Glottocodes are always valid - i.e. the way to mark obsolence for these is moving the languoids to the *Bookkeeping* pseudo family.
2. Sub-group level Glottocodes may be become obsolete and will then be removed from the current version. The codes will never be recycled, though, and we keep track of the last Glottolog version a code was valid (e.g. [Nilo-Saharan](http://glottolog.org/resource/languoid/id/nilo1235) will resolve to HTTP 301).
3. Dialect level Glottocodes are somewhat experimental at the moment; they behave like sub-group level codes, but maybe should not?
4. Some Glottocodes that have been valid for Glottolog <2.0 are completey [410 Gone](http://glottolog.org/resource/languoid/id/nilo1234).

Due to the way releases are imported into the web app (i.e. the webapp doesn't distinguish bugfix releases but always serves the latest minor release (`3.3`, **not** `3.3.2`)), Glottocodes must not be dropped in bugfixes.

Another grey area is codes denoting languoids which switch level, e.g. when a Language is determined to be a sub-group.

So, I guess, the only two hard rules are:

1. Glottocodes are never recycled - i.e. once assigned, they won't be re-assigned to something else (with the caveat that what they are assigned to may change slightly).
2. For each Glottocode we know the latest version of Glottolog it was valid for.

The nice thing is that we have an HTTP API for this:
- **HTTP 200**: valid Glottocode for current version
- **HTTP 301**: valid Glottocode for an older version (redirects to a URL including the version number)
- **HTTP 404**: invalid Glottocode (code has not been assigned yet)
- **HTTP 410**: valid Glottocode for a Glottolog version <2.0

**Comment by xrotwang** [comment]
@bambooforest triggered by your question, I opened this issue, which will hopefully turn into more official documentation soon.

**Comment by d97hah** [comment]
yes this is it. I think re (3) that, yes, dialects thrown out should be
treated like classifications thrown out (http 301 with links to any
assiocated languoids in current version).  Good initiative to make this all
explicit. all the best, H

Pada tanggal Sel, 7 Agt 2018 pukul 08.30 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Will be addressed by forthcoming paper.

**Comment by xrotwang** [comment]
See http://www.semantic-web-journal.net/content/glottocodes-identifiers-linking-families-languages-and-dialects-comprehensive-reference
