### ISSUE TITLE
provide geojson shapes for macroareas

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#272]
To allow simple lookup-by-coordinate, we should provide geocoordinates for the macroareas as computed via the algorithm described in 

> FIXME: add citation

**Comment by xrotwang** [comment]
@d97hah do you have any shapefiles or similar at hand for macroareas?

**Comment by d97hah** [comment]
I have point sets (at 1/2 a degree resolution) and/or the point contours of
the shapes (at 1/2 a degree resolution) but it was not straightforward to
make Polygons (with the shapely library) from the latter. What do we need
this for again? Maybe the point sets will do?!

Pada tanggal Rab, 20 Nov 2019 pukul 11.50 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
I think it would just be nice to overlay macroareas on maps. But, then, I
see that the major boundaries are clear enough, and the difficult cases
will remain difficult...

d97hah <notifications@github.com> schrieb am Do., 21. Nov. 2019, 04:11:

**Comment by d97hah** [comment]
Ok here's two sets of geojson files + a .ppm
1. One derived from point clouds of the ppm
2. One derived from the Voronoi regions of language coordinates
3. The ppm deriving ultimately from SRTM as described in the paper cited re
macro areas on Glottolog

Pada tanggal Kam, 21 Nov 2019 pukul 15.07 Robert Forkel <
notifications@github.com> menulis:
