### ISSUE TITLE
recording bcp47 code

### ISSUE THREAD

**Issue by eroux** [glottolog/glottolog#309]
I'm not sure if this issue should be on this repo or the glottolog3 repo, but I think it would be useful to record the bcp47 tag to use for a language. I tried to summarize my understanding of that in the intro of [this doc](https://github.com/buda-base/owl-schema/blob/master/lang-tags.md), basically it's the tag that appears in the [IANA registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), sometimes a two letters code, sometimes a 3 letters code. Most of the time it's the 2 letters code if it exists, but I'm pretty sure there are exceptions. The lexvo ontology doesn't have this information, I don't think there is any plan for an RDF version of the IANA registry.

**Comment by xrotwang** [comment]
Yes, this is the right repos for this issue; and yes, I think it would make sense. I faintly remember we discussed doing this before - but it seemed non-trivial, in particular if we wanted to add this info also for dialects. The problem I see is the maintenance. There's basically a trivial part: We can map Glottocode to ISO 639-3 code, and ISO 639-3 to ISO 639-2; but whenever this fails, there doesn't seem to be an algorithmic solution.

So if we wanted to add this info, we'd need someone willing to maintain this info for a big enough set of languages and varieties to add value over the simple ISO mapping.

**Comment by eroux** [comment]
Hmm I see what you mean. I think one approach would be to only record valid tags, which means tags that appear in the IANA registry ([section 2.2.9](https://tools.ietf.org/html/bcp47#section-2.2.9) explicitly requires it). This would mean just adding the tags that appear in the registry, which are in limited number and changing at a very slow pace. Then you can use the algorithmic part to get the well-formed tag if possible (meaning ISO639-2 or ISO639-3 if absent), that would be recorded in another property. For dialects that are not recorded in ISO639, maybe this property doesn't need to appear? I think doing just that is feasible and quite useful... wdyt?

**Comment by xrotwang** [comment]
Ok, limiting to what's in IANA would make for a tractable, transparent scope and still provide useful comprehensiveness. So yes, let's explore this option. I probably won't find the time to do this until mid March, though.

**Comment by eroux** [comment]
ok perfect!

**Comment by xrotwang** [comment]
Ok, mid June now, but I'm on the "identifier and links to other resources" topic again. So, @eroux do you know of any interesting resources which could be linked from Glottolog once we have IANA identifiers?

**Comment by xrotwang** [comment]
@eroux  The [IETF language tag](https://www.wikidata.org/wiki/Property:P305) in wikidata seems to be what you want - and given that it can be searched by glottocode in wikidata (e.g. [Cimbrian](https://www.wikidata.org/wiki/Q37053) has one), this might be sufficient for your purposes. Can we close this issue?

**Comment by eroux** [comment]
ok yes
