### ISSUE TITLE
Wikidata vs. DBPedia links

### ISSUE THREAD

**Issue by eroux** [glottolog/glottolog#313]
I'm wondering if there's a policy for links to DBPedia vs. Wikidata? It seems to me that Wikidata is gaining quite a lot of traction. When looking at the ttl export for Tibetan, it has a [link to DBPedia](http://dbpedia.org/resource/ISO_639:bod) but not to the [Wikidata entity](http://www.wikidata.org/entity/Q34271), I'm wondering if there's a policy to only use DBPedia or if both could be used? Or if links should migrate from DBPedia to Wikidata?

I also cannot see the Wikidata link in the [ini file](https://github.com/clld/glottolog/blob/master/languoids/tree/sino1245/bodi1256/bodi1257/oldm1245/tibe1276/late1253/cent2346/tibe1272/md.ini), is it computed based on the ISO639-3 code?

**Comment by xrotwang** [comment]
Yes, all links to wikipedia (and thus to dbpedia) are created based on the ISO 639-3 code, and only when a release is imported in the web app and several downloads are created.

I agree that Wikidata seems to gain traction. But do think it would be useful to include the link to Wikidata in clld/glottolog - considering that the Wikidata object already has the link to Glottolog? Wouldn't this mean **two** places where this info is curated - with the potential to get out of synch?

**Comment by xrotwang** [comment]
So I guess, the question is how to divide responsibilities between Glottolog and Wikidata. From my POV, I'd consider Glottolog the "academic" language catalog, while Wikidata would integrate Glottolog with the "rest of the world", e.g. wikipedia. In this view, the IANA language tags should rather go into Wikidata than in Glottolog.

**Comment by eroux** [comment]
Well, that makes sense yes... an idea that comes to mind is to synchronize the Wikidata entities automatically based on the ISO639-3 code. That would require to call either the Wikidata API or a SPARQL endpoint but I don't think that would be too complex (creating a .csv file of a SPARQL result for instance)... It means maintenance, scripting, etc. though.

**Comment by xrotwang** [comment]
It could be simple. The `pyglottolog` package is built for automated maintenance of the data in this repository after all. So we could just - before each release - "vendor in" the wikidata links. If we do this, it should be based on the Glottocodes which are already in Wikidata, though, at least if these are harvested from wikipedia pages. The Glottolog links on Wikipedia are fairly well maintained (mostly by [Kwamikagami](https://en.wikipedia.org/wiki/User:Kwamikagami)).

**Comment by eroux** [comment]
That sounds perfect yes

**Comment by xrotwang** [comment]
Somewhat optimistically I assigned this for release 3.4. @eroux would you be able to look into how to retrieve the Glottocode to Wikidata mapping from Wikidata?

**Comment by eroux** [comment]
The SPARQL query

```sparql
SELECT ?item ?glottocode WHERE { ?item wdt:P1394 ?glottocode. }
```

returns satisfying results on https://query.wikidata.org so

```
curl -H "Accept: text/csv" -X POST https://query.wikidata.org/sparql -d 'query=select %3Fitem %3Fglottocode where { %3Fitem wdt%3AP1394 %3Fglottocode. }'
```

looks like a reasonable first approximation...

**Comment by eroux** [comment]
(note that an alternative would be to fetch the ISO639-3 codes of Wikidata items through a similar query)

**Comment by xrotwang** [comment]
Thanks!

Elie Roux <notifications@github.com> schrieb am Do., 21. Feb. 2019, 17:59:

**Comment by xrotwang** [comment]
we'll try to push out changes related to Ethnologue 22 in a 3.4 release ASAP, so I rescheduled this to 4.0.

**Comment by xrotwang** [comment]
Wikidata links are now in the languoid's ini files (see https://github.com/glottolog/glottolog/commit/c42109cb2c61a5f9d422b3384959b2f8a6abec70) - will be in https://glottolog.org after the next release.

**Comment by xrotwang** [comment]
@eroux thanks for the SPARQL query! I've incorporated it in [pyglottolog](https://github.com/glottolog/pyglottolog/blob/master/src/pyglottolog/links/wikidata.py) so we can regerate the links peridodically.

**Comment by eroux** [comment]
excellent, thanks!
