### ISSUE TITLE
Computer-assigned reference error [iris1253]

### ISSUE THREAD

**Issue by SAuderset** [glottolog/glottolog#352]
Many of the refs for Irish are not on Irish, list and correct glottocodes provided below:

**Refs on Singlish/Singapore English: has no glottocode, so maybe one should be created**
Wee, Lionel. 2010. Metadiscursive convergence in the Singlish debate. Language and Communication 31. 75-85. 

Gupta, Anthea Fraser. 2006. Singlish on the Web. In Hashim, Azirah and Hassan, Norizah (eds.), Varieties of English in Southeast Asia and beyond, 19-37. Kuala Lumpur: University of Malaya Press.

Gil, David. 1998. Patterns of Polyfunctionality in Singlish noun phrases: A questionna. Papers from the Fifth Annual Meeting of the Southeast Asian Lingu. 147-182. Tempe, Arizona: Arizona State University, Program for Southeast Asian Studies.

Gil, David. 1994. 'Everything Also Must Grab: A Unified Semantic Analysis of Singlish 'Also'. In F. Plank (ed.), Agreement Gender Number Genitive, Eurotyp Working Papers, Series 7, Number 23, 133-145. Berlin: The European Science Foundation, EUROTYP Programme.

Platt, John T. 1975. The Singapore English speech continuum and its basilect "Singlish" as a "creoloid". Anthropological Linguistics 17. 363-374.

**Ref on Thai: thai1261**
Horsley, H. C. M. and Thanat Gojaseni. 1964. A tutor for reading Thai. Bangkok: Siva Phorn. ii, 35pp.

**Refs on Irish English: iris1255**
Hickey, Raymond. 2002. A Source Book for Irish English. (Library and Information Sources in Linguistics, Amsterdam studies in the theory and history of linguistic science : Series 5, Library and information sources in linguistics.) Amsterdam/Philadelphia: John Benjamins Publishing Company. 553pp.

Filppula, Markku. 1999. The grammar of Irish English: language in Hibernian style. (Routledge Studies in Germanic Linguistics, 5.) London: Routledge. xvi+334pp.

Dolan, Terence Patrick. 1999. A dictionary of Hiberno-English: the Irish use of English. Dublin: Gill & Macmillan. xxix+311pp.

**Ref on Irish Sign Language: iris1235**
LeMaster, Barbara. 1997. Sex differences in Irish Sign Language. Berlin. 67-85pp.

**Comment by d97hah** [comment]
Thanks Sandra I've fixed those for next version! all the best, H

Pada tanggal Min, 19 Mei 2019 pukul 20.39 Sandra <notifications@github.com>
menulis:

**Comment by SAuderset** [comment]
cool, thanks! all the best :-)
