### ISSUE TITLE
"diemen" \neq "Inland Yuin"

### ISSUE THREAD

**Issue by chirila** [glottolog/glottolog#359]
https://glottolog.org/resource/reference/id/300241
Rossel, Elizabeth Paul Edouard de. 1808. Vocabulaire de la langue d'une des peuplades de la terre de Van Diemen. In Voyage de D'Entrecasteaux envoyé à la recherche de La Pérouse, 552-556. Imprimerie Impériale.
Van Diemen's Land is Tasmania.

**Comment by d97hah** [comment]
Thx fixed for next version

Pada tanggal Sab, 1 Jun 2019 pukul 15.12 Claire Bowern <
notifications@github.com> menulis:
