### ISSUE TITLE
James et al Yan-nhaŋu 

### ISSUE THREAD

**Issue by chirila** [glottolog/glottolog#360]
classified as wordlist, should be dictionary.
https://glottolog.org/resource/reference/id/311579

**Comment by d97hah** [comment]
Looks short, how many entries is it?

Pada tanggal Sab, 1 Jun 2019 pukul 19.51 Claire Bowern <
notifications@github.com> menulis:

**Comment by chirila** [comment]
About 1000. Longer than the Macquarie wordlists, which are marked as
dictionaries

**Comment by d97hah** [comment]
Thx I'll adjust that for next version

Pada tanggal Min, 2 Jun 2019 pukul 15.04 Claire Bowern <
notifications@github.com> menulis:

> About 1000. Longer than the Macquarie wordlists, which are marked as
> dictionaries
>
