### ISSUE TITLE
not dictionaries

### ISSUE THREAD

**Issue by chirila** [glottolog/glottolog#362]
Items with 'dictionary' in the title but works that aren't actually dictionaries (e.g. reviews of dictionaries or other work on lexicography)
https://glottolog.org/resource/reference/id/309173
https://glottolog.org/resource/reference/id/307992
https://glottolog.org/resource/reference/id/310544

**Comment by d97hah** [comment]
Thanks fixed for next ver

Pada tanggal Sab, 1 Jun 2019 pukul 20.45 Claire Bowern <
notifications@github.com> menulis:
