### ISSUE TITLE
Data ownership question

### ISSUE THREAD

**Issue by lyleaf** [glottolog/glottolog#367]
Hi hi glottolog owners!

We are trying to build a free app to make people learn endangered languages more easily. We found this dataset and tool and thought it would be useful to have it as our dictionary for translation. Would love to understand, if it's possible to use this data for the app?

Thanks!

**Comment by xrotwang** [comment]
Hi @lyleaf 
I'm not quite sure how you would use Glottolog data as a dictionary (other than maybe to translate language names - and for that purpose all relevant data in Glottolog comes from [lexvo](http://www.lexvo.org/)). But the data is available under a CC-BY license, see https://doi.org/10.5281/zenodo.596479
