### ISSUE TITLE
source.bib malformed?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#374]
When I try and read [source.bib](https://cdstar.shh.mpg.de/bitstreams/EAEA0-9478-C22F-4AAF-0/glottolog_source.bib.zip) in R with the function `bib2df()` I get the following warning messages:

```
Some BibTeX entries may have been dropped.
            The result could be malformed.
            Review the .bib file and make sure every single entry starts
            with a '@'.
```
and

`  incomplete final line found on 'source.bib'`

I don't use zotero or anything like that normally, I keep a bib file for my thesis in a "raw" bib format and read that into LaTex, so I can't test if everything works well with reading it into other bibliography software. 

For the record, `bib2df()` reads in hh.bib (random old large bib-file of Harald's) just fine so I know it works on similar files. The function reads bibtex syntax and renders a big ol' table where the columns are fields and the rows entries. It deals fine with innovative field types and missing data.

This might just be a problem with the specific combination of `bib2df()` and source.bib, and therefore not really your problem, but just in case: 

- is there any unusual formatting I should be expecting in source.bib?

I can't really easily manually inspect it ^^, tis huge

**Comment by xrotwang** [comment]
Can't confirm. [pybtex](https://pybtex.org/) - which is supposed to be a complete BibTeX replacement - reads it fine:
```python
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybtex.database import parse_file
>>> res = parse_file('source.bib', bib_format='bibtex')
>>> len(res.entries)
327712
```

This does take considerable (up to a minute, I'd say) time and memory, though - so I'd suspect that may causing `bib2df` to fail.

**Comment by xrotwang** [comment]
Reading

> The BibTeX file format is simple

on the [package's CRAN page](https://cran.r-project.org/web/packages/bib2df/vignettes/bib2df.html) and the open [issue 21](https://github.com/ropensci/bib2df/issues/21) also points to a `bib2df` problem :)

**Comment by HedvigS** [comment]
Thanks @xrotwang ^^! 

I thought I would have encountered something like that with hh.bib with bib2df() so when source.bib failed I thought there was something like that time with nerwick, but turns out it's an easy fix with bi2df then. Danke
