### ISSUE TITLE
treedb.py error

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#375]
Just tried running treedb.py again after a new clone of the repos

```
Hedvigs-MBP:scripts hedvigskirgard$ python3 -i treedb.py
{'id': 'musk1252', 'parent_id': None, 'level': 'family', 'name': 'Muskogean', 'hid': None, 'iso639_3': None, 'latitude': None, 'longitude': None, 'macroareas': [], 'countries': [], 'identifier': {'wals': 'genus/muskogean'}, 'classification': {'sub': '**hh:hv:Martin-Munro:Proto-Muskogean**', 'familyrefs': [{'bibfile': 'hh', 'bibkey': 'hv:Booker:Muskogean', 'pages': None, 'trigger': None}, {'bibfile': 'hh', 'bibkey': 'hv:Martin-Munro:Proto-Muskogean', 'pages': None, 'trigger': None}], 'subrefs': [{'bibfile': 'hh', 'bibkey': 'hv:Martin-Munro:Proto-Muskogean', 'pages': None, 'trigger': None}]}}
Traceback (most recent call last):
  File "treedb.py", line 978, in <module>
    print(next(iterdescendants(parent_level='top', child_level='language')))
StopIteration
>>> 
```

Not really sure what happened here, I haven't pushed anything or made any changes and it worked last time I pulled the repos. Was there something in the recent rewiring of languoids and families that caused treedb to be upset?

**Comment by xrotwang** [comment]
I also don't know. And I don't know `treedb` much. Do you rebuild the db before running the above command? The error I'm getting when running `python treedb.py` is different and due to the new option `links` in the `[core]` section of INI files, which `treedb` seems to choke on.

**Comment by HedvigS** [comment]
Right. 
I just run treedb like that everytime, and as far as I can tell it rebuilds everything from scratch everytime.

I'd be happy to use something else if that's preferable, anything that renders something like that is good with me ^^.

**Comment by xrotwang** [comment]
Good, try `glottolog languoids` installed with `pyglottolog`, then.

**Comment by xflr6** [comment]
Thanks. This is expected from whitelisting (which we can change), see ae8fd82648070e1762ed287a76442fac67b14178 and df61824541de60b332394dd34e0e787439384805.

**Comment by HedvigS** [comment]
Hm, what whitelisting?

**Comment by xflr6** [comment]
IIRC we did not want to add `elcat` as provider last time.

**Comment by xflr6** [comment]
Whitelisting approach to data intake: Any field that is in the data but not in the schema is rejected by default.

**Comment by HedvigS** [comment]
Alright. Well. Regardless, is treedb.py a script that is being maintained with changes like this?

I'll probably switch to pyglottolog, I just haven't had the time to trial that fully just yet.

**Comment by xflr6** [comment]
Switching to `pyglottolog`, which is the official interface sounds like a good idea. :)

**Comment by xflr6** [comment]
If nobody wants to pick up the code here (no obligation to), I will probably move it into my own repo at some point.

**Comment by HedvigS** [comment]
Yes, well I'm happy to do whatever fits best. The reason I was using treedb.py was because Robert said that was preferable to using the languoid.csv download table. Guess this is the next step on the ladder ^^.
@xflr6 have you seen [my repos for clobbering together a table that I like](https://github.com/HedvigS/Glottolog_look_up_table)?

**Comment by xflr6** [comment]
added  `core->link` title and scheme extraction (http[s] whitelisted) in  51382475e9f77e7873888cf63e377ceba381d840

**Comment by xflr6** [comment]
@HedvigS, let me have a look later :)

**Comment by xrotwang** [comment]
@xflr6 at this point, I think moving the treedb code somewhere else (we could also move it to a separate repos in the `glottolog` org) would make sense. I'm trying to cut the next release with substantial improvements and a backwards incompatible `pyglottolog` 2.x - so any additional irritations will be ... well, irritating :)

Thinking about it a bit more, I think we should move `scripts` and `cookbook` to a new repo `glottolog/cookbook`. @xflr6 ok with you? If so, I'll create, move the code and give you permissions.

**Comment by xrotwang** [comment]
@HedvigS looking at your repos, and considering that `treedb` does **not** rebuild the SQLite db when run with `python treedb.py` (is that true, @xflr6 ?), your setup seems flawed.

**Comment by xflr6** [comment]
Correct Robert. The preferred way to use it in client code is importing it as exemplified in the dostring, which also shows how to use `treed.load(rebuild=True)`:

https://github.com/glottolog/glottolog/blob/f5a758d3174164ccf8ede25f043199795004afa2/scripts/treedb.py#L10-L27

**Comment by xflr6** [comment]
So the following might do the trick for Hedvig:
```$ python -c "import treedb; treedb.load(rebuild=True); treedb.write_csv()"```

**Comment by HedvigS** [comment]
@xrotwang  I didn't know that, I was only using treedb because I was told to. Switching over to using pyglottolog when I next get the mind space to sit down, run those bits and inspect what differences that makes to my flow.

**Comment by HedvigS** [comment]
If in addition you're moving this script around and it risks being out of sync, I would prefer it not being in my workflow regardless.

**Comment by xrotwang** [comment]
@HedvigS when adopting new tools, evaluation is easier, if the effects of the tool can be isolated. Looking at the [history of your Glottolog data CSV file](https://github.com/HedvigS/Glottolog_look_up_table/commits/master/Glottolog_lookup_table_Hedvig_output/Glottolog_lookup_table_Heti_edition.tsv) it's hard to figure out, if the underlying Glottolog data between runs actually changed, because other things (like the processing code) also changed.

**Comment by HedvigS** [comment]
My intention, as is stated in [the readme](https://github.com/HedvigS/Glottolog_look_up_table) was to run reclone the Glottolog repos and run the treedb at the same time as a re-genreated my csv such that the date in the metadata file is the date of all of those runs, however because I ran intro trouble with that I've now amended [the meta data file](https://github.com/HedvigS/Glottolog_look_up_table/blob/master/Glottolog_lookup_table_Hedvig_output/Glottolog_lookup_meta.txt) to state the time that I rendered the sheet and separately the time that I was last able to run treedb on the latest Glottolog data.

**Comment by HedvigS** [comment]
The original intention was that when I change little things in the code (added a colour column for example) I would also reclone and rerun treedb. That actually worked for the first couple of pushes, but then treedb failed and I was unable to keep up that flow, hence the separate dates now.

**Comment by HedvigS** [comment]
You can also see the exact version of treedb.csv that was used because[ it's also in the reps](https://github.com/HedvigS/Glottolog_look_up_table/blob/master/treedb.csv), if the date of the latest run of treedb.py isn't enough. The MED data is static, and as is mentioned in the readme that has to be checked by me whenever you guys change where that data is found.

Naturally, this will change soon as I adopt the new workflow with pyglottolog and I will continue to keep apart dates for recloning and running pyglottolog from re-running my script.

**Comment by HedvigS** [comment]
Speaking of MED, any developments on[ including descriptive status data (however static) in the grambank languoid meta data file](https://github.com/glottobank/grambank-cldf/issues/8) that I should be adopting to?

**Comment by xrotwang** [comment]
@HedvigS if by "reclone" you mean throwing away the previous clone and actually run `git clone` again - thereby downloading more than half a gig of data - than your approach would be ok. But I suspect that you rather meant updating your clone, i.e. running `git pull` (which arguably would be the right thing to do to sync a clone with the upstream repos). In that case, you'd have to rebuilt the "treedb". This is a SQLite database which `treedb` uses to store all the info from `languoids/tree` - hence the name. Merely running the command to create CSV from this SQLite db (as seems to be recommended [here](https://github.com/HedvigS/Glottolog_look_up_table/blob/master/running_treedb_at_glottolog_repos.txt)) will **not** result in CSV which reflects the updated state of the repository clone.

**Comment by xrotwang** [comment]
@HedvigS another note on using datestamps for versioning here: Except for the static (i.e. never-changing) parts of this process, everything is under version control, i.e. in git repositories. The best way to refer to particular versions of such repositories is by [commit hash](https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History) - the 40 character hex string you see as commit identifier when running `git log`, or just the 7 first characters, as is often done by GitHub. You can get this abbreviated commit hash by running
```bash
$ git describe
v3.4-70-gabae6ac
```
The last 7 characters are the first 7 hex digits of the commit hash, i.e. `abae6ac`.

So, rather than using dates with the implicit assumption that the repos clone will have been synched to a particular upstream clone at that time (in which timezone?), you should use commit hashes of the involved repos to make things reproducible.

**Comment by HedvigS** [comment]
Thank you Robert for all of this information.

Like I said, I'll be adjusting the script to no longer rely on treedb at all, as soon as I have time. So, if you don't mind I'll just ignore anything to do with improving the workflow that includes treedb. I hope that makes sense.

I'm not using command line to to clones pushes and pulls for Git, and I haven't yet incorporated git pulls and pushes into the directly R scripts (thought there are packages for this). I like using GitHub's Desktop app, it's easier to inspect changes that way I find. So currently commit hashes would not be easy to incorporate, but I'll give it a try.

This table is mainly for my use and for others who want to get the data in this format but who either don't know where to look for it or don't know how git or pyglottolog works, but who want a more up to date version of languoid.csv with some added information. For that community, I think that dates are sufficient and intelligible.

I think that anyone who is sufficiently keen on getting exact version via commits hash would actually not need these scripts and tables at all, if I'm entirely honest.  Those users would just use pyglottolog directly I imagine.

I'm trying to keep this working as well as possible for the intended users, and for myself. I don't think I can or should fit the process to a more demanding advanced user, mainly because I don't think they'll use it. That's your crew, the ones who pyglottolog serves.

That said, I'll try. I don't know yet how complicated it'll be, mainly the simplicity will amaze me :)
