### ISSUE TITLE
ELCat Data versioning

### ISSUE THREAD

**Issue by HughP** [glottolog/glottolog#380]
Greetings,

I notice that some ELCat data is being replicated in the glottolog (see link below). This is interesting in a positive way.... However, I am failing to see how the glottolog is citing the ELCat (version/date-time) from which the data was harvested (same for other sources like `lexvo`). These other referenced resources are in fact resources which change over time too... So being able to know which version and what date something was harvested is helpful. Also what seems to be missing (or maybe someone can point me to a URL for a better understanding) is how a "fact" presented in ELCat, which has a supporting citation, is then replicated with its supporting citation in Glottolog.

Pointers and help appreciated.

https://github.com/glottolog/glottolog/blob/master/languoids/tree/abun1252/md.ini

**Comment by xrotwang** [comment]
The endangerment info does have a date, see https://github.com/glottolog/glottolog/blob/e90a2e37f4c4d70a4d3e791b0c8ab299b2aa4a9b/languoids/tree/abun1252/md.ini#L106-L110
This date is supposed to indicate when the info was harvested from the source.

In the case of ElCat we also include a link (e.g. https://github.com/glottolog/glottolog/blob/e90a2e37f4c4d70a4d3e791b0c8ab299b2aa4a9b/languoids/tree/abun1252/md.ini#L14) which should make it possible to lookup the source of ElCat's assessment.

I'm not aware of ElCat providing previous versions of their data, so our setup still does not provide full traceability - although the internet archive may help with the missing bits.

Regarding lexvo, I don't think this is a resource that "changes over time" (anymore). We also only harvested alternative names from lexvo, which are basically used as a navigational device and not really considered part of the "Glottolog data".

**Comment by HughP** [comment]
But the actual citation I.e. blust 1999. OL 1(2):3-4. Is not imported to
glottolog in anyway? Is this correct?

**Comment by d97hah** [comment]
Whatever citation ElCat uses is indeed not imported into Glottolog

Pada tanggal Rab, 3 Jul 2019 pukul 22.50 HughP <notifications@github.com>
menulis:
