### ISSUE TITLE
Bhaskararao, Peri 1980 linked to wrong language?

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#396]
[Bhaskararao, Peri 1980](https://glottolog.org/resource/reference/id/316939) is currently linked (only) to [Mudhili Gadaba](https://glottolog.org/resource/languoid/id/mudh1235). But given that [Pottangi Ollar Gadaba](https://glottolog.org/resource/languoid/id/pott1240)
- is linked to WALS' *Gadaba (Kondekor)*
- is coded in Grambank using Bhaskararao as source

it should (also) be linked to the latter?

**Comment by d97hah** [comment]
I had a look and Bharaskaro's Gadaba and the Pottangi Ollari Gadaba as per
ethnologue/glottolog refer to different groups of speakers, the only
question is whether they are close enough to be the same language. Some
sources (e.g. Burrow-Bhattacharya 1962-1963) say yes, others (e.g.
Krishnamurti 2003) say no, or some version of the cryptical "prefer to
treat as different": None of the sources say something explicit about
intelligibility, leaving SILs lexicostatistical figures the
only hard evidence. They are more consistent with two different languages
than the same language, so I think this is the better solution. They should
be subgrouped though, which they are currently not in Glottolog -- I'll fix
that.

Pada tanggal Kam, 15 Agu 2019 pukul 18.06 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Ok, regarding Bhaskararao as source in Grambank, I'll go with the "copy-and-extend-lgcode" approach then, right?
