### ISSUE TITLE
Hong Kong, not Xianggang

### ISSUE THREAD

**Issue by jacksonllee** [glottolog/glottolog#398]
The official name of Hong Kong is, well, Hong Kong. It is surprising that Glottolog refers to Hong Kong as Xianggang in the Cantonese entry at https://glottolog.org/resource/languoid/id/xian1255, which is politically inappropriate.

For a reference of Hong Kong Cantonese, please see [Cantonese: A Comprehensive Grammar](https://www.taylorfrancis.com/books/9780203835012) by Stephen Matthews and Virginia Yip.

I believe this error was made in good faith, between consistency with other related languoids and the sources that the maintainers happened to get hold of.

**Comment by xflr6** [comment]
Thanks Jackson. Without wanting to anticipate the owners too much here (there may be some requirements for such a name change),  maybe you can send a PR for this file:

https://github.com/glottolog/glottolog/blob/c45a82aebe03d8049dbbab59c0712dccdffad933/languoids/tree/sino1245/sini1245/clas1255/midd1354/yuep1234/yuec1235/yueh1236/cant1236/xian1255/md.ini#L3

IIRC, we would normally add the old name to the `[altnames] glottolog`.

**Comment by jacksonllee** [comment]
Hi Sebastian, thank you for the prompt reply (long time no see, by the way -- hope all's well with you!). I hesitated to send in a PR directly, because the Glottocode for Hong Kong Cantonese is currently "xian1255", which is clearly based on the inappropriate toponym "Xianggang". I imagine assigning a new Glottocode to an existing languoid in the database could only be done by the Glottolog administrators? If you think I should submit a PR anyway, just let me know and I'd be more than happy to send one in with the changes you've suggested. Thanks!

**Comment by xflr6** [comment]
Good to see you as well (all good). :) Yeah, I am not sure about a code change, let's wait for the others to comment.

**Comment by xrotwang** [comment]
We wouldn't want to change the code, even if it ends up being derived from
an inappropriate name. Glottocodes are supposed to be mnemonic devices in
the "best" case, but in general opaque and without meaning.

Sebastian Bank <notifications@github.com> schrieb am Fr., 23. Aug. 2019,
19:38:

**Comment by jacksonllee** [comment]
Hi Robert, thank you for the reply and explaining the code. I've submitted #400 for the place name fix.
