### ISSUE TITLE
Missing coordinates for Koreanic languoids

### ISSUE THREAD

**Issue by LuPaschen** [glottolog/glottolog#402]
Coordinates for most Koreanic varieties are missing, would be good to have them included.
-----
Jejueo: 33.37, 126.53
-----
Cheju Island: 33.37, 126.53  [should be Jeju, not Cheju. possibly a doublet, see Jejueo above]
Chollado: 35.14, 126.84 [not sure why ㅈ is transliterated as "j" in Jejueo but as "ch" in Jeollado. try to be consistent.]
Ch'ungch'ongdo: 36.63, 127.31
Hamgyongdo: 42.34, 129.84
Hwanghaedo: 38.29, 125.47 
Kyongsangdo: 35.30, 128.30
P'yong'ando: 39.44, 126.16
Seoul: 37.54, 126.98

**Comment by d97hah** [comment]
Thanks! Added the coordinates for next version (Jejueo sep lang should
already have one in the repos), removed the duplicate Cheju and adjusted
the spelling to Jollado. all the best, H

Pada tanggal Rab, 11 Sep 2019 pukul 12.58 LuPaschen <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/pull/403
