### ISSUE TITLE
Add geo coordinates for ende1235

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#411]
according to https://katelynnlindsey.weebly.com/ende-language.html
the geo coordinates of Ende (Papua New Guinea) are:

lat: -8.957786
long: 142.24079900000004

**Comment by d97hah** [comment]
Thanks, I've added them for next version! H

Pada tanggal Jum, 4 Okt 2019 pukul 18.58 Hans-Jörg Bibiko <
notifications@github.com> menulis:
