### ISSUE TITLE
Add lgcode for Kuanua [kuan1248] to Thurston 1987

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#416]
[Thurston 1987](https://glottolog.org/resource/reference/id/hh:hvw:Thurston:NBritain) has been used as source for coding [Kuanua](https://glottolog.org/resource/languoid/id/kuan1248) for Grambank. So adding `[ksd]` to this record's `lgcode` should be considered.

**Comment by d97hah** [comment]
Afaik that source has no information on Kuanua. all the best, H

Pada tanggal Sel, 8 Okt 2019 pukul 09.25 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
ok
