### ISSUE TITLE
Language classification clarification

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#421]
Hiya, 

For my thesis, since I'm using Glottolog data, I'm writing up a section comparing how Ethnologue and Glottolog classify languages. I just noticed something about lexical similarity as criterion and wanted to double check to make sure I've understood you correctly.

The official criteria for ISO 639-3 does not refer to lexical similarity but "shared literature". However, there is a mention elsewhere that " Percentages [of lexical similarity] higher than 85% usually indicate a speech variant that is likely a dialect of the language with which it is being compared." It's not said explicitly, but it would seem plausible that these scores would be based on something similar to Swadesh lists.

On the Languoids page under about at the Glottolog website, under the heading "Is the putative language assertably distinct from all other known languages?" it says that "direct comparison of language data" can provide sufficient information to answer this question.

Am I interpreting it correctly that this "language data" is basically the same as the further down "50 items or so of basic vocabulary" needed for placing a languoid in a tree structure?

**Comment by d97hah** [comment]
As said there, "50 items or so of basic vocabulary" is some kind of minimal
requirement guideline but really the more language data the better

Pada tanggal Sab, 12 Okt 2019 pukul 07.42 Hedvig Skirgård <
notifications@github.com> menulis:
