### ISSUE TITLE
Dialects with dialects

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#434]
I understand the conceptual basis, but since it's not really explained anywhere and seems a bit inconsistently applied (and causes hiccups in my scripts), is there any way you would consider not letting dialects have dialects?

**Comment by xrotwang** [comment]
While still covered only patchily, and possibly inconsistently, dialects as they are now already provide some value, namely a way to have more specific info than on language-level while still being able to lookup language-level nodes. Some users may already use this functionality to lookup languages for dialect groups. So I'd be reluctant to do away with these group nodes just for the sake of a slightly simpler data structure.

I'd say fixing the scripts is the better option here. Whether scripts consider **all** nodes below language-level dialects - or only proper **leafs** - is not something Glottolog has an opinion on (correct @d97hah ?).

**Comment by HedvigS** [comment]
I am fixing my scripts, don't worry. I just think that this is something that either should be changed or documented somewhere, since I don't think it is generally known that this is a feature of the dataset. It's easy to miss this structure since it's quite rare.

**Comment by xrotwang** [comment]
Yes, documentation of this would be good. But I don't see grave potential errors arising from missing this feature of the data: Since dialect coverage is very patchy anyway, mistaking the first-level dialect groups for dialects doesn't change much. And if software assumes there is just one level below language, it will crash - and thus reveal this wrong assumption.

**Comment by HedvigS** [comment]
Well, I'm switching my whole set up from using the newick file and pruning to the sample I need to taking the classification col from the cldf-formatted data and rebinding them into a tree instead. 

Some people work over large amounts of data and might not notice that they haven't pruned enough in the first go. Displaying this information somewhere where people who use the newick files might look would not hurt.

**Comment by xrotwang** [comment]
PRs welcome!

**Comment by HedvigS** [comment]
I don't know where in the clld app repos that information is editable, or where it should be displayed.

**Comment by d97hah** [comment]
Correct

Pada tanggal Sen, 4 Nov 2019 pukul 08.23 Robert Forkel <
notifications@github.com> menulis:
