### ISSUE TITLE
Otomanguean: Macroarea mis-assigned to all 'dialect' entries

### ISSUE THREAD

**Issue by SAuderset** [glottolog/glottolog#435]
For Otomanguean (otom1299), I noticed that all entries classified as dialects are assigned to the macroarea 'South America', while the entries classified as languages are assigned to 'North America'. 
For example, Chicahuaxtla Triqui is correctly assigned to North America, but Laguna (a dialect of it) is assigned to South America, see corresponding lines from csv:
chic1273,Chicahuaxtla Triqui,trs,language,North America,17.1628,-97.8547
lagu1250,Laguna,,dialect,South America,,

I'm not exactly sure where the cut-off is for South America according to Glottolog, but apart from Subtiaba and Mangue which are located in Nicaragua, all Otomanguean languages listed are located in Mexico and should thus be listed as North America (as far as I understand it).

**Comment by d97hah** [comment]
Thx Sandra. @Robert Forkel <forkel@shh.mpg.de>  I recognize this issue, do
I misremember if it was solved for next versioN? H

Pada tanggal Jum, 8 Nov 2019 pukul 10.25 Sandra <notifications@github.com>
menulis:

**Comment by xrotwang** [comment]
Fixed: e.g. https://github.com/glottolog/glottolog/blob/master/languoids/tree/otom1299/east2557/amuz1253/mixt1422/triq1251/chic1273/lagu1250/md.ini

@SAuderset So the fixed data will show up in the web app https://glottolog.org after the next release.

**Comment by xrotwang** [comment]
Oh wait, it should be the other way round. So no, not fixed. Sorry!

**Comment by xrotwang** [comment]
@d97hah so I should fix all these:
```
Otomanguean
  Santa Ana Ateixtlahuaca Mazatec [sant1456]
  Santa María Citendejé-Banos [sant1435]
  Quioquitani Zapotec [quio1242]
  Petlacalancingo Mixtec [petl1238]
  San Pedro Molinos [sanp1259]
  Nagrandan [nagr1240]
  Santa María Yosoyúa [sant1442]
  San San Jerónimo Mazatec [sans1275]
  Loma Grande [loma1263]
  Jalieza Zapotec [jali1244]
  Cuatzoquitengo [cuat1239]
  Tabehua [tabe1238]
  Potoichan [poto1253]
  San Martín Tilcajete Zapotec [sanm1299]
  Tezoatlán [tezo1239]
  Santa Catarina Ticuá [sant1443]
  Orisi [oris1240]
  Teotitlán del Valle Zapotec [teot1238]
  Jinotepe-Nindirí [nucl1669]
  San Antonio Eloxochitlán Mazatec [sana1287]
  San Martín Peras [sanm1291]
  San Mateo Zoyamazalco Popoloca [sanm1302]
  Panixtlahuaca Chatino [pani1261]
  San Mateo Peñasco Mixtec [sanm1293]
  Yaitepec Chatino [yait1239]
  San Gregorio Ozolotepec Zapotec [sang1340]
  Santa María Pápalo [sant1437]
  San Lucas Zoquiapan Mazatec [sanl1249]
  Santo Domingo Heundío Mixtec [sant1440]
  Nicoya [nico1263]
  Zoyaltitla [zoya1238]
  Platanillo [plat1255]
  Xochapa Mixtec [xoch1238]
  Nuyoo [nuyo1238]
  Santa Cruz Ocopetatillo Mazatec [sant1455]
  San Miguel Achiutla Mixtec [sanm1292]
  San Miguel Tenoxtitlán [sanm1290]
  San Miguel [sanm1304]
  San Felipe Santiago Otomí [sanf1263]
  Nuclear Cajonos Zapotec [nucl1670]
  Acatepec [acat1240]
  Todos Santos Almolonga Popoloca [todo1238]
  Santiago Tlazoyaltepec [sant1446]
  Diria [diri1255]
  Huizapula-Zapotitlán Tablas [huiz1244]
  Yalina [yali1256]
  Santa María Nativitas [sant1453]
  Yucuhiti [yucu1249]
  Yucu Ñuti [yucu1251]
  San Agustín Loxicha Zapotec [sana1285]
  Zapotitlán Tablas [zapo1435]
  Santa María Peñoles [sant1445]
  San Agustín Tlacotepec [sana1284]
  Zaachila [zaac1238]
  Santa Maria Tataltepec [sant1444]
  San Marcial Ozolotepec Zapotec [sanm1300]
  Orotiña [orot1239]
  San Mateo Tepantepec [sanm1297]
  San Francisco Huehuetlán Mazatec [sanf1265]
  Ayotzintepec [ayot1238]
  Coicoyán [coic1238]
  Tototepec [toto1307]
  San Juan Piñas [sanj1280]
  Atlacomulco-Temascalcingo [atla1270]
  Santa María Acatepec [sant1441]
  San Juan Quiahije Chatino [sanj1283]
  Santiago Matatlán Zapotec [sant1449]
  Zoogocho [zoog1239]
  Monte Verde Mixtec [mont1271]
  Candelaria Loxicha Zapotec [cand1249]
  San Miguel Chalcatongo [sanm1296]
  San Cristóbal Amoltepec Mixtec [sanc1244]
  Yaganiza-Xagacía Zapotec [yaga1261]
  San Lorenzo Cuanecuiltitla Mazatec [sanl1250]
  Yolox Chinanteco [yolo1240]
  Quierí Zapotec [quie1238]
  Plan de Guadalupe [plan1238]
  Malinaltepec [mali1286]
  Santa Catarina Yosonotu [sant1438]
  Atlamajalcingo del Monte [atla1271]
  Zilacayotitlán [zila1239]
  San Mateo [sanm1303]
  San Simón Zahuatlán [sans1274]
  Laguna [lagu1250]
  Ahuatempan Popoloca [ahua1238]
  Huejonapan [huej1238]
  Yosoñama [yoso1238]
  San Vicente Coyotepec Popoloca [sanv1243]
```

**Comment by SAuderset** [comment]
Thanks for always attending to this so fast! Yes, that looks right! The issue is with all 'dialect' entries of Otomanguean.

I've also just noticed another issue, but specifically with this entry (lagu1250):
The multitree altnames all refer to a different language, namely the Keresan variety spoken in Laguna Pueblo in New Mexico, USA.

**Comment by xrotwang** [comment]
@d97hah btw. there's quite a few more cases where dialects have different macroareas than their language - lots in Japonic (papunesia vs. eurasia), several in Austronesian. I guess it would make sense to try to find coordinates for all of these and then run the macroarea-assignment algorithm again?

**Comment by SAuderset** [comment]
I'll just chime in again: I (or rather my student assistant) collected all the coordinates for the dialect entries in Mixtec. I'm happy to share that, just let me know how (it's a csv file).

**Comment by xrotwang** [comment]
@SAuderset please send to glottolog@shh.mpg.de ! Thanks a lot!

**Comment by SAuderset** [comment]
cool cool, will do!

**Comment by xrotwang** [comment]
@SAuderset please have a look at #437 and let me know if that's ok with you.

**Comment by SAuderset** [comment]
yes, looks good to me!

**Comment by d97hah** [comment]
Indeed, though even better to set all dialects without a coordinate to the
same macro-area as its parent and then reassess if/when they get a
coordinate

Pada tanggal Jum, 8 Nov 2019 pukul 17.19 Robert Forkel <
notifications@github.com> menulis:
