### ISSUE TITLE
Description of descriptive score

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#446]
Can the [glottologinformation page](https://glottolog.org/glottolog/glottologinformation) please have a section on how doctypes correspond to descriptive status scores, à la this table?

![aes_table](https://user-images.githubusercontent.com/5327845/70096102-62f0f080-167a-11ea-989d-02d014afaf03.png)

**Comment by HedvigS** [comment]
it's otherwise not obvious to users of the cldf-format that "phonology/text" includes "dictionary".

**Comment by xrotwang** [comment]
We have this info here https://glottolog.org/langdoc/status and this info is also included in the `CodeTable` of the CLDF dataset: https://github.com/glottolog/glottolog-cldf/blob/master/cldf/codes.csv#L26 - which should be the obvious place to look for it in the CLDF context.

**Comment by HedvigS** [comment]
Right, okay. Well, I didn't but that's my mistake.

Could the languoid about page include a line somewhere about the descriptive status regardless? Like

"The Agglomerated Endangerment Status (AES) is derived from the databases of  The Catalogue of Endangered Languages (ELCat) ,  UNESCO Atlas of the World's Languages in Danger and  Ethnologue. For more information see GlottoScope and GlottoVis, which also contain information on descriptive status."

**Comment by xrotwang** [comment]
See https://glottolog.org/glottolog/glottologinformation#agglomeratedendangermentstatusaes
