### ISSUE TITLE
The branching structure of South Wakashan

### ISSUE THREAD

**Issue by martsen79** [glottolog/glottolog#447]
I have a question and possible suggestion for the branching structure of South Wakashan. It is currently branched as South Wakashan > [Nootkan > Ditidaht & Nuuchahnulth] & Makah. It is no doubt that Makah and Nuuchahnulth are on separate sub-branches of the tree, but I am curious why Ditidaht is branched with Nuuchahnulth in "Nootkan" which I am guessing is based on Campbell 1997, since I don't see it in Stonham 2006. Why was this decision made? I will below give my case for undoing this grouping, although this should be read as a suggestion and not necessarily expert knowledge.

I am not an expert on Ditidaht (Adam Werle would be the person to talk to for that), but I think it is somewhat of an open question how Ditidaht relates to Makah and Nuuchahnulth. Ditidaht shares certain things in common with Nuuchahnulth possibly due to its location - the change from /q'/ --> /ʡʕ/ (or whatever the odd sound is, epiglottal with pharyngeal offglide according to Esling et al 2005), the southern Nuuchahnulth dialect's ablaut rules, and lots of lexical material. However it shares in common with Makah the collapse of hypothesized /m|b/ and /n|d/ morphemes (Kinkade 1985) into /b, d/ while Nuuchahnulth went with /m, n/, the retention of phonemic /l/ which Nuuchahnulth lost, and quite a bit of inflectional morphology, including retaining Wakashan subject-object portmanteau enclitics, which Nuuchahnulth has simplified to simple subject enclitics (only retaining object agreement in the imperative). In sum, while Ditidaht has certainly been in intense linguistic and cultural contact with their Barkley sound (southernmost Nuuchahnulth dialect) neighbors, it's not clear from this that they share a more direct common ancestor with Nuuchahnulth, rather than a more direct ancestor with Makah.

In Fortescue's comparative dictionary (2007) he brings up the hypothesis that Ditidaht may represent the fusion of a former Makah group returning north and then mixing with Nuuchahnulth speakers. This seems quite plausible to me and it may even be the case that Ditidaht is underlyingly more closely related to Makah but has adopted Nuuchahnulth words and participated in Nuuchahnulth sound changes after it returned to Vancouver Island. Or perhaps something else. Until more evidence comes to light and is published, I wonder if it may be more conservative to not add branching structure to South Wakashan.

**Comment by d97hah** [comment]
Thanks for this notification, I now re-read the items and neither Stonham
nor Campbell actually subgroup D with N so that subgrouping should not have
been there in the first place. (I think the fact that I put it there has
something to do with the fact that Dididaht used to be subsumed under N in
earlier ISO 639-3 division.). Anyway it's wrong so I will adjust it
accordingly for the version. Thanks a lot! H

Pada tanggal Kam, 5 Des 2019 pukul 17.51 martsen79 <notifications@github.com>
menulis:
