### ISSUE TITLE
Reference for Milanese [mila1243] or new dialect

### ISSUE THREAD

**Issue by tresoldi** [glottolog/glottolog#454]
I am preparing a Lombard/Milanese wordlist for IECor. I interviewed people in Carugate (province of Milan) and used a dictionary published 20 years ago.

The language dialect is undoubtedly Lombard/Milanese, specifically of the north-eastern group which follows the Villoresi channel ([here](http://proverbimilanesi.blogspot.com/p/i-dialetti.html) a good enough description). There is probably no reason to add a new sub-variety, even though there are indeed some differences with neighbouring towns (Carugate somewhat sits on a triple border involving this Villoresi, the Brianzolo, and the Monzese groups), but I suppose Glottolog would benefit from this reference nonetheless.

An short official webpage describing the dictionary can be found [here](https://www.comune.carugate.mi.it/c015051/zf/index.php/servizi-aggiuntivi/index/index/idtesto/3)

```bibtex
@book{Galbiati1999,
  address = {Carugate},
  author = {Galbiati, Mario},
  pages = {254},
  publisher = {Comune di Carugate},
  year = {1999},
  macro_area = {Eurasia},
  lgcode = {Milanese = Lombard [lmo]},
  hhtype = {dictionary},
}
```

**Comment by d97hah** [comment]
Grazie I've added the ref for next version! H

Pada tanggal Jum, 20 Des 2019 pukul 19.03 Tiago Tresoldi <
notifications@github.com> menulis:
