### ISSUE TITLE
Old/variant spurious glottocode associations 

### ISSUE THREAD

**Issue by d97hah** [glottolog/glottolog#459]
This (and other) references are shown as associated with Sumayela Ndebele [sout2808],
presumably because it used to be, or is currently in one of the source bibliographies, associated with iso 639-3 [nbl]. But the association should follow hh.bib if there is an association there (in the lgcode field) and merge all source biblio associations in other cases.  The lgcode-field in the .bib entry works like this and actually the associations should be a mirror image of the lgcode-field in the bib.
https://glottolog.org/resource/reference/id/121226

**Comment by xrotwang** [comment]
Hm, yes. Seems to be a bug somewhere.

**Comment by xrotwang** [comment]
@d97hah Hm, ok. So what you'd want is that whenever a set of references is merged into a single one (upon making a release of Glottolog), the `lgcode` fields of non-`hh` references should be ignored if the `hh` reference has one, correct?

I could probably put together a PR which does that, i.e. 
- merges bibtex records on `glottolog_ref_id`
- deletes the `lgcode` of the non-`hh` records in case the `hh` record has one.

This might give us a chance to see whether there's anything we might lose.

**Comment by d97hah** [comment]
Pada tanggal Sel, 17 Mar 2020 pukul 15.39 Robert Forkel <
notifications@github.com> menulis:

> @d97hah <https://github.com/d97hah> Hm, ok. So what you'd want is that
> whenever a set of references is merged into a single one (upon making a
> release of Glottolog), the lgcode fields of non-hh references should be
> ignored if the hh reference has one, correct?
>
Yes, so the tag should be a function of the lgcode field of the merged
entry (which has the above property)



> I could probably put together a PR which does that, i.e.
>
>    - merges bibtex records on glottolog_ref_id
>    - deletes the lgcode of the non-hh records in case the hh record has
>    one.
>
> This might give us a chance to see whether there's anything we might lose.
>
Sure

**Comment by xrotwang** [comment]
`anla` seems to have quite a few more detailed (?) or at least different `lgcode` fields that might be worth keeping - or integrating into `hh.bib`?

**Comment by d97hah** [comment]
Example?

Pada tanggal Sel, 17 Mar 2020 pukul 16.12 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
`eballiso2009` is responsible for about half of the 3,000 cases where the set of codes listed in the `lgcode` field differs from the set of the corresponding `hh` record. Since for `eballiso2009` the `lgcode` fields have been computed automatically anyway, we could probably just delete those fields.

For other sources such as `ozbib` the `lgcode` fields seem to also contain useful information on alternative names. So maybe we just move this info to a new field, `lgcode_from_source` or similar?

**Comment by xrotwang** [comment]
An example for `anla`:
```
hh: {'haid1248'}
anla: , Northwest Alaska Inupiatun [esk] OR Central Siberian Yupik [ess] OR North Alaskan Inupiatun [esi], Haida [hai], Tlingit [tli]
```
(Sorry, I didn't log the actual reference key.)

**Comment by d97hah** [comment]
Ok, this and other examples from anla are not enough to make an exception
to the general policy

Pada tanggal Sel, 17 Mar 2020 pukul 16.29 Robert Forkel <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
The simplest solution seems to be just to compute the lgcode field merge
and then set the associations from there, without worrying about the
originals in these cases. There is some value in the originals, but not
much, so if you want to bother with moves like lgcode_from_source, please
do, but IMHO not worth the extra work. all the best, H

Pada tanggal Sel, 17 Mar 2020 pukul 16.28 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Ok, I'll just remove the dissenting `lgcode` fields, then (they'll stay in the history anyway :) )

**Comment by d97hah** [comment]
Yes they are still there in the source bib:s

Pada tanggal Sel, 17 Mar 2020 pukul 16.48 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Oh, I was just going to purge them from the source bib:s. This will also prevent conflicting associations to show up in the languoid `md.ini` files.

**Comment by d97hah** [comment]
Don't purge them from the source bib:s, that would be a less general
solution

Pada tanggal Sel, 17 Mar 2020 pukul 17.09 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
So here's what I just did: The [`glottolog-admin updatesources` command](https://github.com/glottolog/pyglottolog/blob/master/src/pyglottolog/admin_commands/updatesources.py) now prefers `hh.bib`, i.e. it first parses all associations from `hh.bib`, and stores corresponding `glottolog_ref_id`. Then it parses all other bib:s and skips entries with a known `glottolog_ref_id`.
A nice side effect of this is that it also cuts down on some noise (i.e. effective duplicates) in languoid's `md.ini[sources]`.

PR will come shortly.
