### ISSUE TITLE
Katabaga shouldn't really be "Unattested"

### ISSUE THREAD

**Issue by liuxinyu970226** [glottolog/glottolog#463]
Regarding https://glottolog.org/resource/languoid/id/kata1268

As far as I've got from SIL International, the 2019-024 change request has rejected: https://iso639-3.sil.org/sites/iso639-3/files/change_requests/2019/CR_Comments_2019-024.pdf

And descriptions about Katabaga do really exist in the Philippines' sites: http://www.ethnicgroupsphilippines.com/people/languages-in-the-philippines/katabaga/ and http://www.languagelinks.org/onlinepapers/fil_lang.html

Maybe we shouldn't change anything soon without somewhat confirmations from Louward Allen Zubiri of University of the Philippines (mentioned in that pdf file), but how can't these be the evidences that Katabaga is really a language, and not a "spurious thing"?

**Comment by d97hah** [comment]
Ok so there are four words, so I'll move it from unattested to
unclassifiable. all the best, H

Pada tanggal Sab, 1 Feb 2020 pukul 07.57 Liu Xin Yu <
notifications@github.com> menulis:
