### ISSUE TITLE
1432 languages are missing in tree_glottolog_newick.txt

### ISSUE THREAD

**Issue by agricolamz** [glottolog/glottolog#465]
Hello,

In the file [`tree_glottolog_newick.txt`](https://cdstar.shh.mpg.de/bitstreams/EAEA0-3DAE-E27B-4692-0/tree_glottolog_newick.txt) in the glottolog version 4.1 1432 languages/dialects are missing. Including all Sign Languages.

Here is a [list](https://gist.github.com/agricolamz/b29ffaf0d4e36b9fb6c851d88c732a38).

**Comment by xrotwang** [comment]
I think that's all languages from [pseudo families](https://glottolog.org/meta/glossary#sec-pseudofamilies). Since pseudo-families do not actually represent genealogical classifications, they are left out of the "glottolog classification tree".

**Comment by xrotwang** [comment]
Hm, need to investigate why dialects like https://glottolog.org/resource/languoid/id/nort3332 are missing, though.

**Comment by xrotwang** [comment]
Btw. the code generating this file is here https://github.com/clld/glottolog3/blob/master/glottolog3/commands/newick.py

**Comment by xrotwang** [comment]
Regarding the dialects, I'm not sure your analysis is correct. AFAIKT `nort3332` **is present** in https://cdstar.shh.mpg.de/bitstreams/EAEA0-3DAE-E27B-4692-0/tree_glottolog_newick.txt

**Comment by agricolamz** [comment]
Dear, Robert, yes, I figured out the problem for cases like `nort3332`, thank you. All others are mixed languages, artificial languages, sign languages etc. It is a pity though that tree structure for Sign Languages is not in the newick.txt.

**Comment by xrotwang** [comment]
@d97hah would you consider the tree of Sign Languages in Glottolog a genealogical classification like for the other language families? If so, I'd agree with @agricolamz that we should include it in the newick export.

**Comment by d97hah** [comment]
Yes include sign

Pada tanggal Sen, 2 Mar 2020 pukul 08.43 Robert Forkel <
notifications@github.com> menulis:
