### ISSUE TITLE
Abkhazian

### ISSUE THREAD

**Issue by agricolamz** [glottolog/glottolog#466]
Is it possible to rename [Abkhazian](https://glottolog.org/resource/languoid/id/abkh1244) to Abkhaz?

All English references use this form.

**Comment by haspelmath** [comment]
Yes, this language should be called „Abkhaz“.

**Comment by d97hah** [comment]
I'll adjust it so for next version

Pada tanggal Min, 9 Feb 2020 pukul 18.07 Martin Haspelmath <
notifications@github.com> menulis:
