### ISSUE TITLE
Kho-Bwa khob1235 names of languages and subgroups

### ISSUE THREAD

**Issue by monpasang** [glottolog/glottolog#468]
1) The name 'Kamengic' is a misnomer. It refers to ‘Kameng’, which is the name by which a certain river is known in the Nyishi language in a very short stretch along its lower course. Because of a late colonial and early post-independence lack of knowledge and understanding and the historical dominance of the Nyishi people, the name Kameng stuck to two districts, East and West Kameng, based on the geographical location vis-à-vis this river. 

The river system is actually very long, and the river is known by various names along the various subsidiary rivers and streams, which reflects the many distinct languages belonging to many distinct sub-groups that are spoken in West Kameng district. These include Brokpa (Central Bodish); Dirang Tshangla (comments on doubtful Bodish affiliation in (Bodt 2012: 188-189) and Grollmann (2013, 2019)); Khispi (Lishpa) and Duhumbi (Chugpa) (see comments below); Sartang (see comments below); Miji (Dhammai, Sajolang: Hrusish, comments on Hrusish affiliation in Bodt and Lieberherr 2015); Bugun (see comments below); Hruso-Aka (comments on Hrusish affiliation in Bodt and Lieberherr 2015); and Koro-Aka before flowing to the Brahmaputran plains of Assam, where it is known as Bhareli. To name this very specific sub-group as 'Kamengic' is, therefore, unwarranted (see the comment in Lieberherr and Bodt 2017: 27). None of these groups calls this river the Kameng, in fact, none of the groups in West Kameng calls this river the Kameng. Nyishi, on the other hand, the language that gave rise to the name of the river, is not spoken in West Kameng district. 

The name 'Kamengic' has been coined by Blench and Post (2011) in an unpublished paper and subsequently published in Blench and Post (2014) in want of a new name for a sub-group, a sub-group in itself based on weak or non-existent evidence. 

My suggestion is to delete this name completely, before it gains even more prominence through quoting in the derived literature. See the comment on classification for the most parsimonious solution.

2) Like ‘Kamengic’, the name 'Meyic' is another misnomer. The name of the Rupa people for themselves is [meː] or [tʰõŋdʒi], for the Shergaon people [møː] or [sɛ̃ndʒi] (Bodt 2014a). Neither of them refers to themselves or each other as [mej], this is simply because Blench erroneously transcribed [meː] as mey (Blench 2012). None of the Sartang groups, nor the Chugpa and Lishpa, consider Mey or Mö or Me a valid name for themselves, their languages or their tribe. In fact, they have never heard of it. Proliferation of this name in the literature is unwarranted. Western Kho-Bwa, which is introduced in my 2014 paper (Bodt 2014b:154) and we also used in our 2017 paper (Lieberherr and Bodt 2017:33) and is the name of the reconstructed proto-language (Bodt 2019 and Bodt accepted), is a neutral term, describing the location of these linguistic varieties compared to the other languages of Kho-Bwa, Puroik and Bugun. 

Similarly, the name Mey to refer to the Sherdukpen is incorrect. Just as with Meyic, this was introduced based on a wrong transcription and interpretation and should be avoided. 

Instead, the names Sherdukpen and Sartang are generally acknowledged by the speakers themselves as being correct and are used in all official and non-official communication. Sherdukpen has been included in the Scheduled Tribes list of Arunachal since the 1960s (Bodt 2014a, Bodt 2014b) and Sartang replaced earlier pejorative But or Boot Monpa in the early 2000s and has been practically acknowledged as a Scheduled Tribe but not officially included in the list (Bodt 2014a, Bodt 2014b). 

Jacquesson (2015:1) is correct in stating that the autonym is pronounced as Shertukpen and not Sherdukpen, however, this is too little of a difference to warrant re-labelling of the language.

When combining the names, Sartang should be mentioned first because of alphabetical reasons. Mentioning Sherdukpen first gives the Sartang the idea that they are somehow inferior to the Sherdukpen, something that the Sherdukpen like to profess themselves. Although such superiority is true in contemporary numerical and socio-economic terms, there is anecdotal and now growing linguistic evidence that the Sartang-Sherdukpen dialect continuum has its homeland in the area around Khoina in the East and spread from there (Bodt 2014b:163, 166). 

3) On the other hand, Lishpa and Chugpa or Lish Monpa and Chug Monpa are exonyms that have pejorative connotations (Bodt 2014a, Bodt 2014b, Bodt 2020). The people call themselves Khispi and Duhumbi, respectively, and they also call each other that (Bodt 2014a, Bodt 2014b, Bodt 2020). Now, because Lish and Chug (exonyms for the village / valley they inhabit) are already established names I do not wish to push for a name change, although I do consciously call my grammar ‘Grammar of Duhumbi (Chugpa)’ and not ‘Grammar of Chugpa (Duhumbi)’ (Bodt 2020). Inclusion of the autonyms somewhere in Glottolog will, however, do credit to the people who speak these languages, instead of just considering them as languages per se.

**Comment by monpasang** [comment]
Comments on classification:

There is no linguistic evidence that suggests in any way that Bugun is closer to Chug-Lish, Sartang and Sherdukpen than to Puroik, as is suggested by the inclusion of Bugun in Kamengic, see Lieberherr and Bodt (2017) for a graphic illustration of the independent position of Bugun versus both Sartang-Sherdukpen-Lish-Chug and Puroik. Rather than a reference to the unpublished Blench and Post (2011) paper mentioned with 'Comments on subclassification'.

The updated classification I propose is as follows:

Kho-Bwa (7)
	Bugun (6)
		Bichom
		Dikhyang
		Kaspi
		Namphri
		Singchung
		Wangho
	Western Kho-Bwa (4)
		Chug-Lish (2)
			Chug (Duhumbi)
			Lish (Khispi)
		Sartang-Sherdukpen (2)
			Sartang (4)
				Jerigaon
				Khoitam
				Khoina
				Rahung
			Sherdukpen (2)
				Rupa
				Shergaon
	Puroikic (2) (no comments)

**Comment by monpasang** [comment]
Comments on geolocations:

See additional file / Excel worksheet.
[Geolocations Kho-Bwa.xlsx](https://github.com/glottolog/glottolog/files/4197230/Geolocations.Kho-Bwa.xlsx)

**Comment by monpasang** [comment]
References attached
[References.pdf](https://github.com/glottolog/glottolog/files/4197233/References.pdf)

**Comment by d97hah** [comment]
Thanks a lot!
1. I've updated the classification accordingly (I agree with all you say
and shame on me for not reading the 2017 more carefully when it came out).
I've also adjusted the remaining names.
2. I've added the coordinates
3. I've added the remaining references. Do you have a pdf of Grollman
(2013) or does this remain unavailable?

Pada tanggal Kam, 13 Feb 2020 pukul 09.38 monpasang <
notifications@github.com> menulis:

**Comment by monpasang** [comment]
Thank you for updating. I would have to ask Grollman whether a pdf of her thesis can be shared, since she may be planning a publication. Will inform you as soon as I receive word.

**Comment by xrotwang** [comment]
Addressed in #472
