### ISSUE TITLE
Many irrelevant references in bibliography for Bathari (bath1244)

### ISSUE THREAD

**Issue by IanMaddieson** [glottolog/glottolog#474]
All of the last 10 entries in the bibliography for Bathari (bath1244) have nothing to do with this South Semitic language, as also the 5th entry in this bibliography by Luce having to do with Burmese poetry!

**Comment by xrotwang** [comment]
Ah yes, the triggers for automatic assignment of references are a bit overly broad, see https://github.com/glottolog/glottolog/blob/bcfde1abec929ef7aa1e685fa5d21d767f1a6083/languoids/tree/afro1255/semi1276/west2786/mode1252/hoby1243/west2859/bath1244/md.ini#L64-L68

But you can sort by the first "ca" (for computerized assignment) column, to shuffle all these to the end:

![Bathari](https://user-images.githubusercontent.com/870184/74711351-14d49d80-5224-11ea-9951-4f9805f0da41.png)

**Comment by d97hah** [comment]
I've fixed the triggers so the mistagged refs should go away in the next
update

Pada tanggal Sel, 18 Feb 2020 pukul 07.58 Robert Forkel <
notifications@github.com> menulis:
