### ISSUE TITLE
Request for dialect split - Hopi (hopi1249)

### ISSUE THREAD

**Issue by rhiannon-schembri** [glottolog/glottolog#475]
Hopi currently has no dialects listed, but several are recognised in descriptions of the language. For coding in Grambank, the Second Mesa and Third Mesa dialects require different coding for at least one feature, based on descriptions in Kalectaca & Langacker (1978) and Jeanne (1978). I would like to request to have these two dialects listed with separate glottocodes so that I can submit two different sheets for them in Grambank.

Thanks :)

**Comment by d97hah** [comment]
I've added first, second and third mesa for next version

languoids/tree/utoa1244/nort2953/hopi1249/firs1235/md.ini
languoids/tree/utoa1244/nort2953/hopi1249/seco1242/md.ini
languoids/tree/utoa1244/nort2953/hopi1249/thir1234/md.ini

Pada tanggal Sel, 18 Feb 2020 pukul 11.02 Rhiannon Schembri <
notifications@github.com> menulis:
