### ISSUE TITLE
bula1258 missing dialect?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#478]
Did there used to be a dialect of hanu1241/hnn called "Bulalakawnon" with the glottocode "bula1258"?
Some poking in ABVD and MultiTree seem to indicate so.

**Comment by d97hah** [comment]
If you say so, afaik Bulalakawnon is Inonhan [loc]

Pada tanggal Sab, 29 Feb 2020 pukul 23.17 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
Interesting! The plot thickens.

As far as I can tell right now bula1258 doesn't exist as a glottocode. [MultiTree has that as name for a dialect of [hnn]](http://multitree.org/codes/hnn-bul.html).

I can see a bula1256 which is a dialect of inon1237, [and that the language with the next ID number in ABVD is attributed to [loc]](https://abvd.shh.mpg.de/austronesian/language.php?id=1548). 

I think there's just been a mixup of one number in ABVD, I'll let them know.

**Comment by HedvigS** [comment]
Super quick follow up I swear. Sometimes I search a name on Glottolog and a language comes up, but the name I searched isn't listed as the main name or among the alternative names of that language.

For example, if I search "Bulalakawnon" I get to ["inon1237"](https://glottolog.org/resource/languoid/id/inon1237). But, "Bulalakawnon" isn't listed among the alternative names as far as I can tell (it is listed in a reference title though). Are only some alternative names shown on the website?

**Comment by xrotwang** [comment]
If you want to knwo whether a glottocode was once assigned to a languoid, you look up its canonical URL, i.e. you append it to https://glottolog.org/resource/languoid/id/ : https://glottolog.org/resource/languoid/id/bula1258
So `bula1258` last showed up in Glottolog 3.3 - and was presumably inherited from MultiTree. Subsequently, I gues, it fell victim to a dialect cleanup.

**Comment by HedvigS** [comment]
@xrotwang Huh.. interesting. Is there a list kept somewhere of discarded codes, i.e. besides the bookkeeping family?

**Comment by xrotwang** [comment]
[glottocodes.json](https://github.com/glottolog/glottolog/blob/master/languoids/glottocodes.json) stores the biggest numeric suffix ever used with a given alphanumeric prefix, where the numeric suffix started out at 1234. So
```python
"aala": 1237,
```
means, `aala1234` up to `aala1237` have been assigned to languoids at some point. Anything that doesn't resolve to HTTP 200 anymore, is no longer a valid glottocode:
```
forkel@shh.mpg.de@dlt4803010l:~$ curl -I https://glottolog.org/resource/languoid/id/aala1234
HTTP/1.1 410 Gone
...

forkel@shh.mpg.de@dlt4803010l:~$ curl -I https://glottolog.org/resource/languoid/id/aala1235
HTTP/1.1 410 Gone
...

forkel@shh.mpg.de@dlt4803010l:~$ curl -I https://glottolog.org/resource/languoid/id/aala1236
HTTP/1.1 410 Gone
...

forkel@shh.mpg.de@dlt4803010l:~$ curl -I https://glottolog.org/resource/languoid/id/aala1237
HTTP/1.1 200 OK
...
```
Most of these invalid glottocodeshave been invalidated with the Glottolog 1.0 to 2.0 transition, where all alternative trees, inerited from multitree, have been dropped from the Glottolog database. These will resolve to HTTP 410 - as above - while any Glottocode invalidated after 2.0 will resolve to the latest version it was still valid, e.g.:
```
forkel@shh.mpg.de@dlt4803010l:~$ curl -I https://glottolog.org/resource/languoid/id/bula1258
HTTP/1.1 301 Moved Permanently
Location: https://glottolog.org/files/glottolog-3.3/bula1258.html
```

**Comment by HedvigS** [comment]
@xrotwang ah, very interesting! And what is the criterion for a retired glottocode to be indexed in the bookkeeping family?

**Comment by HedvigS** [comment]
I have been asked more than once how come a common glottocode for language level glottocodes end in 1241. I'm guessing the answer to that is somewhere in this information.

**Comment by xrotwang** [comment]
The idea is that language-level glottocodes will never become invalid. Instead, they are moved to bookkeeping in case they turn out not to correspond to a language. Families and dialects may simply be removed, i.e. invalidated.

**Comment by xrotwang** [comment]
I'm not sure I understand your question about glottocodes ending in 1241. If 6 glottocodes for the same alphanumeric 4-character prefix - say `abcd` have already been dealt out, a new languoid with a name starting with `Abcd` will get glottocode `abcd1241`. This new languoid may have any level.

**Comment by HedvigS** [comment]
It just seems to be something about the distribution of nodes and languages over the numbers that people notice, and people often assume I know stuff like this so they ask me ^^

As far as I can tell, 19% of all language glottocodes end in "1238", "1239" or "1241". 18% of dialect glottocodes end in "1238", but people seem not to notice that. It's just a quirk of the assignment, language names etc but humans like patterns so they notice :). It's not important, nevermind.

Thanks for the answer about retired non-language glottocodes, very helpful :)!
