### ISSUE TITLE
tidied references? looking for med_pages etc

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#480]
The way the references are displayed on the website is different from how they are in the bibtex files (both [cldf version](https://github.com/glottolog/glottolog-cldf/blob/master/cldf/sources.bib) and [the download file](https://cdstar.shh.mpg.de/bitstreams/EAEA0-3DAE-E27B-4692-0/glottolog_source.bib.zip)). I also couldn't find what I was looking for in the N3-file and I wasn't sure where to look at Zeonodo.

This is a bit of an issue particularly when it comes to years and pages, which is interesting information to me. The tables on the website are much more tidy than the actual bibtex entires which may contain different formats and non-numeric characters.

I suspect that you have a script somewhere that deals with untidy bibtex fields in a generally good way and summarises things like year and page counts for the web front end :). Rather than wasting time writing a script that does the same thing and deals correctly with all inconsistencies in the bibex-entries, can I somehow get that script and/or a file :)?

For example, the grammar sketch "Études Parāči" is listed with multiple years and a complicated page field in the bibtex entry:

@ article{556013,
  author     = {Charles M. Kieffer},
  journal    = {Studia Iranica},
  number     = {1, 2, 1, 2, 1, 2, 1, 2, 2},
  pages      = {97-125, 249-281, 81-107, 269-277, 67-106, 245-267, 99-119, 233-249, 283-306},
  title      = {Études Parāči},
  volume     = {6, 6, 7, 7, 8, 8, 9, 9, 10},
  year       = {1977, 1977, 1978, 1978, 1979, 1979, 1980, 1980, 1981},
  besttxt    = {ptxt2\eurasia\kieffer_paraci1977-1981_o.txt},
  cfn        = {eurasia\kieffer_paraci1977-1981_o.pdf},
  fn         = {eurasia\kieffer_paraci1977-1981_o.pdf, eurasia\kieffer_paraci1977-1981.pdf},
  hhtype     = {grammar_sketch;dictionary},
  inlg       = {French [fra]},
  lgcode     = {Parachi [prc]},
  macro_area = {Eurasia},
  src        = {hh}
}

But which appears in the table with the oldest year and a neatly summarised page number:

Details | Name | Title | Any field | ca | Year | Pages | Doctype | ca | Provider | da
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Citation| Charles M. Kieffer 1977, 1977, 1978, 1978, 1979, 1979, 1980, 1980, 1981 | Études Parāči |   |   | 1977 | 223 | dictionary, grammar_sketch |   | hh |  

This is actually one of the easier examples, there are other cases of non-numeric characters in the year field, complicated ways of referring to pages etc. It's not impossible to clean up, I just don't want to reinvent the wheel, I hope that makes sense.

I'm looking for this information in order to complement the "to code"-list for grambank with the inlg of the 3-5 most extensive descriptions per language. This will make the task of assigning languages to coders a lot easier for node leaders and the coders themselves. I also would like a file with this information for a project I have with a few of the coders about terminology in linguistic description over time.

I wouldn't ask if it wasn't for the fact that it looks like it's already been done :), just point me in the right direction please :)? I feel a bit stupid like I'm missing some obvious place to look.

I can get what I want from [the csv-download link on the website](https://glottolog.org/langdoc#), but only for 2,000 entries at a time. The fields I'm looking for there are called "med_pages", "pages_int" (yes please I'd like both and I've noticed the difference) and "year_int"

**Comment by xflr6** [comment]
I think part of the code you are looking for is [here](https://github.com/glottolog/pyglottolog/blob/fe4c2a52d54cdcf0804b4f889598dbb9b8698dbd/src/pyglottolog/references/bibfiles.py#L279-L301) ([see](https://github.com/glottolog/pyglottolog/blob/fe4c2a52d54cdcf0804b4f889598dbb9b8698dbd/src/pyglottolog/references/bibfiles.py#L44-L45) [also](https://github.com/glottolog/pyglottolog/blob/fe4c2a52d54cdcf0804b4f889598dbb9b8698dbd/src/pyglottolog/references/util.py#L26-L29)).

**Comment by xrotwang** [comment]
So this is how you'd access this info:
```python
>>> from pyglottolog import Glottolog
>>> api = Glottolog('.')
>>> rec = api.bibfiles['hh.bib']['sd:Kieffer:Paraci']
>>> rec.year_int
1977
>>> rec.pages_int
223
```

**Comment by HedvigS** [comment]
@xflr6 Thanks! That does look like what I'm looking for!

Now to figure out how to run/access this in the most convenient way with the pyglottolog API.

**Comment by HedvigS** [comment]
@xrotwang Thanks! 

I'll just need to figure out how to run that in a convenient way over all the entries, or at least all the entries with grammar in hhtype. I'm not sure if my pyglottolog is up to date, I'll check that too. Installing python packages was a bit difficult last few times so I've been keeping away from it, which isn't really good.

**Comment by HedvigS** [comment]
This isn't somewhere in the cldf release, right?

**Comment by xrotwang** [comment]
no

**Comment by HedvigS** [comment]
Hi again, this is Hedvig and Ste reporting back on how this all went.

We were able to render a csv with pages_int and year_int based on monster-utf8.bib after some cajoling. We couldn't get things to work with pyglottolog API.bibfiles.iterentries without removing all other bib-files in references/bibtex and putting monster-utf8.bib there. 

Steps:
1) render monster-utf8.bib
[https://github.com/HedvigS/glottolog/blob/hedvig_monster_bib_merge_and_clean/rendering_monster.py
](https://github.com/HedvigS/glottolog/blob/hedvig_monster_bib_merge_and_clean/rendering_monster.py
)
2) move out all .bib files in references/bibtex and move in monster-utf8.bib from build

3) clean up monster-utf8.bib into neat csv using pyglottolog
[https://github.com/HedvigS/glottolog/blob/hedvig_monster_bib_merge_and_clean/cleaning_monster_bib.py](https://github.com/HedvigS/glottolog/blob/hedvig_monster_bib_merge_and_clean/cleaning_monster_bib.py)

We'd prefer to not do step (2), either by doing the "cleaning" ourselves or by telling the glottolog API to look in build instead of references/bibtex, but we didn't want to get out of sync or otherwise mess with pyglottolog. We couldn't easily figure out how to load a specific bibtex file to pyglottolog, if there is a way pray do tell.

**Comment by xflr6** [comment]
Thanks for the pointers. IIUC from the initial post above you seek to get this information for the published Glottolog version. In that case I think you want to extract it from `sources.bib` from [glottolog_source.bib.zip](https://cdstar.shh.mpg.de/bitstreams/EAEA0-18EC-5079-0173-0/glottolog_source.bib.zip) (the download file you mention). Building a new `monster.bib` with the latest version will most likely differ from information from the site as published.

Here is a rough version that should create a similar output to the one you get from your scripts (note that you only need `source.bib` for this, i.e. no need to clone the `glottolog` repo):

```python
import csv
import pathlib

from pyglottolog.references import BibFile

SOURCE = pathlib.Path('source.bib')

DEST = SOURCE.with_suffix('.csv')

ATTRS = ['year_int', 'pages_int']

FIELDS = ['title', 'hhtype', 'author',
          'inlg', 'lgcode']

bf = BibFile(SOURCE)

with DEST.open('wt', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(ATTRS + FIELDS)
    for e in bf.iterentries():
        row = [getattr(e, a) for a in ATTRS]
        row += [e.fields.get(f) for f in FIELDS]
        writer.writerow(row)
```

**Comment by HedvigS** [comment]
Thanks @xflr6 , this is very useful indeed!

To be clear, I would prefer having the latest image of the database as it is on git rather than the website release version. I don't think it makes a big difference here, but I prefer to not rely on the download files but be able to use the repos and pyglottolog to get at what I'm after.

**Comment by xflr6** [comment]
Happy to help. The snippet above can also be used to extract from a locally built `monster.bib`.

>  I would prefer having the latest image of the database as it is on git
> rather than the website release version

Caveat that creating a new `monster.bib` usually mints new `glottolog_ref_id`s and changes them from merges/splits. As they differ from the ones created when preaparing the next released version, the ids in the new file don't refer to Glottolog (you can think of a locally created `monster.bib` as an unofficial fork). Maybe that is fine for your use case (just trying to avoid confusion over different versions).

**Comment by HedvigS** [comment]
@xflr6 yes we noticed that. Was a little bit surprised at first, didn't think you'd be changing every entry in the bibtex files everytime the monster was created. It didn't disrupt our workflow though.

Next time I want to do something along these lines with pyglottolog, what is the easiest way of getting documentation on function?

**Comment by xflr6** [comment]
> didn't think you'd be changing every entry in the bibtex files everytime the monster was created.

IIRC, that should not be the case (should only affect bibentries with added/changed ref_ids).

There is some documentation in the [README.md](https://github.com/glottolog/pyglottolog/blob/master/README.md) and place for recipes in the [cookbook repo](https://github.com/glottolog/cookbook). You can in principle use Python's `help()` on functions, classes and instances (filling in the remaining docstrings might allow us to create an API-doc, maybe you want to help here?):

```python
>>> from pyglottolog.languoids import Languoid
>>> help(Languoid)
class Languoid(builtins.object)
 |  Languoid(cfg, lineage=None, id_=None, directory=None, tree=None, _api=None)
 |  
 |  Info on languoids is encoded in the ini files and in the directory hierarchy.
 |  This class provides access to all of it.
...
```

**Comment by HedvigS** [comment]
Right okay. I'll look in those places first next time.

I'm not sure who is meant to be using pyglottolog so I don't know how you want this to look.

I have to get help from a more experienced python user every time, and it usually takes us several hours to read through the code and figure out what's going on (and then later we find that it's been cleverly solved somewhere else 😅). I'm sort of okay with that though, because I don't think I'm the intended user.

**Comment by xrotwang** [comment]
`pyglottolog` is the tool the Glottolog editors use to maintain the Glottolog data repository, and access the data there-in. Other people sometimes need to access this data as well, an then are welcome (or actually encouraged) to do this via `pyglottolog`. Expectations regarding the way software should be documented vary a lot, so doing this in a generally satisfactory way is hard. But we try at least to provide places where documentation can be contributed. So whenever you think you solved a problem requiring Glottolog data (preferably one that other people may have as well), feel free to open a PR at our [cookbook](https://github.com/glottolog/cookbook). You will get free code review and we may end up with documentation users want to read.

**Comment by HedvigS** [comment]
Hmm, that might be a thing I might do. Most of the things I regularly need are now provided within the CLDF-version of Glottolog, though not all. I've been meaning to re-write[ this script ](https://github.com/HedvigS/Glottolog_look_up_table) to overall update it but also link it better to the glottolog-cldf release. I just haven't had the time yet.

I didn't know non-glottolog staff could submit things to the cookbooks. I'd probably write scripts in R though, lest I exhaust Ste's time too much with re-writing it all into python

**Comment by xrotwang** [comment]
Everyone can submit PRs to the cookbook. You may just have to do it from your personal fork if you do not have write permissions for the repos.
