### ISSUE TITLE
Incomplete title/bibliography [nucl1310] - Davidson, F. A. L. 1889

### ISSUE THREAD

**Issue by wieserd** [glottolog/glottolog#483]
"Davidson, F. A. L. 1889. Anglicized colloquial Burmese..." is not complete/correct
https://glottolog.org/resource/reference/id/44604

**Complete title:** F. A. L. Davidson, _Anglicized Colloquial Burmese_ or, _How to speak the language in three months_, London 1889.

**Comment by d97hah** [comment]
Thanks I've fixed that for next version! H

Pada tanggal Rab, 11 Mar 2020 pukul 14.16 wieserd <notifications@github.com>
menulis:
