### ISSUE TITLE
Ref 144733: wrong language

### ISSUE THREAD

**Issue by oesten** [glottolog/glottolog#485]
Reference 144733 is attributed to two languoids: noon1242 and noon1243 but these are two quite different languages.  Noon (Senegal) is noon1242 and is the right one.

**Comment by d97hah** [comment]
Thanks! @Robert Forkel <forkel@shh.mpg.de>  this is the same bug as
previously identified

Pada tanggal Sel, 17 Mar 2020 pukul 11.04 Östen Dahl <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See #459
