### ISSUE TITLE
Mismatch (?) between language labels under references and languoids

### ISSUE THREAD

**Issue by alenawitzlack** [glottolog/glottolog#487]
The language name under [this reference](https://glottolog.org/resource/reference/id/300265) say Igloolik [west2618], however, Igloolik does is not mentioned under [west2618](https://glottolog.org/resource/languoid/id/west2618).

**Comment by xrotwang** [comment]
You mean, Igloolik is not listed as alternative name, right? The entries listed under the "Languages" header on the reference details page are parsed from `lgcode` fields of BibTeX records, being merged into the reference. So in this case, it's
```
lgcode           = {Igloolik = Inuinnaqtun [ikt]},
```
in Harald's bibliography. So yes, typically the things mentioned in these entries would qualify as alternative names - but there's no guarantee or check whatsoever.

So basically, when it comes to alternative names, we distinguish between what's been used as a somewhat official name for a language, and what's useful as a search term when looking fora language. This is also the reasoning behind hiding Harald's "search terms" when listing alternative names. These terms do list "Igloolik", see https://github.com/glottolog/glottolog/blob/9e5e22ead230ebcd62e9077cf34ecba0a47882a6/languoids/tree/eski1264/eski1265/inui1246/west2618/md.ini#L72-L87

**Comment by xrotwang** [comment]
@alenawitzlack @d97hah I really don't have much of an opinion here. But if we can make it transparent that "alternative names" are nothing official, but simply a navigational device, we might want to list the `hhbib_lgcode` names as well?

**Comment by xrotwang** [comment]
Alternatively, we can keep it as is and advertise "expert access", e.g. using the tools from `pyglottolog`:
```
$ glottolog langsearch Igloolik
INFO    glottolog/glottolog at /home/forkel/venvs/glottolog/glottolog
1 matches
Western Canadian Inuktitut [west2618] language
glottolog/languoids/tree/eski1264/eski1265/inui1246/west2618/md.ini
Igloolik

1 matches
```

**Comment by alenawitzlack** [comment]
ok, it makes more sense now. I was not sure what the convention for languages listed by reference was and assumed that it should be the same label as the relevant Glottocode and some test cases seemed to support it (like Swahili/Kiswahili), but now I see that this was not the intention and the name should be close to whatever the source uses. Thanks and good to know!

**Comment by haspelmath** [comment]
I think it would indeed be useful to "list the hhbib_lgcode names as well". I think it's already pretty clear that the "alternative names" have no special status. – I'm also wondering whether we could simply always give the Glottolog name whenever we refer to the language. The label "Igloolik" in https://glottolog.org/resource/reference/id/300265 is indeed a bit confusing, and it would be confusing also if "Igloolik" were listed under "alternative names". This may be technically challenging, but I see no conceptual reason for the old hhbib_lgcode names in this field.

**Comment by xrotwang** [comment]
@haspelmath I'm a bit confused now. So you would opt for listing `hhbib_lgcode` under alternative names, but you think the particular entry "Igloolik" would be confusing?

The reason for listing "Igloolik" in the "Languages" box is that typically the label given in Harald's `lgcode` field is the label used for the language in the given source. But what is aggregated now in the `hhbib_lgcode` lists for a particular language also comprises things that might lead to more confusion, e.g. misspellings of names, etc.

**Comment by haspelmath** [comment]
Sorry, this confusion is probably my fault, because I lost track of the various parts of the database. (Misspelled names should of course not be included...) But I wonder what the value is of giving the "label used for the language in the given source". It does not seem to me that it's very systematic. (I just browsed the references given under https://glottolog.org/resource/languoid/id/swis1247, and those given under https://glottolog.org/resource/languoid/id/ayac1239; in the latter, there's seemingly random variation between "Ayacucho Quechua", "Quechua Ayacucho", and "Quchua-Ayacucho".) Maybe it gives some extra information if the source language is a non-English language which Glottolog users may not understand? (e.g. here: https://glottolog.org/resource/reference/id/55347). So maybe both should be listed somehow, i.e. the Glottolog name AND the "lgcode label"?

**Comment by d97hah** [comment]
SOmeone else raised this issue with me in person last week.
IMHO
- on the page of a certain reference, such as
https://glottolog.org/resource/reference/id/477446
to the right, the languages box should contain both the lgcode-name
and the Glottolog name, e.g., as
lgcode-name (Glottolog-name [abcd1234])

- on the page of a languoid
https://glottolog.org/resource/languoid/id/baga1275
one could rename "Alternative names" to "aliases" and
also list the aliases occurring in the lgcode field,
perhaps ranked by # references and excluding hapaxes
to make it look nicer.

all the best,
H


Pada tanggal Kam, 19 Mar 2020 pukul 11.03 Martin Haspelmath <
notifications@github.com> menulis:
