### ISSUE TITLE
Addition of timespan attribute

### ISSUE THREAD

**Issue by d97hah** [glottolog/glottolog#500]
I'd like to add an attribute timespan similar to coordinates etc for ancient languages. E.g. 500 BC-50 BC
for Camunic [xcc]. I have compiled a reasonably complete list. I can add attributes to the core in the .ini which is just two integer values e.g.

timespan_start = -500
timespan_end = -50

But then ideally pyglottolog should be able to fetch them with l.timespan_start and l.timespan_end
and I should write them to the .ini:s with l.cfg.write, so maybe this requires a little hacking on @xrotwang:s or xlr6:s part?!

**Comment by xrotwang** [comment]
What about using [ISO-8601 durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)?

**Comment by d97hah** [comment]
Ok so "-2500-01-01T00:00:00Z/-50-01-01T00:00:00Z" is legal and desired? Can
do

Pada tanggal Sel, 7 Apr 2020 pukul 20.55 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
The time part can be omitted, so `-2500-01-01/-50-01-01`.

**Comment by d97hah** [comment]
Ok!

Pada tanggal Sel, 7 Apr 2020 pukul 22.50 Robert Forkel <
notifications@github.com> menulis:

**Comment by xflr6** [comment]
IIUC [ISO_8601#Years](https://en.wikipedia.org/wiki/ISO_8601#Years) requires a minimum four digits for the year, do we want to adapt?

https://github.com/glottolog/glottolog/blob/1d4c01b2f73bb147fd656e6f105155245f32c85a/languoids/tree/indo1319/indo1320/iran1269/cent2317/cent2318/nort3177/tati1243/adha1238/md.ini#L15

**Comment by xrotwang** [comment]
Ah, yes, we do. Will implement validation in pyglottolog later today.

Sebastian Bank <notifications@github.com> schrieb am Mi., 15. Apr. 2020,
09:59:

**Comment by xflr6** [comment]
Thanks Robert. Just in case there is something prelimiary [here](https://github.com/glottolog/treedb/blob/c80a497b8962d9b6c1d0b8f2154736356be5aeb7/treedb/languoids.py#L80-L125) (`datetime` does not do BCE).

**Comment by xrotwang** [comment]
Thanks. Looks pretty comprehensive - I'll have to replace the f-strings, though :)

**Comment by xflr6** [comment]
> I'll have to replace the f-strings, though :)

Yeah. Python 3.5 ends this year, and 3.6+ provides some nice things such this. :)
