### ISSUE TITLE
Cuicatec: a few mis-assigned references

### ISSUE THREAD

**Issue by SAuderset** [glottolog/glottolog#502]
I went through the references on Cuicatec (cuic1234) and came across a few mis-assigned entries:
- Review of: Diccionario zapoteco: Zapoteco de Juarez, by Neil Nellis and Jane G. Nellis => should be assigned to sier1250
- La concepción del mundo entre los Huachipaire (Harákmbet). El kürednndári (cielo). Ponencia al simposio "Cosmología, alteridad y medio ambiente" del 48o CIA, Estocolmo/Uppsala, 4-9 de julio de 1994 => should be assigned to huac1244
- La concepción del mundo de los aborígenes de Costa Rica
- La concepción de tiempo y espacio en el mundo andino
(for the last two, I unfortunately don't know what they should be assigned to)

**Comment by d97hah** [comment]
Thanks a lot, I've fixed that for next version! H

Pada tanggal Kam, 9 Apr 2020 pukul 17.37 Sandra <notifications@github.com>
menulis:

**Comment by SAuderset** [comment]
great! thanks for the quick reply, S.
