### ISSUE TITLE
Map coordinates of Mangarrayi [mang1381]

### ISSUE THREAD

**Issue by gfkpth** [glottolog/glottolog#506]
The current coordinates for the language Mangarrayi [mang1381], now at (-14.8, 138.5), seem to have changed from glottolog 4.0 and now point to the sea. I'm not an expert on the language, but the previous coordinates from glottolog 4.0 (-14.7982, 133.803) seemed more plausible, as they actually point to dry land.

**Comment by xflr6** [comment]
Pointer for convenience:
https://github.com/glottolog/glottolog/blob/9e5e22ead230ebcd62e9077cf34ecba0a47882a6/languoids/tree/mang1423/mang1381/md.ini#L7-L8

**Comment by d97hah** [comment]
Probably a typo, should be 133.5, 14.8. I'll push fix

Pada tanggal Rab, 15 Apr 2020 pukul 13.41 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah can you do this soon - so it gets into 4.2?

**Comment by d97hah** [comment]
Yes I dig, was awaiting the response of gfhdk on the Apulian coordinate.
Now pushed (directly to master - sorry!)

Pada tanggal Rab, 15 Apr 2020 pukul 17.07 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/commit/37aa10a5ef4727cade7405af925912b6581ca48e
