### ISSUE TITLE
Propose coordinates for Aspromonte Greek [aspr1238]

### ISSUE THREAD

**Issue by gfkpth** [glottolog/glottolog#507]
I would like to suggest map coordinates for Aspromonte Greek [aspr1238], which currently shares coordinates with Apulian Greek.

Admittedly, I don't know the currently applied practices for determining precise coordinates, but I think as a first approach the village of Gallicianò in the area of Reggio Calabria may be a good choice, as a "large" number of speakers currently still using the language are connected to that village. Coordinates for a random point close the the entrance to the village would be (38.0166, 15.88621) according to OpenStreetMap.
Alternatively, there is the village/town of Bova which is culturally much associated with the Greek-speaking people of the area, coordinates for a point in the centre of town are (37.99427, 15.9323).
However, I got the impression there are a few more speakers in (or associated with) Gallicianò, so I would opt for using the first set of coordinates.

**Comment by gfkpth** [comment]
I forgot, if this addition is accepted, it would probably make sense to use the current coordinates for [apul1236] for the specific languid of Apulian/Salento Greek [apul1237] instead.

**Comment by d97hah** [comment]
Ok, is there any reason you prefer the joint languoid to be associated with
Aspromonte rather than Apulian?

Pada tanggal Rab, 15 Apr 2020 pukul 13.44 gfkpth <notifications@github.com>
menulis:

**Comment by gfkpth** [comment]
Oh, for the joint languoid I'm actually not sure which option would be best - the problem being that they are actually two clearly distinct (albeit abviously related) varieties with no "intermediate" dialects in the areas between - so a point geographically in the middle would be "fairest" but factually possibly misleading. Speaker numbers are likely much higher for the Apulian Greek variety, but I'm not sure if that should be a deciding factor?
I don't know how glottolog normally deals with such situations?

My point was mostly to add coordinates to [aspr1238] and to [apul1237], I'm not actually sure what an approach to appropriate coordinates for [apul1236] would be.

**Comment by xrotwang** [comment]
Higher speaker numbers seems like a good justification for a point-location of a dialect.

**Comment by gfkpth** [comment]
Ok, that seems reasonable. I think the practical problem/question is if it makes sense to have a point at all for that level. I've had a closer look at how levels like "High German" are treated and indeed it seems that all individual data points are shown rather than one overall/average point. I think this might be the best approach for [apul1236] as well, i.e. displaying the coordinates of both [apul1237] and [aspr1238] rather than trying to (more or less arbitrarily) decide for one specific point.

**Comment by xrotwang** [comment]
@gfkpth It makes sense in this case, because the higher organizational level is **not** a family-level languoid like "High German", but a language-level languoid. Language-level languoids have a somewhat special status in that they are deemed most appropriate for any comparative analyses. Thus, there's an expectation of many users that language-level languoids have a point coordinate.

**Comment by d97hah** [comment]
There is no grand principle we are consistently following sometimes
demographic, sometimes geographic, sometimes historical centre but mostly
we follow the principle of conservatism: if the point isn't clearly wrong,
no change. So here let's stick to the Apulian coordinate

Pada tanggal Rab, 15 Apr 2020 pukul 17.10 gfkpth <notifications@github.com>
menulis:

**Comment by xrotwang** [comment]
@d97hah but we can add
```
latitude = 38.0168301
longitude = 15.8844409
```
for [Aspromonte](https://glottolog.org/resource/languoid/id/aspr1238), right?

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/commit/b66c76e5e10137d6996da93704a750491cba3931

**Comment by d97hah** [comment]
Indeed I did

Pada tanggal Rab, 15 Apr 2020 pukul 17.49 Robert Forkel <
notifications@github.com> menulis:

**Comment by gfkpth** [comment]
That's good, thanks - also for the explanation!

Ideally, at some point it may still be worth figuring out whether the two varieties should indeed be treated as the same or separate languages. There is some amount of mutual intelligibility, but I don't know how strong that is (i.e. if it's more than what you'd find between, e.g., Standard Modern Greek and Cypriot). They also seem to differ in several aspects grammatically (Apulian seems to be much more "italicised") and I think the communities haven't had much if any interaction historically, up until recently. But for now, leaving Apulian Greek as the (numerically) dominant variant is probably ok for most practical purposes, especially given the cited principle.

**Comment by d97hah** [comment]
I did try to find this out when it was initially added and according to my
notes it is Tozer 1889:37 who says they are intelligible, but few other
sources say anything in the matter

Pada tanggal Rab, 15 Apr 2020 pukul 19.11 gfkpth <notifications@github.com>
menulis:
