### ISSUE TITLE
Khinalugh -> Khinalug

### ISSUE THREAD

**Issue by agricolamz** [glottolog/glottolog#514]
Dear all, is it possible to change language name in Glottolog, since _Khinalug_ is one used by specialists, and you have no reference with _Khinalugh_ variant (except some databases like [Ethnologue](https://www.ethnologue.com/language/kjj?__cf_chl_jschl_tk__=2a87cd2af5ee98e7d90cb0fea8d1b5990e7db692-1589013125-0-ASnHaZg6X1GLIcZMMil3_e5vImzWT6um_XnjKP1pR5mRwqkX4f1pPdfJjayzkXbX38drOwoY8qmDijOrEK-f-oaz-s0dqTRbEIXHmd4J_-jgSy0addgsidBFTFSLabETteFdiqgZhshTTGyar4XU4knQ7yt-eSgrlrV3yCvKvx3IKMbPX82G5l0grtS9m07vfsHu0w36C4tNvIida_OlEKtqLkmRtICtbFVHyI3jnqzvcxe49-xdA4a2z7ZMqLrrYW-XOz0v_sQ0x9dsBUFKFVCaHfADhBHTM2T_KKNs6BYA) and [SIL](https://iso639-3.sil.org/code/kjj))

**Comment by d97hah** [comment]
Indeed. I've adjusted it for next version! H

Pada tanggal Sab, 9 Mei 2020 pukul 10.31 George Moroz <
notifications@github.com> menulis:

**Comment by agricolamz** [comment]
Thank you!
