### ISSUE TITLE
"print.google.com" URLs do not work

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#515]
E.g. `http://print.google.com/print?id=U8IxYGujF-8C` - given as `url` for `g:HolmesHinchliffe:Swedish` in `hh.bib` resolves to HTTP 404. Replacing `print` with `books` seems to do the right thing, i.e. https://books.google.de/books?id=U8IxYGujF-8C does work.

**Comment by d97hah** [comment]
Thanks, fixed, see PR

Pada tanggal Sen, 11 Mei 2020 pukul 13.39 Robert Forkel <
notifications@github.com> menulis:
