### ISSUE TITLE
Edition is not rendered in the linearization of bib-entries

### ISSUE THREAD

**Issue by d97hah** [glottolog/glottolog#521]
Acc to unified style sheet it should come immediately before publisher and be "XY edn."
where X is the edition (e.g., 2, 3, IV) and Y is st/nd/rd or th if X is roman and X mod 10 is 1/2/3 or sthng else. 

E.g.

https://glottolog.org/resource/reference/id/314538

is now

Thiesen, Wesley. 2008. Gramática del idioma bora. (Serie Lingüística Peruana, 38.) Pucallpa: Ministerio de Educación and Instituto Lingüístico de Verano. 132pp.

should be

Thiesen, Wesley. (2008) Gramática del idioma bora (Serie Lingüística Peruana 38). 2nd edn. Pucallpa: Ministerio de Educación and Instituto Lingüístico de Verano.

**Comment by xrotwang** [comment]
See https://github.com/clld/clldutils/issues/95

**Comment by xrotwang** [comment]
@d97hah The year should not be in parentheses, though, right?

**Comment by d97hah** [comment]
Yes, you are right, not in parentheses! H

Pada tanggal Kam, 1 Okt 2020 pukul 12.28 Robert Forkel <
notifications@github.com> menulis:
