### ISSUE TITLE
"Comments on subclassification" not culumative?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#522]
I just noticed that the "Comments on subclassification" aren't cumulative, either up or down. For example, Walworth and Marck are referenced at internal node marq1246, and at the family node, aust1307, Blust & Chen and Blust are quoted. 

I was under the impression, just until now, that the listing higher up included the subclassification comments for all the daughters or that the lower down classifications also included references to the higher up. I guess that the actual situation kind of makes sense, the "Comments on subclassification" only refers to that precise node and its direct daughters.

How would I go about seeing the references for all the subclassifications in the entire tree?

**Comment by xrotwang** [comment]
I guess that would be a case for `pyglottolog`:
```python
from pyglottolog import Glottolog
api = Glottolog('.')
l = api.languoid('marq1246')
print(l.id, l.classification_comment.subrefs)
while l.parent:
    l = l.parent
    print(l.classification_comment.subrefs)
```

**Comment by HedvigS** [comment]
Right, okay. Is the opposite also possible?

from pyglottolog import Glottolog
api = Glottolog('.')
l = api.languoid('aust1307')
print(l.id, l.classification_comment.subrefs)
while l.daughter:
    l = l.daughter
    print(l.classification_comment.subrefs)

**Comment by xrotwang** [comment]
In principle, yes, the recursion needs to be a bit more explicit, though:
```python
from pyglottolog import Glottolog

def subclfrefs(node, level, agg):
    if node.classification_comment:
        for ref in node.classification_comment.subrefs:
            agg.add(ref.key)
    if level < 5:
        for l in node.children:
            subclfrefs(l, level + 1, agg)

api = Glottolog('.')
refs = set()
subclfrefs(api.languoid('aust1307'), 0, refs)
for ref in refs:
    print(ref)
```
Austronesian is big, so limiting the search depth (via `level`) may make sense.

**Comment by HedvigS** [comment]
Right, okay. I'll try that then. Thanks!

**Comment by HedvigS** [comment]
(102 references turned up and I can't comfortable cite them all so I'll just cite the main Blust and Chen ones and refer the reader to check Glottolog for more details.)
