### ISSUE TITLE
Wrong date for  Zajceva, Marija Ivanovna. 981. Grammatika vepsskogo jazyka: Fonetika i morfologija

### ISSUE THREAD

**Issue by IanMaddieson** [glottolog/glottolog#523]
The date for this reference related to veps1250 should be 1981, not 981 (unless it's written in Proto-Slavic?). Also the same Russian family name is transliterated in three different ways in references related to Veps, the most common way would be to spell it "Zaitseva".

**Comment by d97hah** [comment]
Thanks I've fixed the date for next version. all the best, H

Pada tanggal Min, 24 Mei 2020 pukul 04.38 IanMaddieson <
notifications@github.com> menulis:
