### ISSUE TITLE
Reversed latitude and longitude for Ngaalam [ngaa1241]

### ISSUE THREAD

**Issue by jlesg** [glottolog/glottolog#524]
Hi,

I noticed that the geographical coordinates for Ngaalam [ngaa1241] are reversed, which puts it in Tunesia instead of Ethiopia. 

They are currently:

> longitude = 8.216287
> latitude = 34.563102

They should be:

> longitude = 34.563102
> latitude = 8.216287

All the best,

Jakob

**Comment by d97hah** [comment]
Thanks for spotting that, fixed for next version! H

Pada tanggal Sel, 26 Mei 2020 pukul 11.12 Jakob Lesage <
notifications@github.com> menulis:
