### ISSUE TITLE
Latitude / Longitude for Halkomelem incorrect

### ISSUE THREAD

**Issue by martsen79** [glottolog/glottolog#530]
The latitude and longitude for Halkomelem appears puts them inland near Granite Falls, when the Halkomelem peoples are historically located in Canada, on the mainland along the Fraser River, and on Vancouver Island around what is today Nanaimo and extending south and east toward what is now Saanich. A centroid would probably put the dot in the Salish Sea.

**Comment by d97hah** [comment]
Thanks you are right, I've adjusted the coordinate for next version to be
in east Vancouver (not wanting a dot in water)

Pada tanggal Kam, 11 Jun 2020 pukul 16.58 martsen79 <
notifications@github.com> menulis:
