### ISSUE TITLE
Achomi

### ISSUE THREAD

**Issue by ghachomi55** [glottolog/glottolog#533]
https://github.com/glottolog/glottolog/blob/a1ef02e22a2db3d1637844ec84e884c2242c67cc/languoids/tree/indo1319/indo1320/iran1269/sout3157/midd1352/mode1259/lari1253/md.ini#L5

**Comment by ghachomi55** [comment]
Lari is a dialect, but achomi is a common language The Larestani dialect is for the people of Lar, but the Achomi language is an achomiadzin region.

**Comment by d97hah** [comment]
I think I judged this as unclear what change is being prompted

Pada tanggal Jum, 14 Mei 2021 pukul 14.16 Robert Forkel <
***@***.***> menulis:
