### ISSUE TITLE
Citing Glottolog search results

### ISSUE THREAD

**Issue by HughP** [glottolog/glottolog#535]
Greetings,

Currently search parameters are not passed to the URL so I can not share or cite a search query of the resources in glottolog. I feel this is a shortcoming because I can not cite some findings. The findings I wanted to cite were that I found 886 entries with 'bibliography' in the title at https://glottolog.org/langdoc. Would think that something like https://glottolog.org/langdoc[/search?q=title&&bibliography] might make search queries more citable and shareable.

**Comment by xrotwang** [comment]
You get a URL including search params from the "complex query", e.g. https://glottolog.org/langdoc/complexquery?languoids=&author=&year=&title=bibliography&editor=&journal=&address=&publisher=

A citation using such a URL would need to include an "accessed at" qualification, though, and it might not be entirely trivial to recreate the exact result set a couple of years from now. So I'm not sure I'd want to encourage citing such resources.

**Comment by haspelmath** [comment]
Thanks – this is great for sharing (e.g. in an e-mail or on Twitter). It's of course not something to be used for formal citation.

**Comment by HughP** [comment]
@haspelmath with regard to a formal citation I disagree with you. If one is citing query results from a specific query, then the syntax of the query is certainly to be included in the citation. That is simple reproducible science.

**Comment by xrotwang** [comment]
@HughP the reproducibility aspect is exactly the problem: While a full URL may allow you to reproduce the results you have seen for the time being, this may not be the case after the next Glottolog version update. So reproducibility is a bit of a false hope here. If you are after "real" reproducibility, you'd have to cite the Glottolog dataset DOI and provide a piece of code "running" your search query on this data.

**Comment by HughP** [comment]
@xrotwang Your point about the versioning is well understood, in fact that is why a version number would be added to the citation. If I follow the logic you present about code and "real" reproducibility then I shouldn't cite the glottolog at all I should only cite the dataset in the first place.

**Comment by haspelmath** [comment]
Yes, the way I understand it, the Glottolog *IS* the dataset. The webpage is just a particular presentation of the data. Maybe we should somehow make this clearer.

**Comment by HughP** [comment]
Well, the way that the citation reads now, is that it is a book... not a dataset. this was confirmed by two editors in issue #536 

```
@book{hammarstrom_glottolog_2020,	
address = {Jena},	
title = {Glottolog 4.2.1},	
url = {https://glottolog.org/},	
urldate = {2020-07-06},	
publisher = {Max Planck Institute for the Science of Human History},	
editor = {Hammarström, Harald and Forkel, Robert and Haspelmath, Martin and Bank, Sebastian},	
year = {2020}}
```

**Comment by xrotwang** [comment]
Well, there's no BibTeX type for dataset - and having seen quite a few datasets as printed books, I think that's a false dichotomy anyway. That said, it's true that the link to the dataset - the DOI https://doi.org/10.5281/zenodo.3754591 - is missing in the metadata delivered to Zotero. Noted at https://github.com/clld/glottolog3/issues/124

**Comment by HughP** [comment]
Yes, the limits of BibTex are well and widely acknowledged. That is why it is not a prefered format to build a database around. In fact a large part of the TeX community has moved on to [BibLaTeX](https://ctan.org/pkg/biblatex) which does have the type `@suppbook` for supplemental materials to a book, AND also has a direct type for Datasets (see page 10 of the documentation). 
`@misc` is one solution that arises in bibTeX as noted in this blog post dealin with the issue: https://nennius.wordpress.com/2013/11/27/using-bibtex-for-dataset-citation/

**Comment by xrotwang** [comment]
I look at metadata formats - and in particular bibliographic metadata - from a very pragmatic perspective: 
- Does it have tool support?
- Does it have support from publishers?
- Is it extensible, i.e. function as generic key-value storage?

BibTeX ticks all those boxes. BibLaTeX - e.g. - doesn't have a python package.

I'm also rather pragmatic regarding the main categories in a bibliographic database. If you consider Glottolog a biggish publication by the same set of author/editors which is published in subsequent editions, this seems to be described appropriately with `book`. A formatted citation of the BibTeX metadata also "comes out ok" with the `book` type. That's basically the two things I'd ask for.

So while BibTeX might not be "a prefered format to build a database around", I think it does largely what we want from it in our context.

**Comment by xrotwang** [comment]
Oh and I should add that as soon as something has a DOI, arguably this DOI should be used to retrieve the metadata. With the Zenodo DOI from Zenodo you'd get metadata that tells you the thing is a `dataset`.
