### ISSUE TITLE
coordinates for Amis' dialect: Tavalong-Vataan - tava1241

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#541]
lat: 23.635064
long: 121.422761
referring to Taiwanese Guangfu township (光復鄉) since an alternative name is Kuangfu (also found at [https://nl.wikipedia.org/wiki/Tavalong-Vataan](https://nl.wikipedia.org/wiki/Tavalong-Vataan))

[Glottolog entry tava1241](https://glottolog.org/resource/languoid/id/tava1241)

**Comment by d97hah** [comment]
Thanks, added for next version! H

Pada tanggal Rab, 22 Jul 2020 pukul 15.54 Hans-Jörg Bibiko <
notifications@github.com> menulis:
