### ISSUE TITLE
Ardhamagadhi Prakrit

### ISSUE THREAD

**Issue by aryamanarora** [glottolog/glottolog#545]
Hi, new to Glottolog so not sure if I'm doing this right. Currently, there's no documentation of [Ardhamagadhi Prakrit](https://en.wikipedia.org/wiki/Ardhamagadhi_Prakrit). Ardhamagadhi is a Middle Indo-Aryan language, generally thought to the ancestor of the Eastern Hindi languages (Saksena [1971] among others) and closely related to Shauraseni Prakrit (`saur1252`) and Pali (`pali1273`). I would classify it under the Indo-Aryan central zone (https://glottolog.org/resource/languoid/id/indo1322). It also has an ISO code `pka` which isn't in Glottolog yet.

In fact, it seems to be classified as an alternative name for Pali on Glottolog. This, I don't think, is an accepted notion in Indo-Aryan linguistic scholarship. I'll add more references as I find them. I really think it should be split into its own language.

Also note that Ardhamagadhi is one of the languages of the Jain canon, i.e. a separate religious tradition from Pali which was espoused by Buddhism.

## References
* Baburam Saksena (1971). _Evolution of Awadhi (a Branch of Hindi)._
* R. L. Turner (1966). _A comparative dictionary of Indo-Aryan languages._ (listed as a separate Prakrit from Pali under the abbreviation *amg.* in entries)
* R. Pischel (1900), translated by Subhadra Jha (1957) _Comparative Grammar Of The Prakrit Languages_ (in the Introduction, dedicates a section to Ardhamagadhi as a separate Prakrit)

Unfortunately there hasn't been much recent work on Ardhamagadhi by itself, but it's certainly mentioned in general Middle Indo-Aryan scholarship, in both English and Indian languages.

**Comment by d97hah** [comment]
It's not classified as an alternative name for Pali but as a variety
intelligible to Pali. Do you know if this was not the case?

Pada tanggal Sel, 4 Agu 2020 pukul 04.06 Aryaman Arora <
notifications@github.com> menulis:

**Comment by aryamanarora** [comment]
@d97hah Ah okay. That is likely true, seeing as all the Prakrits and Pali were mutually intelligible to some degree. (A lot of the dramas that have been preserved would assign different languages to different classes of characters, and presumably, audiences understood them all.)
