### ISSUE TITLE
Wrong location of Coeruna coer1236

### ISSUE THREAD

**Issue by thiagochacon** [glottolog/glottolog#552]
coer1236 is wrongly places within the Northern Andes. It is location should be further south, near its linguistic relatives of the Witotoan family. Based on Kaufman's 1994 map 20 and 21, I would like to suggest the following new coordinates

-72.9, -1.96

This should be revised with ethnographic information

Kaufman, Terrence. 1994. The native languages of South America. In Atlas of the world's languages, ed. Christopher Moseley and R. E. Asher, 46-76. London: Routledge.

**Comment by d97hah** [comment]
von Martius (1867:273) says the vocabulary was collected in S. Antonio de
Maripi (there's a present-day location with that name at (-74.01139,
5.52833) --- which is the source of the current erroneous coordinate in
Glottolog). But von Martius S Antonio de Maripi is different, and does not
seem to exist anymore with that name. Its location is on the lower Japurá
in Brazil:
https://gallica.bnf.fr/ark:/12148/btv1b53093718p/f1.item.zoom
Spix (1831 Resien II:1202) says S Antonio de Maripi was a mixed
administrative village were Indians from various neighboring tribes were
found, and that the Coeruna lived on the Miriti-Parana, at the tributary
that the Coeruna call Caritaja. This name for the tributary river is
(obviously) not to be found anywhere else, but von Martius map has a
Caritaxa tributary to the Miriti-Parana. I gauge from his map this is
something like Coordinates (-70.55, -1.05), in any case between the Curetu
and the Yucuna. It's difficult to understand Kaufman's 1994 location but I
don't have a complete copy of Kaufman 1994 and his maps, if you do, can you
send? Thanks and thanks for spotting this, H








Pada tanggal Sel, 1 Sep 2020 pukul 22.51 thiagochacon <
notifications@github.com> menulis:

**Comment by thiagochacon** [comment]
thanks for getting the information from Martius!


I don't have the full maps, but I used Campbell's reprints of them in his 1997 "American Indian Languages" on pages 364 and 366.


Thiago Costa Chacon
Linguista - Professor Adjunto (Assistant Professor of Linguistics)
Departamento de Linguistica, Portugues e Linguas Classicas
Universidade de Brasilia
________________________________
De: d97hah <notifications@github.com>
Enviado: quarta-feira, 2 de setembro de 2020 08:08
Para: glottolog/glottolog <glottolog@noreply.github.com>
Cc: thiagochacon <thiago_chacon@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [glottolog/glottolog] Wrong location of Coeruna coer1236 (#552)


von Martius (1867:273) says the vocabulary was collected in S. Antonio de
Maripi (there's a present-day location with that name at (-74.01139,
5.52833) --- which is the source of the current erroneous coordinate in
Glottolog). But von Martius S Antonio de Maripi is different, and does not
seem to exist anymore with that name. Its location is on the lower Japurá
in Brazil:
https://gallica.bnf.fr/ark:/12148/btv1b53093718p/f1.item.zoom
Spix (1831 Resien II:1202) says S Antonio de Maripi was a mixed
administrative village were Indians from various neighboring tribes were
found, and that the Coeruna lived on the Miriti-Parana, at the tributary
that the Coeruna call Caritaja. This name for the tributary river is
(obviously) not to be found anywhere else, but von Martius map has a
Caritaxa tributary to the Miriti-Parana. I gauge from his map this is
something like Coordinates (-70.55, -1.05), in any case between the Curetu
and the Yucuna. It's difficult to understand Kaufman's 1994 location but I
don't have a complete copy of Kaufman 1994 and his maps, if you do, can you
send? Thanks and thanks for spotting this, H








Pada tanggal Sel, 1 Sep 2020 pukul 22.51 thiagochacon <
notifications@github.com> menulis:
