### ISSUE TITLE
Wrong Glottocode in Capell (1951-1952)

### ISSUE THREAD

**Issue by barlowrussell** [glottolog/glottolog#553]
The language that Capell calls "Murusapa" is not [tang1356] (as currently indicated on the site), but rather [more1258]. 

Arthur Capell. 1951-1952. Languages of Bogia District, New Guinea. Oceania 22. 130-147, 178-207, 317-317.

**Comment by d97hah** [comment]
Thanks, I'll fix that for next version. all the best, H

Pada tanggal Kam, 3 Sep 2020 pukul 20.21 barlowrussell <
notifications@github.com> menulis:
