### ISSUE TITLE
Wrong Glottocodes for Bell (1934) and Bell (1938)

### ISSUE THREAD

**Issue by barlowrussell** [glottolog/glottolog#554]
These are both currently tagged as "Tangu [tang1355]". However, both should be "Tangga [tang1348]".

Bell, F. L. S. 1934. Report on Field Work in Tanga. Oceania 4. 290-309.
Bell, F. L. S. 1938. Courtship and Marriage Among the Tanga. Oceania 8. 401-418.

**Comment by d97hah** [comment]
Thanks I've fixed it for the dplace.bib in Glottolog but @Robert Forkel
<xrotwang@googlemail.com> someone might wish to take it further in D-place

Pada tanggal Jum, 4 Sep 2020 pukul 20.41 barlowrussell <
notifications@github.com> menulis:
