### ISSUE TITLE
Invalid year in hh:g:Chareanraat:Kuay

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#560]
2525 can't be right here:
```bibtex
@mastersthesis{g:Chareanraat:Kuay,
    author = {Chirat Chareanraat},
    title = {The Kuay language of Suphanburi},
    school = {Silpakorn University},
    pages = {375},
    year = {2525 [1982]},
    besttxt = {ptxt2\eurasia\chareanraat_kuay1982_o.txt},
    fn = {eurasia\chareanraat_kuay1982v2_o.pdf, eurasia\chareanraat_kuay1982_o.pdf, eurasia\chareanraat_kuay1982.pdf},
    glottolog_ref_id = {304259},
    hhtype = {grammar},
    inlg = {Thai [tha]},
    lgcode = {Kuay = Kuy [kdt]},
    macro_area = {Eurasia},
    title_original = {ภาษากวย (ส่วย) ที่จังหวัดสุพรรณบุรี}
}
```

**Comment by d97hah** [comment]
Yes it's right but not on the Munich calendar, but read the year in
brackets for the corresponding year on the calendar you want

Pada tanggal Sen, 21 Sep 2020 pukul 16.17 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Ah, I see. And it seems the logic of taking the stuff in square brackets when computing `year_int` is also implemented (in `pyglottolog`). I just naively ran `cast(year as int)` in SQLite on this, and that - of course - took the `2525` as number.

Maybe we should add an explicit `year_gregorian` to the BibTeX files already? This would then be propogated to the CLDF data and eventually to the SQLite database (see https://github.com/glottolog/cookbook/tree/master/recipes/glottolog_cldf)?

**Comment by d97hah** [comment]
If you want to add that as an automatic to the bibtex (and something
similar will be in demand in turning pages into pages_int) go ahead.

Pada tanggal Sen, 21 Sep 2020 pukul 16.45 Robert Forkel <
notifications@github.com> menulis:
