### ISSUE TITLE
Duplicate address in publisher field in hh.bib

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#570]
In `hh.bib` it happens quite often that the `address` field is duplicated in `publisher`,e.g.
```bibtex
@book{d:Anonimo:Geral,
    author = {Anônimo},
    title = {O diccionario anonymo da Lingua Geral do Brasil, publicado de novo com seu reverso por Julio Platzmann},
    publisher = {Leipzig: B.~G.~Teubner},
    address = {Leipzig},
    pages = {181},
    year = {1896 [1795]},
    besttxt = {ptxt2\south_america\anonimo_diccionario-geral1896.txt},
    fn = {south_america\anonimo_diccionario-geral1896.pdf},
    glottolog_ref_id = {82752},
    hhtype = {dictionary},
    inlg = {Portuguese [por]},
    lgcode = {Nhengatu [yrl]},
    macro_area = {South America}
}
```

Should we fix this in the bibtex file? Or is this considered a feature and should be fixed - e.g. when linearizing?

**Comment by d97hah** [comment]
I advocate the 'feature' solution, i.e., when linearizing, just check if
publisher.startswith(address) and if so suppress address. The origin of the
issue lies in the fact that some bibtex styles do not automatically add
address when linearizing.

Pada tanggal Kam, 8 Okt 2020 pukul 15.57 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
ok
