### ISSUE TITLE
Remove two languages from reference "John A. Z'graggen 1972"

### ISSUE THREAD

**Issue by barlowrussell** [glottolog/glottolog#573]
Two languages--(1) Aion [amba1269] and (2) Kambot [apma1241]--should be removed from the following "wordlist" reference, since only their names are included; there is absolutely no linguistic information in there for either:

John A. Z'graggen. 1972. Comparative Wordlist of the Ramu language group, New Guinea. Alexishafen: Anthropos Insitute. 280pp.

Also, there's a typo in the bibliographic entry: it should be "Institute". The version I have of this ms. is dated 1974 (not 1972); and the title is "Ramu comparative wordlist". I hear there are earlier hand-written versions of this document, but the 1974 (typed) version is maybe more authoritative?

**Comment by d97hah** [comment]
Thanks, yes you are right (also it should be 380pp). I'll fix that. My copy
of this is in 3 volumes, the first dated 1972 without question marks, the
second also dated to 1972 but the section on the title page mentioning the
Madang lgs project 1971-1972 has hand-corrected that 1972 to 1973. My copy
of vol III lacks the title page. All three volumes have the actual word
forms in vernacular lgs hand-written. Could you send me a copy of the 1974
typed up version? Thanks, H

Pada tanggal Kam, 15 Okt 2020 pukul 22.40 barlowrussell <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah can we close this?

**Comment by d97hah** [comment]
Yes

Pada tanggal Jum, 14 Mei 2021 pukul 14.25 Robert Forkel <
***@***.***> menulis:
