### ISSUE TITLE
Internal classification of Romani

### ISSUE THREAD

**Issue by ViktorElsik** [glottolog/glottolog#574]
For the internal classification of varieties of Romani (https://glottolog.org/resource/languoid/id/roma1329) you may find it useful to consult a recent overview in Elšík, Viktor & Beníšek, Michael. 2020. Romani dialectology. In: Matras, Yaron & Tenser, Anton (eds.) The Palgrave handbook of Romani language and linguistics. Palgrave Macmillan Publishers. 389–428.

**Comment by d97hah** [comment]
Thanks Viktor, I had seen that but thought it was rather inconclusive on
the genealogical/areal explanation for specific cases and hence not cause
for updates to the current Glottolog. That said, I read it more carefully
now, and it does contain a number of updates which are not consistent with
the current Glottolog (Northern Romani as a genetic group, the North
Transylvanian dialects) which I'll fix and cite accordinly. all the best, H

Pada tanggal Jum, 16 Okt 2020 pukul 00.46 ViktorElsik <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
Also now that I have your attention, is Elsik et al (in prep) available?

"Elsik et al. (in preparation) classify their sample of over 400 local
varieties of Central Romani into two dialect groups, 12 dialect subgroups
and 70 dialect regions on the basis of a complex of structural linguistic
(i.e. phonological, grammatical, and lexical) criteria."

Elšík, Viktor, Michael Beníšek, and Zuzana Bodnárová. In preparation. The
linguistic
atlas of Central Romani. Manuscript. Prague: Charles University.


Pada tanggal Min, 18 Okt 2020 pukul 14.38 Harald Hammarström <
harald.hammarstrom@gmail.com> menulis:

**Comment by xrotwang** [comment]
@d97hah can we close this?

**Comment by d97hah** [comment]
Yes

Pada tanggal Jum, 14 Mei 2021 pukul 14.26 Robert Forkel <
***@***.***> menulis:
