### ISSUE TITLE
Adding missing sign language coordinates

### ISSUE THREAD

**Issue by borstell** [glottolog/glottolog#639]
glottocode,latitude,longitude,edit
inma1234,-12.144766,-77.019557,new
kail1256,-5.898418,144.152512,new
leso1234,-29.31,27.48,new
miri1273,-15.773611,128.738611,new
moun1255,-9,148.3,new
oldb1247,13.7525,100.494167,new
sivi1235,-12.5125,-73.857778,new
wani1243,-3.857281,142.53,new
mehe1245,-3.857281,142.7295,correction

**Comment by d97hah** [comment]
Thanks Calle! Two quick q:s, 1. what is the source for the coordinate of
Mount Avejaha sign? I cannot find this mountain on maps and I do not know
the village name where the information about it emanates from. 2. what is
the source of the very southeastern corrected coordinate for Mehek Sign lg?
I would have assumed Hatfield got the bulk of his information at
Wilwil (which is shown on his maps)?! all the best, H

Pada tanggal Kam, 10 Des 2020 pukul 00.43 Carl Börstell <
notifications@github.com> menulis:

**Comment by borstell** [comment]
Yes, sorry I should have mentioned the sources!

A recent chapter by Reed & Rumsey (2020; which I didn't find in Glottolog in its final published form, BibTeX below), has a map on page 141 with the locations of the sign languages mentioned in the chapter. I overlayed this map onto Google Maps and could approximate the Wanib and Mt. Avejaha points on the map based on that (although Mt. Avejaha is marked as "exact location uncertain"). In the text, Wanib is described as being "immediately west of the Mehek" (p. 150), and judging from their location on the map, they are closer to Avatip than the current coordinates for Mehek show (just triangulating Avatip, Wewak, and Serai), so I approximated them both based on the overlay mapping and their relative locations to each other (i.e. directly east–west). The map is labeled "(ANU) CartoGIS CAP 19-230_KP" which I couldn't find in their online repository, if it even is a unique key, but I guess it might be possible to ask for their coordinates. I could ask Lauren unless you happen to have a direct contact with the ANU cartographers.

* Sivia and (Old) Bangkok are just general coordinates for the cities.
* Lesotho = general coordinates for Maseru.
* Miriwoong = general coordinates for Kununurra.
* Inmaculada is more or less exact coordinates for the location of the school in Lima.

```
@incollection{reed_rumsey_2020,
	address = {Amsterdam},
	title = {Sign Languages in Papua New Guinea and the Solomon Islands},
	isbn = {978-90-272-0453-0 978-90-272-6182-3},
	url = {https://benjamins.com/catalog/z.226.se1},
	booktitle = {Sign Language in Papua New Guinea: A primary sign language from the Upper Lagaip Valley, Enga Province},
	publisher = {John Benjamins Publishing Company},
	author = {Reed, Lauren W. and Rumsey, Alan},
	editor = {Kendon, Adam},
	year = {2020},
	doi = {10.1075/z.226.se1},
	pages = {141--183}
}
```

**Comment by d97hah** [comment]
I don't have the published version of the paper but it seems they are not
very careful about the coordinates. At same time neither Hatfield or Diaz
say exactly where they recorded their deaf individuals. I think the best
one can get is the below (assuming the locations of the main fieldsites).
It would be great if you could ask Lauren how they got the Mt Avejaha
coordinates
Wanib SL of Tuginaro (142.53, -3.758622)
Mehek SL of Wilwil (142.49818, -3.70927)

Pada tanggal Kam, 10 Des 2020 pukul 10.54 Carl Börstell <
notifications@github.com> menulis:

**Comment by borstell** [comment]
```
glottocode,latitude,longitude,data
kail1256,-5.94376666666667,144.111873167568,gps
moun1255,-8.89880652408157,148.189291736927,oro-mid
wani1243,-3.91084764848502,142.629496756726,gps
mehe1245,-3.9075812670558,142.713506478241,gps
```

These are the exact coordinates used in Reed & Rumsey (2020), personal communication with the first author. Kailge is based on actual GPS data, Wanib and Mehek GPS(?) data also (these three are all from the cartographers' data). Mt Avejaha was estimated based on a midpoint in the Oro region.

**Comment by d97hah** [comment]
Thanks, do you know what midpoint in the Oro region?

Pada tanggal Sel, 26 Jan 2021 pukul 00.29 Carl Börstell <
notifications@github.com> menulis:

**Comment by borstell** [comment]
It would be the coordinates I pasted above (should have mentioned that they were all new), thus:

`moun1255,-8.89880652408157,148.189291736927`

**Comment by d97hah** [comment]
Right but I meant *what* midpoint is referred to when you say "based on a
midpoint in the Oro region"? The midpoint OF the Oro region?

Pada tanggal Sel, 26 Jan 2021 pukul 01.35 Carl Börstell <
notifications@github.com> menulis:
