### ISSUE TITLE
delete https://glottolog.org/resource/reference/id/136682

### ISSUE THREAD

**Issue by alenawitzlack** [glottolog/glottolog#640]
This entry should be deleted, as it contains a typo in the authors name (Ki**ll**ian instead of Ki**l**ian) and the title is incorrect (should be _**A** Grammar of Modern Khwe_ not _Grammar of Modern Khwe_). The correct reference is provided in https://glottolog.org/resource/reference/id/12267.

**Comment by d97hah** [comment]
Thanks Alena I've fixed that for next version! H

Pada tanggal Jum, 11 Des 2020 pukul 10.46 alenawitzlack <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/commit/451d92ee21bf53e327e8affe3ccbf98f0763fcab#diff-c513f662d0f961193dc24d1b79e53a17eac42fddbd01284d1e6b8f69fe731fef
