### ISSUE TITLE
requesting glottocode - Raoping Hakka

### ISSUE THREAD

**Issue by keyilan** [glottolog/glottolog#646]
The Raoping variety of Hakka (Sinitic) does not have a glottocode. Unfortunately the best description (to my knowledge) 《臺灣饒平客話》 of the variety isn't available in English, but only in Mandarin. This is one of the five Hakka groups spoken in Taiwan, as well as in Raoping County in Guangdong province. While the classification within Hakka (in terms of sub-branches) isn't well settled on, it's definitely its own variety within Hakka.

Would it be possible to get it added as a node under `hakk1236`? If needed, I can track down more sources attesting the existence and some description of the variety.

Apologies if creating this as an issue isn't the preferred way to make such requests. I figured it was preferable to just emailing, though.

**Comment by d97hah** [comment]
Hi Kellen! Yes, sure, will be added for next version as Raoping [raop1234]
(directly) under Hakka. This is the preferred wat to make requests
(although others are possible too). all the best, H

Pada tanggal Sel, 19 Jan 2021 pukul 10.30 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See
```
$ glottolog tree hakk1236
INFO    glottolog/glottolog at /home/robert_forkel/projects/glottolog/glottolog
Sino-Tibetan [sino1245]
   └─ Sinitic [sini1245]
      └─ Classical-Middle-Modern Sinitic [clas1255]
         └─ Middle-Modern Sinitic [midd1354]
            └─ Hakka Chinese [hakk1236]
               ├─ Hailu [hail1247]
               ├─ Huizhou [huiz1243]
               ├─ Meixian [yuet1238]
               ├─ Ning-Long [ning1269]
               ├─ Raoping [raop1234]
               ├─ Sixian [sanh1239]
               │  ├─ Liudui-Pingtung [liud1234]
               │  └─ Taoyuan-Miaoli [taoy1234]
               ├─ Tingzhou [ting1250]
               │  ├─ Changting [chan1325]
               │  ├─ Liancheng [lian1259]
               │  ├─ Mingxi [ming1255]
               │  ├─ Ninghua [ning1278]
               │  ├─ Qingliu [qing1239]
               │  ├─ Shanghang [shan1292]
               │  ├─ Wuping [wupi1239]
               │  └─ Yongding [yong1284]
               ├─ Tonggu [tong1314]
               ├─ Yuebei [yueb1238]
               ├─ Yuezhong [yuez1238]
               └─ Yugui [yugu1248]
```
