### ISSUE TITLE
Links missing in Glendon A. Lean. 1986. Gulf Province.

### ISSUE THREAD

**Issue by barlowrussell** [glottolog/glottolog#647]
"North-Eastern Kiwai" should link to [nort2930].
"Arigibi" should (also) link to [nort2930].
"Podopa" should link to [folo1238].
"Purari" should link to [pura1257].

Also, "Barika, Kairi [rumu1243]" should be changed to "Kairi [rumu1243]".
And "Dugeme [ikob1240]" is maybe superfluous?

Reference: Glendon A. Lean. 1986. Gulf Province. (Counting Systems of Papua New Guinea, 11.) Port Moresby: Papua New Guinea University of Technology. (Draft Edition).

**Comment by d97hah** [comment]
Hi Russell! Thanks I'll add those tags. (Barika, Kairi should be to two lgs
Barikewa and Kairi and Dugeme is not superfluous as far as I can see.) all
the best, H

Pada tanggal Sen, 18 Jan 2021 pukul 11.00 barlowrussell <
notifications@github.com> menulis:

**Comment by barlowrussell** [comment]
Ah, I see what's going on: Lean has three sources (with the language names "Dugeme", "Barika", and "Mena", respectively), all of which he subsumes under what he calls "Mena". It seems that "Dugeme" and "Mena" are both [ikob1240], and that Barika is [bari1298].  He only has data on the numbers 'one' and 'two' for the "Mena" reference, but he does use this as the name that includes both Mena and Dugeme, so, yes, I think you're right to include entries for both "Mena" and "Dugeme", so that everything is maximally findable. And a [bari1298] tag should then be added fro "Barika". :)

**Comment by d97hah** [comment]
Yep! H

Pada tanggal Rab, 20 Jan 2021 pukul 07.24 barlowrussell <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See:
```
@book{hld:Lean:11,
    author = {Glendon A. Lean},
    title = {Gulf Province},
    publisher = {Port Moresby: Papua New Guinea University of Technology},
    series = {Counting Systems of Papua New Guinea},
    volume = {11},
    year = {1986},
    glottolog_ref_id = {308100},
    hhtype = {overview;minimal},
    inlg = {English [eng]},
    lgcode = {Mena = Ikobi-Mena [meb], Dugeme = Ikobi-Mena [meb], Barika 16 miles NNW from Iesso on the Omati river and 8 miles NE by E from the headwaters of the Omati at a point appx 25 miles from Iesso = probably Barikewa [jbk], Kairi = Rumu [klq], Karima of Johnston 1921 = Franklin's Omati = Mouwase [jmw], Kerewo = Kerewo Kiwai [kxz], Minanibai = Minanibai-Foia Foia [mcv], Morigi = Morigi Kiwai [mdb], North-Eastern Kiwai = Northeast Kiwai [kiw], Arigibi = Kiwai-Northeast [kiw], Podopa = Folopa [ppo], Pawaia [pwa], Ipiko [ipo], Purari = Purari [iar], Ankave [aak], Ivori [ago], Lohiki [miw], Keuru [xeu], Orokolo [oro], Uaripi = Tairuma [uar], Raepa-Tati = Kaki Ae [tbd], Toaripi [tqo], 1-2 in Ikobi, Simbari, Opao, Hamtai (= all Gulf languages as of Wurm and Hattori 1981 except Porome).},
    macro_area = {Papua},
    note = {Draft Edition}
}
```
