### ISSUE TITLE
Halh mongolian (halh1238) is shifting

### ISSUE THREAD

**Issue by yusufymz** [glottolog/glottolog#650]
Hi, Halh Mongolian (halh1238) is the variety of Mongolian spoken in Mongolia by more than 3 million speakers. The reference in the UNESCO is about a dialect Ordos. I dont believe that a language with many speakers and official status in a country should be considered “shifting”.

**Comment by d97hah** [comment]
Thanks I'll fix that for next version! H

Pada tanggal Rab, 3 Feb 2021 pukul 20.43 yusufymz <notifications@github.com>
menulis:

**Comment by xrotwang** [comment]
See
```
$ glottolog show halh1238 | grep endangerment -A 3
INFO    glottolog/glottolog at /home/robert_forkel/projects/glottolog/glottolog
[endangerment]
status = not endangered
source = E24
date = 2021-03-15T20:30:07
```
