### ISSUE TITLE
Borewar has no ID in languages.csv

### ISSUE THREAD

**Issue by martsen79** [glottolog/glottolog#651]
ID for Borewar is currently missing, although it does have a Glottocode.

**Comment by xrotwang** [comment]
Which `languages.csv` is this issue about?

**Comment by martsen79** [comment]
In the csv here: https://github.com/glottolog/glottolog-cldf/blob/master/cldf/languages.csv

**Comment by xrotwang** [comment]
Hm. Cannot confirm:
```shell
$ git checkout v4.3
$ head -n 1 cldf/languages.csv 
ID,Name,Macroarea,Latitude,Longitude,Glottocode,ISO639P3code,Countries,Family_ID,Language_ID
$ grep Borewar cldf/languages.csv 
bore1248,Borewar,Papunesia,,,bore1248,,,lowe1437,bore1247
```

**Comment by martsen79** [comment]
Hmm I cannot reproduce it anymore, either. I'm not sure if it was a blip when I downloaded it. Closing.
