### ISSUE TITLE
Request to add a creole language/dialect: Bungi

### ISSUE THREAD

**Issue by littlejohn657** [glottolog/glottolog#654]
There was a dialect of English that was known as Bungi that spoken by the Scottish Métis of the Red River Settlement in what is now Manitoba, Canada. It was a dialect that was mostly English, but did include words from Indigenous languages and Scottish Gaelic (the people who were responsible for the development of the dialect likely spoke English as a second language, and so brought in some of their own words and syntax). The dialect is now believed to be extinct.

I'm not a linguist, so I am not sure where this should fit into the larger family tree of languages.

I know that Wikipedia is not a reliable source of information, however, I did a major overhaul of the entry last summer, so I am the one that put most of the information into the entry on Wikipedia for Bungi Creole, and the sources from that would be the same sources that I would be providing here.
https://en.wikipedia.org/wiki/Bungi_Creole

**Comment by d97hah** [comment]
Hi! Yes it's the variety in the Blain thesis. I'll add a glottocode for it
in the next version of Glottocode, classified as a sister to Orkney Scots
English (but skimming the data in the Blain thesis makes me wonder if at
least that data is not better called a variety of Canadian English). all
the best, H

Pada tanggal Kam, 18 Feb 2021 pukul 23.00 littlejohn657 <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
See
```
 glottolog tree orca1234
INFO    glottolog/glottolog at /home/robert_forkel/projects/glottolog/glottolog
Indo-European [indo1319]
   └─ Classical Indo-European [clas1257]
      └─ Germanic [germ1287]
         └─ Northwest Germanic [nort3152]
            └─ West Germanic [west2793]
               └─ North Sea Germanic [nort3175]
                  └─ Anglo-Frisian [angl1264]
                     └─ Anglic [angl1265]
                        └─ Later Anglic [late1254]
                           └─ Scots [scot1243]
                              └─ Insular Scots [insu1251]
                                 └─ Orcadian Scots [orca1234]
                                    ├─ Bungee [bung1271]
                                    └─ Orkney Scots [orkn1236]
```
