### ISSUE TITLE
Ati ati

### ISSUE THREAD

**Issue by Angkola** [glottolog/glottolog#677]
Ati ati bahasa melayu sumatera [tenggara ] indonesia suku mandailing dan suku angkola yg bergen ras melayu bergen mungkin gen ?
Anlantik kongo 
https://glottolog.org/resource/languoid/id/atla1278
b10b1234 ( Ubi ) Ati
Bahasa Melayu-Polinesia dituturkan dan berasal dari orang Ati di Panay

Bahasa Ati  Ati (Filipina)
Glottocode:  b10b1234
ttolog
Lawrence A. Reid 1994 
Teks
BibTeX
RIS
MODS
Lawrence A. Reid. 1994. Kemungkinan Elemen Leksikal Non-Austronesia dalam Bahasa Negrito Filipina. Linguistik Kelautan 33. 37-74.

Jenis dokumen
Buku Pegangan / Tinjauan Studi perbandingan-sejarah
Bahasa
Abelen Ayta [ aben1249 ]
Aberlen Ayta = Pilien [ maga1263 ]
Magganchi Ayta [ maga1263 ]
Maggindi Ayta [ magi1241 ]
Ambala Ayta [ amba1267 ]
Magbeken Ayta [ bata1297 ]
Atta [ pamp1244 ]
Central Cagayan Negrito (Agta) [ cent2084 ]
Cagayan Negrito Timur (Agta) [ dupa1235 ]
Arta [ arta1239 ]
Casiguran Dumagat Agta [ casi1235 ]
Alta, Umiray Dumaget Agta [ umir1236 ]
Sinauna [ remo1247 ]
Tayabas Ayta [ taya1256 ]
Abiyan Agta [ cama1250 ]
Iriga Agta [ mtir1235 ]
Rugnot [ mtir1236 ]
Inati [ atii1237 ]
Ata [ ataa1240 ]
Penyedia
Bibliografi Harald Hammarström
hh: hv: Reid: Negrito
Komentar tentang subklasifikasi
Robert Blust 1991 : 80

Endangerment
Status AES:
bergeser
Sumber:
Campbell, Lyle dan Lee, Nala Huiying dan Okura, Eve dan Simpson, Sean dan Ueki, Kaori 2017
Komentar:
Ati (Filipina) (3864-atk) = Terancam (20 persen pasti, berdasarkan bukti yang ada)
Panay Filipiness Glottocode
http://glottolog.org/resource/languoid/id/atii1237
ISO 639-3 atk

Nama alternatif
elcat:
Ati (Filipina)
Bisaya
Inati
lexvo:
Ati [en]
pohon banyak:
A'i
Ari
Ati
Bisaya
Inati
Ati ati
Ati ati bahasa melayu sumatera [tenggara] indonesia suku mandailing dan suku angkola yg bergen ras melayu bergen mungkin gen?
Anlantik kongo
https://glottolog.org/resource/languoid/id/atla1278
b10b1234 (Ubi) Ati
Bahasa Melayu-Polinesia dituturkan dan berasal dari orang Ati di Panay

Bahasa Ati Ati (Filipina)
Glottocode: b10b1234
ttolog
Lawrence A. Reid 1994
Teks
BibTeX
RIS
MODS
Lawrence A. Reid. 1994. Kemungkinan Elemen Leksikal Non-Austronesia dalam Bahasa Negrito Filipina. Linguistik Kelautan 33. 37-74.

Jenis dokumen
Buku Pegangan / tinjauan Studi perbandingan-sejarah
Bahasa
Abelen Ayta [aben1249]
Aberlen Ayta = Pilien [maga1263]
Magganchi Ayta [maga1263]
Maggindi Ayta [magi1241]
Ambala Ayta [amba1267]
Magbeken Ayta [bata1297]
Atta [pamp1244]
Central Cagayan Negrito (Agta) [cent2084]
Cagayan Negrito Timur (Agta) [dupa1235]
Arta [arta1239]
Casiguran Dumagat Agta [casi1235]
Alta, Umiray Dumaget Agta [umir1236]
Sinauna [remo1247]
Tayabas Ayta [taya1256]
Abiyan Agta [cama1250]
Iriga Agta [ mtir1235]
Rugnot [mtir1236]
Inati [atii1237]
Ata [ataa1240]
Penyedia
Bibliografi Harald Hammarström
hh: hv: Reid: Negrito
Komentar tentang subklasifikasi
Robert Blust 1991: 80

Endangerment
Status AES:
bergeser
Sumber:
Campbell, Lyle dan Lee, Nala Huiying dan Okura, Eve dan Simpson, Sean dan Ueki, Kaori 2017
Komentar:
Ati (Filipina) (3864-atk) = Terancam (20 persen pasti, berdasarkan bukti yang ada )
Panay Filipiness Glottocode
http://glottolog.org/resource/languoid/id/atii1237
ISO 639-3 atk

Nama alternatif
elcat:
Ati (Filipina)
Bisaya
Inati
lexvo:
Ati [en]
pohon Banyak:
A'i
Ari
Ati
Bisaya
Inati

**Comment by Angkola** [comment]
Ati ati
Ati ati bahasa melayu sumatera [tenggara] indonesia suku mandailing dan suku angkola yg bergen ras melayu bergen mungkin gen?
Anlantik kongo
https://glottolog.org/resource/languoid/id/atla1278
b10b1234 (Ubi) Ati
Bahasa Melayu-Polinesia dituturkan dan berasal dari orang Ati di Panay

Bahasa Ati Ati (Filipina)
Glottocode: b10b1234
ttolog
Lawrence A. Reid 1994
Teks
BibTeX
RIS
MODS
Lawrence A. Reid. 1994. Kemungkinan Elemen Leksikal Non-Austronesia dalam Bahasa Negrito Filipina. Linguistik Kelautan 33. 37-74.

Jenis dokumen
Buku Pegangan / tinjauan Studi perbandingan-sejarah
Bahasa
Abelen Ayta [aben1249]
Aberlen Ayta = Pilien [maga1263]
Magganchi Ayta [maga1263]
Maggindi Ayta [magi1241]
Ambala Ayta [amba1267]
Magbeken Ayta [bata1297]
Atta [pamp1244]
Central Cagayan Negrito (Agta) [cent2084]
Cagayan Negrito Timur (Agta) [dupa1235]
Arta [arta1239]
Casiguran Dumagat Agta [casi1235]
Alta, Umiray Dumaget Agta [umir1236]
Sinauna [remo1247]
Tayabas Ayta [taya1256]
Abiyan Agta [cama1250]
Iriga Agta [ mtir1235]
Rugnot [mtir1236]
Inati [atii1237]
Ata [ataa1240]
Penyedia
Bibliografi Harald Hammarström
hh: hv: Reid: Negrito
Komentar tentang subklasifikasi
Robert Blust 1991: 80

Endangerment
Status AES:
bergeser
Sumber:
Campbell, Lyle dan Lee, Nala Huiying dan Okura, Eve dan Simpson, Sean dan Ueki, Kaori 2017
Komentar:
Ati (Filipina) (3864-atk) = Terancam (20 persen pasti, berdasarkan bukti yang ada )
Panay Filipiness Glottocode
http://glottolog.org/resource/languoid/id/atii1237
ISO 639-3 atk

Nama alternatif
elcat:
Ati (Filipina)
Bisaya
Inati
lexvo:
Ati [en]
pohon Banyak:
A'i
Ari
Ati
Bisaya
Inati

**Comment by xrotwang** [comment]
duplicate
