### ISSUE TITLE
Wordlist in Yem language

### ISSUE THREAD

**Issue by anaiswion** [glottolog/glottolog#680]
I would like to add some links toward word-lists of the mid-19th c. in omotic and kushitic languages. They had been collected by a French traveller and has never been used. It is online since a few days and I am cataloguing the manuscript. How can I point to this resource ? 
Thanks a lot.

**Comment by d97hah** [comment]
Tell us what the source and link is and we'd include it in  the next
version. all the best, H

Pada tanggal Kam, 8 Apr 2021 pukul 16.10 anaiswion ***@***.***>
menulis:

**Comment by anaiswion** [comment]
Manuscript Ethiopien d'Abbadie 270, folio 51-57v (it is Dawro and Yem) and 67v (Yem only). The link to the folio 51 is here : http://transcrire.huma-num.fr/scripto/13/14131/14237/edit
Then just click on "next" to consult the manuscript. 
There are also wordlists and remarks about of other languages such as Bench, Awiña (Awngi?), and Anywa (Anuak, here called Yambo). Shall I also provide for the corresponding folios ? 
It dates from the 1840s and has been collected by Antoine d'Abbadie.

**Comment by d97hah** [comment]
Thanks, yes, happy for refs to the other wordlists too

Pada tanggal Kam, 8 Apr 2021 pukul 18.01 anaiswion ***@***.***>
menulis:

**Comment by anaiswion** [comment]
Perfect. 
Then for **Yem** I suggest : 
Name : Antoine d'Abbadie
Title : Listes de mots en Dawro et Yamma, ms. BnF Ethiopien Abbadie 270, fol. 51-57v
Year : ca. 1845
Pages : 13
Doctype : wordlist
URL : https://transcrire.huma-num.fr/scripto/13/14131/14237/edit
(end the 12 next pages in the manuscript)

**Comment by anaiswion** [comment]
DAWRO

Name : Antoine d'Abbadie
Title : Listes de mots en Dawro et Yamma, ms. BnF Ethiopien Abbadie 270, fol. 32r, fol. 44v, fol. 51-57, fol. 67, fol. 69v-70v
Year : ca. 1845
Pages : 18
Doctype : wordlist
URL : https://transcrire.huma-num.fr/scripto/13/14131/media

**Comment by anaiswion** [comment]
BENCH

Name : Antoine d'Abbadie
Title : Notes sur la langue bench (gimira), ms. BnF Ethiopien Abbadie 270, fol. 57v, 68-69v
Year : ca. 1845
Pages : 5
Doctype : wordlist
URL : https://transcrire.huma-num.fr/scripto/13/14131/media

**Comment by anaiswion** [comment]
SIDAAMA

Name : Antoine d'Abbadie
Title : onomastic list, ms. BnF Ethiopien Abbadie 270, fol. 57v, 67v
Year : ca. 1845
Pages : 2
Doctype : minimal
URL : https://transcrire.huma-num.fr/scripto/13/14131/media

**Comment by anaiswion** [comment]
ANYWA

Name : Antoine d'Abbadie
Title : liste de mots, ms. BnF Ethiopien Abbadie 270, fol. 58r-64v
Year : ca. 1845
Pages : 14
Doctype : wordlist
URL : https://transcrire.huma-num.fr/scripto/13/14131/media

**Comment by anaiswion** [comment]
AWNGI

Name : Antoine d'Abbadie
Title : liste de mots, ms. BnF Ethiopien Abbadie 270, fol. 66rv, 69v, 72-77v
Year : ca. 1845
Pages : 15
Doctype : wordlist
URL : https://transcrire.huma-num.fr/scripto/13/14131/media

**Comment by anaiswion** [comment]
Thanks !

**Comment by d97hah** [comment]
Thanks! H

Pada tanggal Jum, 9 Apr 2021 pukul 14.22 anaiswion ***@***.***>
menulis:

**Comment by xrotwang** [comment]
See
```
$ grep "Abbadie" references/bibtex/hh.bib 
@article{e:dAbbadie:Kafa,
    author = {d'Abbadie, Antoine [Thompson]},
@article{hv:Abbadie:Ethiopiennes,
    author = {d'Abbadie, Antoine},
@article{w:Abbadie:Kam,
    author = {d'Abbadie, Antoine},
@article{w:Abbadie:Saho,
    author = {d'Abbadie, Antoine},
@misc{w:dAbbadie:Anywa,
    author = {d'Abbadie, Antoine},
    title = {Liste de mots, ms. BnF Ethiopien Abbadie 270, fol. 58r-64v},
@misc{w:dAbbadie:Awngi,
    author = {d'Abbadie, Antoine},
    title = {Liste de mots, ms. BnF Ethiopien Abbadie 270, fol. 66rv, 69v, 72-77v},
@misc{w:dAbbadie:Bench,
    author = {d'Abbadie, Antoine},
    title = {Notes sur la langue bench (gimira), ms. BnF Ethiopien Abbadie 270, fol. 57v, 68-69v},
@misc{w:dAbbadie:Dawro,
    author = {d'Abbadie, Antoine},
    title = {Listes de mots en Dawro et Yamma, ms. BnF Ethiopien Abbadie 270, fol. 32r, fol. 44v, fol. 51-57, fol. 67, fol. 69v-70v},
@misc{ld:dAbbadie:Sidaama,
    author = {d'Abbadie, Antoine},
    title = {Onomastic list, ms. BnF Ethiopien Abbadie 270, fol. 57v, 67v},
@misc{w:dAbbadie:Yamma,
    author = {d'Abbadie, Antoine},
    title = {Listes de mots en Dawro et Yamma, ms. BnF Ethiopien Abbadie 270, fol. 51-57v},
```
