### ISSUE TITLE
nonu1241 is linked wrongly to Chile - it should be Colombia [CO] and Peru [PE]

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#683]
https://glottolog.org/resource/languoid/id/nonu1241

**Comment by d97hah** [comment]
Thanks this will go away in the next Glottolog edition

Pada tanggal Rab, 14 Apr 2021 pukul 18.02 Hans-Jörg Bibiko <
***@***.***> menulis:

**Comment by xrotwang** [comment]
Maybe not:
https://github.com/glottolog/glottolog/blob/ea763abd75e6aa333e666a0645ab3c4c3bf460d0/languoids/tree/huit1251/nonu1240/nonu1241/md.ini#L11-L12

**Comment by d97hah** [comment]
Indeed, turns out there was some systematicity to that error, now fixed
with latest PR

Pada tanggal Rab, 14 Apr 2021 pukul 18.15 Robert Forkel <
***@***.***> menulis:
