### ISSUE TITLE
zial1235 - one should consider to add Guinea [GN] as country (or only [GN])

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#686]
acc. to Kirill Babaev 2010, Ms. Daria Mishchenko, St. Peter State University

**Comment by d97hah** [comment]
Yes, thanks, already fixed for next version! H

Pada tanggal Kam, 15 Apr 2021 pukul 08.21 Hans-Jörg Bibiko <
***@***.***> menulis:
