### ISSUE TITLE
dadu1237 geo coordinates + alternate name suggestion

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#687]
Acc. to https://catalog.paradisec.org.au/collections/VD1/items/dadua20140218_01 and to Mr. David Penn, PhD Student, Linguistics, University of New England, Australia. September 19, 2012: "[...] It is spoken on the north coast of mainland Timor Leste, in the Ilimano area of Manatuto district. This is about 40km east of the Timorese capital, Dili. [...]" and to https://commons.wikimedia.org/wiki/File:Dadua.png  I would suggest to set the coordinates to lat/long -8.486,125.8637 ( https://www.openstreetmap.org/search?query=-8.4860%2C125.8637#map=13/-8.4860/125.8638 ).

In addition Mr. David Penn and J. Patrick Fischer wrote the language name as: Dadu'a

**Comment by d97hah** [comment]
Thanks I'll adjust accordingly! H

Pada tanggal Kam, 15 Apr 2021 pukul 09.23 Hans-Jörg Bibiko <
***@***.***> menulis:

**Comment by xrotwang** [comment]
See
```
$ glottolog show dadu1237
INFO    glottolog/glottolog at /home/robert_forkel/projects/glottolog/glottolog

Glottolog languoid dadu1237

Classification:
Austronesian [aust1307]
   └─ Malayo-Polynesian [mala1545]
      └─ Central-Eastern Malayo-Polynesian [cent2237]
         └─ Central Malayo-Polynesian [cent2245]
            └─ Timoric A [timo1259]
               └─ Northern Timoric A [nort3194]
                  └─ Wetar [weta1245]
                     └─ Ili'uun [iliu1237]
                        └─ Dadu'a [dadu1237]

Info:
Path: /home/robert_forkel/projects/glottolog/glottolog/languoids/tree/aust1307/mala1545/cent2237/cent2245/timo1259/nort3194/weta1245/iliu1237/dadu1237/md.ini
[core]
name = Dadu'a
level = dialect
latitude = -8.486
longitude = 125.8637
macroareas = 
	Papunesia
countries = 

[altnames]
multitree = 
	Dadua
glottolog = 
	Dadua
```
