### ISSUE TITLE
toki1238 geo coordinates: 42.5727 E, 46.3724 N

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#688]
acc. to https://ru.wikipedia.org/wiki/Каратинский_язык and https://minlang.iling-ran.ru/lang/tukitinskiy-yazyk the dialect Tokita is spoken in the Тукита (Tukita) village [near village Karata]

see: https://www.openstreetmap.org/search?query=42.5727%2C%2046.3724#map=15/42.5727/46.3724

In addition, acc. to http://lingvarium.org/publications/caucas/ACL-N_Cau.pdf and others and to the fact that in Russian this dialect is spelled as tukitin-skij (from village name Tukita -> Tukit-in [-in = belonging to]) one could add `Tukitin` as additional alternate name.

**Comment by d97hah** [comment]
Thanks H-J I've made the additions accordingly in a new PR
https://github.com/glottolog/glottolog/pull/691

Pada tanggal Jum, 16 Apr 2021 pukul 14.55 Hans-Jörg Bibiko <
***@***.***> menulis:
