### ISSUE TITLE
bana1307 geo coordinates: -6.741 S, -64.89624 E

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#692]
acc. to https://terrasindigenas.org.br/pt-br/terras-indigenas/3936 and http://endangeredlanguages.com/lang/1792

alternate names:
- Banawá Yafí
- Kitiya
- Banivá
- Baniwá-Jafí

countries:
BR

Links:
- `[Banawá](http://endangeredlanguages.com/lang/1792)`
- `[Banawá](https://terrasindigenas.org.br/pt-br/terras-indigenas/3936)`

**Comment by d97hah** [comment]
Thanks HJ I've added these additions to the tukita PR

Pada tanggal Jum, 16 Apr 2021 pukul 16.35 Hans-Jörg Bibiko <
***@***.***> menulis:
