### ISSUE TITLE
bang1335 geo coordinates: 29.8692 N, 79.0686 W

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#693]
links: `[Bangani](http://www.endangeredlanguages.com/lang/1588)`

alternate names:
- Bangaani
- बंगाणी
- baṅgāṇī

country:
India (IN)

**Comment by d97hah** [comment]
Thanks I've added this info NB: longitude must be 79.0686 E, not 79.0686 W

Pada tanggal Sab, 17 Apr 2021 pukul 11.24 Hans-Jörg Bibiko <
***@***.***> menulis:

**Comment by xflr6** [comment]
Thanks Harald.

Can you try to re-base 2a67c982c8c6e4d5f09560c2d61c52df8a2888f0 on 162d1626497635dd70841dbd17bb57ab15f50451 in master (or just re-apply the changes to master and use a new branch name)?

Left a comment on 2a67c982c8c6e4d5f09560c2d61c52df8a2888f0 (name order).

**Comment by xflr6** [comment]
Note that 2a67c982c8c6e4d5f09560c2d61c52df8a2888f0 is based on 9a16a4be5818d8979791c0d2590a144b866a4e17 instead of 092720c4dcc597215c882a53773f649af8bb4da8 (which is the commit that merged to master).

**Comment by d97hah** [comment]
I am not sure what you mean, afaik someone else than me should approve the
tukita branch into master...

Pada tanggal Sab, 17 Apr 2021 pukul 16.40 Sebastian Bank <
***@***.***> menulis:

**Comment by xflr6** [comment]
AFAIU, you might have merged PR 688 via the web UI and then forgot to pull the new `master`, so the commit here still uses your local orphaned commit from 15:.. instead of the one from 16:.. here:

![screen](https://user-images.githubusercontent.com/6342379/115119828-ad8eb680-9faa-11eb-85de-bcec6089ef55.PNG)

If you prefer, I can try to do the re-base and force-push here (this one is also missing the 'remove duplicate field'.

**Comment by xflr6** [comment]
See #695

**Comment by d97hah** [comment]
Yes I was probably already working on the 'tokita' branch when "fix typos
in hh.bib keys" appeared and I merged it. It should have no conflict with
tokita so little reason to pull "fix typos in hh.bib keys" into tokita.
Isn't the desired ord of business that you or robert merge tokita in such a
case?

Pada tanggal Sab, 17 Apr 2021 pukul 18.33 Sebastian Bank <
***@***.***> menulis:

**Comment by xflr6** [comment]
Hm, I think the merge of 'fix typos' was fine, also the merge of 'Added coordinates' to `master`: the conflict seems to be between Roberts and my commit after that above and the 693 on `tukita`.

> Isn't the desired ord of business that you or robert merge tokita in such a case?

The PR for the branch is conflicting, so cannot be merged without resolving conflicts:

![screen](https://user-images.githubusercontent.com/6342379/115124048-7b884f00-9fc0-11eb-97b0-de057673acfb.PNG)

Closing this PR in favour of merged #695.
