### ISSUE TITLE
missing glottocode for Fuyu Kyrgyz ?

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#701]
- names: Fuyu Kyrgyz, Fuyü Gïrgïs, Fu-Yu Kirgiz or Manchurian Kirghiz
- 'iso-code': kjh-fyk
- (?) maybe follows under https://glottolog.org/resource/languoid/id/yeni1251 or maybe as dialect under https://glottolog.org/resource/languoid/id/khak1248
- sources:
- - https://en.wikipedia.org/wiki/Fuyu_Kyrgyz
- - http://endangeredlanguages.com/lang/3383
- - http://multitree.org/codes/kjh-fyk
- - https://www.wikidata.org/wiki/Q2598963

**Note** WALS-Code [kfy](https://wals.info/languoid/lect/wals_code_kfy) is probably **not correctly** linked to kirg1245 (Kirghiz) since Kirghiz (Fu-Yu) is not a variety to Kirghiz.

**Comment by d97hah** [comment]
I'll add it (dialect of Khakas) in a separate PR

Pada tanggal Sen, 19 Apr 2021 pukul 17.22 Hans-Jörg Bibiko <
***@***.***> menulis:

**Comment by xrotwang** [comment]
See
```
└─ Khakas [khak1248]
                     ├─ Beltir [belt1239]
                     ├─ Fuyu Kirghiz [fuyu1243]
                     ├─ Kacha [kach1278]
                     ├─ Kamassian (Turkic) [kama1354]
                     ├─ Kyzyl [kyzy1244]
                     └─ Sagai [saga1260]
```
