### ISSUE TITLE
request to add code for Azamgarhi variety 

### ISSUE THREAD

**Issue by quail4sale** [glottolog/glottolog#704]
Azamgarhi is spoken in the Azamgarh region (Azamgarh and Mau districts) and adjoining areas of Jaunpur district, Purvanchal Uttar Pradesh by Muslims. Alternate names include: Musalman Bhasa, Musalman Boli, Dehati, Bhaiya, Bhasha

Unfortunately, literature specific to Azamgarhi is very, very scarce. Here are two references to Azamgarhi I found:
- [https://www.academia.edu/45387787/A_PRELIMINARY_DESCRIPTION_OF_THE_AZAMGARHI_LANGUAGE] by Maaz Shaikh
- Linguistic Survey of India (Grierson, 1904) Volume 6, page 9, in which Grierson identifies a 'Musalman dialect' of Awadhi 

Maaz Shaikh is is the process of finishing his M.Phil now, which will provide more information on this variety. Though the status of Azamgarhi as a language is under investigation still, we are requesting for the variety to be acknowledged with a Glottocode to be able to properly identify it for archiving. 
-Mary

**Comment by d97hah** [comment]
Hi! The eastern reaches of Awadhi in comparison with other Awadhis has been
covered by Saksena's Evolution of Awadhi which makes no special
delimitation of Azamgar. Yet for whatever it's worth I've enriched the
named lects of Awadhi for next Glottolog update including Azamgarhi (of
Eastern Awadhi) whose glottocode will be azam1234. NB Amhad 1986 AFAICT is
an extensive description of a Muslim lect of Awadhi in SW Azamgar.

Ahmad, Suhail. (1986) A descriptive analysis of Eastern Awadhi dialect of
Jaunpur. Aligarh: Aligarh Muslim University doctoral dissertation.
xii+255pp.

Pada tanggal Sel, 20 Apr 2021 pukul 23.26 quail4sale <
***@***.***> menulis:

**Comment by quail4sale** [comment]
Thanks so much for the prompt reply, and for the reference. I appreciate it!
Mary

**Comment by xrotwang** [comment]
Glottocode ended up being "azam1235": https://github.com/glottolog/glottolog/blob/master/languoids/tree/indo1319/clas1257/indo1320/indo1321/indo1322/subc1234/east2726/awad1245/awad1243/east2875/azam1235/md.ini
