### ISSUE TITLE
Zadjali lect

### ISSUE THREAD

**Issue by aryamanarora** [glottolog/glottolog#705]
Could the Zadjali language be added? Little documentation of it so far, just [Al Jahdhami (2017)](http://www.ijllnet.com/journals/Vol_4_No_3_September_2017/6.pdf) which is a wordlist comparing the language to Sindhi and Balochi. There is a short ethnographic description of the tribe in [Lorimer (1908: 891)](https://www.google.com/books/edition/Gazetteer_of_the_Persian_Gulf_Om%C4%81n_and/Z4QYAQAAMAAJ?hl=en&gbpv=1&dq=Jadg%C4%81l+tribe+lorimer&pg=PA891&printsec=frontcover) which gives the names Jadgāl and Zidjāl (an Arabicised equivalent) and equates them to the Jadgals of Iran.

Given this limited data, it is probably closely related to (if not a variety of) Jadgali (jadg1238 in Glottolog). But since we don't have adequate linguistic descriptions of either language I'd suggest putting it as a sister lect to Jadgali for now.

I'd put the coordinates for it on Muscat, Oman.

Here is the BibTeX for the first source:
```bibtex
@article{AlJahdhami,
    title={Zadjali: The Dying Language},
    author={Al Jahdhami, Said},
    journal={International Journal of Language and Linguistics},
    volume={4},
    number={3},
    year={2017},
    hhtype={wordlist},
    inlg={English [eng]},
    macro_area={Eurasia},
}
```

**Comment by aryamanarora** [comment]
Relatedly, I manage a reference list for South Asian languages (https://aryamanarora.github.io/bhasacitra/). Would a BibTeX'd version of this be useful for incorporating into Glottolog?

**Comment by d97hah** [comment]
The ref in question is already in the repos. I've also filed it as Jadgali
for similar reasons. In the face of ignorance, splitting the two into
sister lects is not a better solution (applying such a principle throughout
would blow up the system). There's also the other expatriate lects Luwati,
Kholosi, Kachhi etc which need to be considered for the classification. all
the best, H

Pada tanggal Sel, 20 Apr 2021 pukul 23.26 Aryaman Arora <
***@***.***> menulis:

**Comment by aryamanarora** [comment]
Ah okay, did not see it in the current version online.

I have an additional reference for Kholosi, a short (for now) dictionary I am updating with the help of my informant. I will be publishing more work on it this year based on my fieldwork (namely, on phonetics/phonology and comparative classification). For now, I highly suggest placing it directly under Sindhic (sind1279).

```bibtex
@book{kholosidict,
    title={Kholosi Dictionary}
    author={Arora, Aryaman and Etebari, Ahmed},
    year={2021},
    doi={10.13140/RG.2.2.35551.79524},
    hhtype={dictionary},
    inlg={English [eng]},
    macro_area={Eurasia},
}

**Comment by d97hah** [comment]
Thanks I'll add that reference. I don't understand how you can highly
suggest placing it directly under Sindhic. That would imply it has no
closer relation with any of the other Sindhic languages, which I am
assuming you don't know because you haven't compared it with Kachhi,
Luwati, Zandjali etc for lack of adequate data on them. all the best, H

Pada tanggal Rab, 21 Apr 2021 pukul 06.14 Aryaman Arora <
***@***.***> menulis:
