### ISSUE TITLE
References linked to wrong language

### ISSUE THREAD

**Issue by joeylovestrand** [glottolog/glottolog#707]
The work of Michka Sachnine: 

https://glottolog.org/resource/reference/id/45023
https://glottolog.org/resource/reference/id/104306
https://glottolog.org/resource/reference/id/39949
https://glottolog.org/resource/reference/id/108656
https://glottolog.org/resource/reference/id/74773
https://glottolog.org/resource/reference/id/536969
https://glottolog.org/resource/reference/id/88228
https://glottolog.org/resource/reference/id/472211
https://glottolog.org/resource/reference/id/129856

are about a dialect of Herdé [1236] not Pévé [peve1243]

**Comment by d97hah** [comment]
Thanks yes I'll fix that for next version! H

Pada tanggal Sen, 26 Apr 2021 pukul 16.00 joeylovestrand <
***@***.***> menulis:
