### ISSUE TITLE
new glottocodes for Kannada varieties?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#708]
There are differences between written and colloquial Kannada such that they could be coded separately in Grambank  (Sridhar 1990: 219-226). Is there any change we could have two dialect level glottocodes for "Written Kannada" and "Colloquial Kannada" made?

**Comment by d97hah** [comment]
Ok I've enriched the Kannada dialect inventory somewhat
https://github.com/glottolog/glottolog/pull/709 which should cover the case
of Sridhar 1990

Pada tanggal Rab, 28 Apr 2021 pukul 16.53 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Cool, tack!

There are other changes in the diff file that I don't fully follow (various changes to Chadic bibtex etc.).

I see that stan1328 = Standard Literary Kannada. Am I to match Northern Kannada [nort3390] to Sridhars "Kumta variety, spoken in the North Ganara area"?

**Comment by d97hah** [comment]
The location of Kumta rather suggests a Western Kannada dialect

Pada tanggal Kam, 29 Apr 2021 pukul 14.14 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
@d97hah Okay. This isn't really my area of expertise so I appreciate guidance. Which precise dialect in glottolog would you match it to?

**Comment by HedvigS** [comment]
Mangalore Kannada [mang1438]?

**Comment by d97hah** [comment]
Not my area of expertise either but yes M Kannada would be the closest
match I suspect

Pada tanggal Kam, 29 Apr 2021 pukul 14.59 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Okay, we'll go with that. Tack tack.
