### ISSUE TITLE
Missing glottocode for ISO639-3 code nxk language 'Koki Naga' in Myanmar 

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#710]
https://iso639-3.sil.org/code/nxk
https://en.wikipedia.org/wiki/Koki_language
http://www.multitree.org/codes/nxk.html

**Comment by d97hah** [comment]
Hi HJ! I've delayed decision on this one because the change request is
based on a report that is still not published or otherwise available. all
the best, H

Pada tanggal Kam, 29 Apr 2021 pukul 13.57 Hans-Jörg Bibiko <
***@***.***> menulis:
