### ISSUE TITLE
Add info about curation policies for bibfiles

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#715]
Here:
https://github.com/glottolog/glottolog/blob/master/references/BIBFILES.ini

**Comment by HedvigS** [comment]
I was just trying to figure out if I could add articles to the wiki of glottolog/glottolog about this, since that's apparently where other instructions about amending language names are. Is that a thing?

**Comment by HedvigS** [comment]
I can't really seem to fork the wiki, at least I haven't figured out yet how to. I can clone it, and I made a stub article about curating references. But, I can't make branches and I can't fork it so I can't make a PR.

Oh well.

[Ammending_references.md](https://github.com/glottolog/glottolog/files/6468420/Ammending_references.md)

**Comment by HedvigS** [comment]
Haha![ I can make a wiki in my glottolog/glottolog fork!](https://github.com/HedvigS/glottolog/wiki)

**Comment by xrotwang** [comment]
@HedvigS you don't have write permissions on glottolog/glottolog, thus you can't add wiki pages.

FWIW I just disabled the wiki for this repos entirely. The one page it had was from 2017, and we don't really use the wiki - also because GitHub wikis are not very functional, e.g. don't allow PR-based workflows.

**Comment by HedvigS** [comment]
Right, I know that but I thought that I could make PRs from a fork still, but turns out that's not possible. So, nevermind.

Okay. For instructions on how to make requests for changes or other details about glottolog - where is the place one should turn?

**Comment by xrotwang** [comment]
We don't have instructions on that other than "open issues" or "send us an email" - see https://glottolog.org/meta/contact

If you are planning on adding to or editing hh.bib substantially, I'd recommend letting @d97hah know, before you start.

**Comment by HedvigS** [comment]
Okay. So the content on the wiki isn't replaced by something else.

**Comment by xrotwang** [comment]
There wasn't really much content in the wiki, other than a couple of
screenshots about suggesting a change of a languoid name. This page was
there for 4 years, and in that time we didn't get many such PRs. We did get
issues and email about languoid names, though. So I think not much is lost
and our feedback channels are somewhat functioning.

Hedvig Skirgård ***@***.***> schrieb am Do., 13. Mai 2021,
15:22:

**Comment by HedvigS** [comment]
Okay! I didn't know about this wiki until now, and I don't think it was advertised on the web page so it's no surprise it wasn't used.

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/blob/6e5834a31cbe21d47a879cdcd70f563120a39df2/references/BIBFILES.ini#L16 for example
