### ISSUE TITLE
Location of Twana

### ISSUE THREAD

**Issue by davidainman** [glottolog/glottolog#717]
I was using this data for other purposes and I saw that the Twana language looks to be in the wrong location. My understanding is that the Twana people were historically mostly along the Hood Canal in the Kitsap Peninsula, while their current geocoordinates put them east of Seattle on the mainland, close to the Nooksack. Can you see where this data came from and if it is incorrectly located?

**Comment by d97hah** [comment]
Indeed it should be on the Hood Canal, I'll change it
to (-123.21227062866376, 47.48951615492443) for next version. all the best,
H

Pada tanggal Sen, 17 Mei 2021 pukul 15.21 davidainman <
***@***.***> menulis:

**Comment by xrotwang** [comment]
```diff
$ git diff 4808e2088939c84b0f6063965dbe944798fa8e11..HEAD languoids/tree/sali1255/coas1325/cent2129/twan1247/md.ini
diff --git a/languoids/tree/sali1255/coas1325/cent2129/twan1247/md.ini b/languoids/tree/sali1255/coas1325/cent2129/twan1247/md.ini
index ce479815ce..d15df4c426 100644
--- a/languoids/tree/sali1255/coas1325/cent2129/twan1247/md.ini
+++ b/languoids/tree/sali1255/coas1325/cent2129/twan1247/md.ini
@@ -4,8 +4,8 @@ name = Twana
 hid = twa
 level = language
 iso639-3 = twa
-latitude = 47.7419
-longitude = -121.765
+latitude = 47.48952
+longitude = -123.21227
 macroareas = 
        North America
 countries = 
```
