### ISSUE TITLE
suru1257 disappeared during update from v4.3 to v4.4

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#719]
Glottocode `suru1257` Suruviri diaclect of `ashk1246` (Ashkun) disappeared without bookkeeping note - Intention or error?

**Comment by xrotwang** [comment]
Only language-level languoids are moved to bookkeeping upon retirement.

Hans-Jörg Bibiko ***@***.***> schrieb am Do., 20. Mai 2021,
13:52:

**Comment by xrotwang** [comment]
For some reason, the archive of retired languoids for version 4.3 wasn't updated properly on the server. It now is, so https://glottolog.org/resource/languoid/id/suru1257 should lead you to a page, where you can see the previous classification for suru1257, and thus decide what to replace this glottocode with - e.g. looking up the parent language https://glottolog.org/resource/languoid/id/ashk1246 in the current version, to see whether any of the remaining dialects fit - or assign the language-level glottocode to your data.

**Comment by Bibiko** [comment]
👍

**Comment by d97hah** [comment]
Suruviri was an erroneous rendering of an alternative name
for Sanu-Gramsena [gram1239] (see a text by Jakob Halfmann). all the best,
H

Pada tanggal Kam, 20 Mei 2021 pukul 15.45 Hans-Jörg Bibiko <
***@***.***> menulis:
