### ISSUE TITLE
Nias dialect identifiers please

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#720]
One of our grambank coders is coding Nias and there are features where dialects vary and these are described as "northern" and "southern", so we'd like to petition for dialect glottocodes.

Our suggestion:

* Nias [nias1242]
  * Nias Utara (Northern Nias)
     * probably where 'nucl1464 Nuclear Nias' should be
   * (Optional, there is a dialect labelled "Central Nias" which is mentioned in descriptions but not described itself.)
  * Nias Selatan (Southern Nias)
     * Batu (Indonesia) [batu1257]

**Comment by d97hah** [comment]
Ok you got it nucl1464 for Nias Utara and batu1257 for Nias Selatan and a
new one for Central Nias

https://github.com/glottolog/glottolog/pull/new/may2021

Pada tanggal Rab, 26 Mei 2021 pukul 15.39 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Much obliged.
