### ISSUE TITLE
Northwestern/southwestern Minyag

### ISSUE THREAD

**Issue by moxie2motion** [glottolog/glottolog#728]
This is not a recognized distinction within Western Minyag. Suggest either a) removing the "western" from the name or b) removing altogether in favor of awaiting more detailed descriptions of regional differences (as these might include 3-4 varieties instead of 2). All are mutually intelligible.

**Comment by d97hah** [comment]
This is from Bai 2019, the names with the "Western" seem better than
without, since they are Western and there is a Western Minyag language in
contrast to an Eastern one. all the best, H

Pada tanggal Sen, 7 Jun 2021 pukul 06.32 moxie2motion <
***@***.***> menulis:

**Comment by moxie2motion** [comment]
But by this measure there would actually need to be a "northwestern", "southwestern" and also a "westwestern" if it were that fine-grained there are three recognizable regional variants within Western Minyag. But all of these variants are mutually intelligible with only one major point of phonological divergence and only minor lexical differences.

**Comment by d97hah** [comment]
What you say is not consistent with Bai 2019, can you disclose the source
of your information?

Pada tanggal Sen, 7 Jun 2021 pukul 09.57 moxie2motion <
***@***.***> menulis:

**Comment by moxie2motion** [comment]
Materials available through https://www.elararchive.org/dk0539

**Comment by d97hah** [comment]
Thanks, could you also point me to the specific place where there is
dialect information and/or explain what's wrong with Bai (2019)'s
information?

Pada tanggal Rab, 9 Jun 2021 pukul 12.39 moxie2motion <
***@***.***> menulis:

> Materials available through https://www.elararchive.org/dk0539
>

**Comment by moxie2motion** [comment]
Hard to point to a specific place since the deposit includes recordings
from across the Western Minyag speaking area. I'm the author of the deposit
and I suppose you could reference my M.A. thesis as the source for my
statements (also included in the deposit) but it is written in a less
commonly used language (Tibetan). Perhaps it's pedantic, but the entire
Western Minyag speaking area exhibits a very high degree of
intelligibility. The most noticeable differences are indeed those between
the comparatively conservative southern variant and a comparatively
innovative northern variant. However, there is also a syntactically unique
variant spoken in the west of the speaking area which has not received
focus or attention in the current literature. I guess my point is that
among the people working on Minyag, I am not aware of a widely accepted
convention of referring to these regional differences as "northwestern" and
"southwestern", but rather as "northern variety/southern variety". Once
more research becomes available on the aforementioned western variety, it
may very well require an in-elegant name like "westwestern". Hence my
suggestion of either removing the "western" from the name or simply
awaiting further description.

Many thanks!
Agnes

**Comment by d97hah** [comment]
Thanks for the reply. If there is just deposits of raw data from different
locations but no summary of the dialectal situation (and still none that
explains what's wrong with Bai 2019) then I don't really want to follow it.
Better to wait for you to write up the dialectal situation and only then
follow it. I still think the names that include Western are better than the
ones without. The naming conventions within the Minyakology community may
be different but the Minyakology field does not need a global perspective
on naming, which Glottolog does. For west-western, whenever it is
established, there are other options (like Far Western) if west-western is
not elegant enough. all the best, H

Pada tanggal Jum, 23 Jul 2021 pukul 04.06 moxie2motion <
***@***.***> menulis:

> Hard to point to a specific place since the deposit includes recordings
> from across the Western Minyag speaking area. I'm the author of the deposit
> and I suppose you could reference my M.A. thesis as the source for my
> statements (also included in the deposit) but it is written in a less
> commonly used language (Tibetan). Perhaps it's pedantic, but the entire
> Western Minyag speaking area exhibits a very high degree of
> intelligibility. The most noticeable differences are indeed those between
> the comparatively conservative southern variant and a comparatively
> innovative northern variant. However, there is also a syntactically unique
> variant spoken in the west of the speaking area which has not received
> focus or attention in the current literature. I guess my point is that
> among the people working on Minyag, I am not aware of a widely accepted
> convention of referring to these regional differences as "northwestern" and
> "southwestern", but rather as "northern variety/southern variety". Once
> more research becomes available on the aforementioned western variety, it
> may very well require an in-elegant name like "westwestern". Hence my
> suggestion of either removing the "western" from the name or simply
> awaiting further description.
>
> Many thanks!
> Agnes
>
