### ISSUE TITLE
Is Zemba 2015 about Nsenga or Chikunda

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#733]
In the Grambank project we aren't sure if this ref:

Mercy Zemba. 2015. A grammatical sketch of Kunda language. (MA thesis, University of Zambia; xviii+143pp.)

is really about [nsen1242] or actually about [kunda1255]. Zemba (2015:3) states that Kunda is N42 (which is kund1255). The current glottolog tag is nsen1242

**Comment by d97hah** [comment]
It's not Chikunda kund1255, neither location, name or data-wise. The
location matches what other sources call Kunda. This variety is (in other
sources) closest to Nsenga. The data (at least the numerals) in Zemba 2015
look more like Bemba though, which another lg close to Kunda (as described
in other sources), but Nsenga is closer according to those other sources.
Kunda in Zemba 2015 could potentially be a different language from Nsenga
(but still in the Sabi subgroup, and not the same as Chikunda kund1255).
It's not clear what N42
meant to Guthrie, if you know, let me know. all the best, H

Pada tanggal Kam, 1 Jul 2021 pukul 16.58 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Sounds like you've got it under control, we'll follow your lead.
