### ISSUE TITLE
Errors for Tho language references

### ISSUE THREAD

**Issue by pamputt** [glottolog/glottolog#740]
Hello, I am not sure this is the right place to report but anyway, there is an error in the references given on the [Tho language page](https://glottolog.org/resource/languoid/id/thoo1240). Indeed, from [SIL](https://www.sil.org/resources/archives/2878), the reference Day, I. Jean and Day, A. Colin. 2002. Thô̌-Vietnamese-English dictionary. Hanoi: SIL. 99pp. is about the [Tày language](https://glottolog.org/resource/languoid/id/tayy1238) (ISO 639-3 code "tyz"). Inaddition, the date should be 1961, not 2002.

**Comment by d97hah** [comment]
Thanks, I'll fix that for next version! H

Pada tanggal Sel, 10 Agu 2021 pukul 11.07 pamputt ***@***.***>
menulis:
