### ISSUE TITLE
How to contribute references?

### ISSUE THREAD

**Issue by dwhieb** [glottolog/glottolog#745]
I'd like to contribute a few additional references for a language I work with, but it wasn't clear to me what the proper pathway is for doing this. A "Submit Additional References" button would be useful.

In the meantime, how can I go about submitting references for addition to the database?

**Comment by d97hah** [comment]
If it's just a few references, just email them to us or the like (bibtex
preferred). If it's a larger amount, we can make a dedicated section, in
this case, also just send a bibtex file by email. all the best, H

Pada tanggal Jum, 3 Sep 2021 pukul 20.38 Daniel W. Hieber <
***@***.***> menulis:

**Comment by xrotwang** [comment]
https://github.com/glottolog/glottolog/blob/master/CONTRIBUTING.md#adding-references
