### ISSUE TITLE
add alternative names to hung1276

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#752]
add these additional names to Hungworo:

Ca̱hungwa̱rya̱
Cahungwarya
reference: https://iso639-3.sil.org/code/nat

Huŋgwəryə
reference: https://en.wikipedia.org/wiki/Hungworo_language

Ungwai
ũngwāī
reference: Blench, Roger (2012). "The Kainji languages of northwestern and central Nigeria" (PDF). Cambridge: Kay Williamson Educational Foundation.

**Comment by d97hah** [comment]
See https://github.com/glottolog/glottolog/pull/754

Pada tanggal Rab, 15 Sep 2021 pukul 12.47 Robert Forkel <
***@***.***> menulis:
