### ISSUE TITLE
change name of sout2989 to "Enxet Sur" and nort2971 "Enlhet Norte"

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#756]
Based on expertise from John Elliott (who wrote a dissertation on sout2989), the more appropriate names for sout2989 and nort2971 are  "Enxet Sur" and "Enlhet Norte" respectively. This is more in line with current literature and the Paraguay government policies.

In addition, it would be better to refer to toba1268 as "Toba-Enenlhet", on the same grounds. He also noted that guan1268 should be "Guaná (Paraguay)".

**Comment by d97hah** [comment]
I'll implement those name changes. all the best, H

Pada tanggal Sen, 20 Sep 2021 pukul 08.11 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Tack!
