### ISSUE TITLE
New dialects for gula1266

### ISSUE THREAD

**Issue by DanielAuerX** [glottolog/glottolog#762]
Hey, 
I am coding gula1266 for Grambank. Since the dialects differ quite significantly from each other, I wanted to split up the coding. The main source, Nougayrol (1999), provides information on a handful of dialects for which I would create sheets. However, some of these dialects are not listed in Glottolog:

![Screenshot 2021-10-20 at 10 00 43](https://user-images.githubusercontent.com/72256996/138052589-a1dbd081-1302-4f5a-8ec2-c44ebcb236e9.png)

I would need glottocodes for the dialects "Koto" and "ɓuɓu". Nougayrol mentions more dialects, but does not provide data (which is relevant for GB at least).

Thanks for your help and let me know if you need more information.

**Comment by xrotwang** [comment]
see https://github.com/glottolog/glottolog/commit/80ab3e6bac838a20ecc4e183d1271b3f3fc04fc0
```
               └─ Gula (Central African Republic) [gula1266]
                  ├─ Kotoic Gula [gula1267]
                  │  ├─ Bubu Gula [bubu1235]
                  │  ├─ Koto Gula [koto1271]
                  │  ├─ Koyo Gula [koyo1246]
                  │  ├─ Ngulu Gula [ngur1264]
                  │  └─ Zura [zura1238]
                  ├─ Mereic Gula [mere1247]
                  │  ├─ Gélé (Dar Fongoro) [fong1243]
                  │  ├─ Malu (Central African Republic) [molo1258]
                  │  ├─ Moto-Mar [motm1238]
                  │  ├─ Mèlè (Central African Republic) [mele1249]
                  │  └─ Méré [mere1241]
                  └─ Sar Gula [sarr1245]
```
