### ISSUE TITLE
dialects for cash1254 and shar1245

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#765]
We'd like to kindly request dialect level glottocodes for two languages: cash1254 and shar1245.

For cash1254:

- One for the variety as spoken in Brazil
- One for the variety as spoken in Peru

For shar1245
- One for the variety described as Arara (Carla Maria Cunha. 1993. A Morfossintaxe da Língua Arara (Pano) do Acre.)
- One for the variety described as Shawã (Emerson Carvalho de Souza. 2012. Aspectos de uma gramática Shawã (Pano))

Or, alternatively, help in matching Arara and Shawã to the existing dialect glottocodes of shar1245.

**Comment by rzariquiey** [comment]
Hi, I will then have a look at the sources and the sheets and let you know which one is the more trustable. There were various differences between them but at least a good portion came from "?". I will let you know what I found and what I can suggest.

**Comment by HedvigS** [comment]
As far as I can tell, this issue can be closed now. We've convinced Harald of adding two dialect glottocodes for cash1254 but not 2 under shar1245. We'll deal with shar1245 in Grambank by merging them in some good way.
