### ISSUE TITLE
Dialect glottocodes for tila1239 please

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#769]
We would like to request two dialect glottocodes for tila1239 that map onto "Acazulco" and "Santiago Tilapa" based on Palancar 2012 ("Santiago Tilapa") and Hernandez-Green 2010 (Acazulco). Thank you

**Comment by d97hah** [comment]
See https://github.com/glottolog/glottolog/pull/771

Pada tanggal Jum, 12 Nov 2021 pukul 09.30 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Thank you

**Comment by HedvigS** [comment]
To confirm, which did you mean to cover "Acazulco" (Hernandez-Green 2010)? sanp1264?

**Comment by xrotwang** [comment]
I'd guess
https://github.com/glottolog/glottolog/pull/771/files#diff-b4935a3e0ed6a8d3e34f71a3e6e5c976a1794815f69063484e53aecef9487925

**Comment by HedvigS** [comment]
@xrotwang yeah I looked at that but I wasn't 100% confident which source Harald imagines maps onto which new glottocode

**Comment by d97hah** [comment]
San Jerónimo Acazulco is a locality in Ocoyoacac

Pada tanggal Jum, 26 Nov 2021 pukul 09.04 Hedvig Skirgård <
***@***.***> menulis:

**Comment by xrotwang** [comment]
ok. I retract my suggestion, then :)

**Comment by HedvigS** [comment]
Okay so Hernandez-Green 2010 (Acazulco) to ocoy1234 and Palancar 2012 ("Santiago Tilapa") to sant1466. Thanks.
