### ISSUE TITLE
Polesian dialects to Ukrainian / Belarusian langauges?

### ISSUE THREAD

**Issue by ptaberg** [glottolog/glottolog#785]
I see just 3 groups of dialects, I think you should add Polesian groups of dialects too. Western Polesian, Central Polesian, Eastern Polesian. You can check [Wikipedia article](https://en.wikipedia.org/wiki/Ukrainian_dialects) about them

**Comment by ptaberg** [comment]
Thanks, @d97hah, it looks better. But what do you think about adding [West Polesian Language](https://en.wikipedia.org/wiki/West_Polesian_microlanguage) as something between Ukrainian and Belarusian? In Belarus Polesian Language plays role as Rusyn in Ukraine and Latgalian in Latvia, but does not have such a great literary activity

**Comment by d97hah** [comment]
Havent we already had this discussion?

Pada tanggal Rab, 1 Des 2021 16.39, Kolja P. ***@***.***>
menulis:

**Comment by xrotwang** [comment]
#581 is somewhat related.

**Comment by ptaberg** [comment]
Oh, yeah, I see [this](https://github.com/glottolog/glottolog/issues/581). But what do you think about such markup, as Samogitian was identified. ![Screenshot 2021-12-01 at 18 56 32](https://user-images.githubusercontent.com/34740585/144267968-f8ce0e53-2ef2-4f2a-b347-cd45d1caa453.png)

**Comment by d97hah** [comment]
I had an email exchange on the q with Kristian roncero. I don't know if
this is the same person as kolja p. In any case, the argument for LG status
of polesian is not conclusive imho. (That is not to say there are other
inconsistencies in glottolog, working on them, slowly)

Pada tanggal Rab, 1 Des 2021 16.57, Kolja P. ***@***.***>
menulis:

**Comment by ptaberg** [comment]
Ok, I think the current implementation is good. When will you merge it?
