### ISSUE TITLE
Comma-separate lgcode entries should be each on a separate line

### ISSUE THREAD

**Issue by d97hah** [glottolog/glottolog#789]
lgcode entries are comma-separated and some are unattributed (lack an = sign) but should then not be display on the same line as the following attribution in the reference-detail sidebar.
E.g.  on https://glottolog.org/resource/reference/id/66179

Basa-To, Kru of Wote, Grebo-Gbumle, Gbe/Gbei, Adampe, Anfue = Anfoin = Krepe [ewee1241]

should be

Basa-To
Kru of Wote
Grebo-Gbumle
Gbe/Gbei
Adampe
Anfue = Anfoin = Krepe [ewee1241]

Apparently people are reading it wrongly at the moment

**Comment by xrotwang** [comment]
Moved to https://github.com/clld/glottolog3/issues/140
