### ISSUE TITLE
Where can I see Polesian dialects on prod?

### ISSUE THREAD

**Issue by ptaberg** [glottolog/glottolog#791]
Hello, can't navigate to Polesian dialects, could you help me?
<img width="500" alt="Screenshot 2021-12-06 at 15 31 32" src="https://user-images.githubusercontent.com/34740585/144846539-22c0010b-0606-4d46-beb9-45dec1b3e316.png">

**Comment by xrotwang** [comment]
You'll only be able to see changes on https://glottolog.org once the next release is published - which we currently plan within the next couple of weeks. Generally, we aim at 2-3 releases per year.
