### ISSUE TITLE
Inconsistent bibkeys in hh.bib

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#796]
There are two bibkeys with a `;` where there should be a `:` (I think):
```
WARNING Invalid bibtex key: hh:s:Kranzmayer;Zimbrischen
WARNING Invalid bibtex key: hh:s:Pierce;Mekranee-Beloochee
```
This trips up the creation of the CLDF data.

**Comment by d97hah** [comment]
Indeed, how to you prefer to get he fix? In a new PR with only those fixes
or a new PR with that and some other update or sthng else?

Pada tanggal Jum, 10 Des 2021 pukul 12.36 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
No preference here. It won't go into 4.5 anymore anyway.

d97hah ***@***.***> schrieb am Fr., 10. Dez. 2021, 13:13:

**Comment by d97hah** [comment]
Good catch, should be fixed now, see new PR

Pada tanggal Jum, 20 Mei 2022 pukul 16.57 Robert Forkel <
***@***.***> menulis:
