### ISSUE TITLE
South Bird's Head

### ISSUE THREAD

**Issue by barlowrussell** [glottolog/glottolog#800]
Uniquely among Glottolog families, South Bird's Head [sout1516] actually has "Family" in its name. Is this intentional? It seems to me it should be called just "South Bird's Head". Or, if the idea here is to explicitly exclude Inanwatan and Konda-Yahadian, then I think, following practices elsewhere, the family should be called "Nuclear South Bird's Head". But the "Nuclear" is perhaps unnecessary.

**Comment by d97hah** [comment]
It's intentional, as this was the name for the intended unit in the (scant)
earlier literature. I don't like to change names just for fun or because it
would be a unique naming style, so that's why. all the best, H

Pada tanggal Min, 2 Jan 2022 pukul 18.03 barlowrussell <
***@***.***> menulis:
