### ISSUE TITLE
Windows cap on file name length

### ISSUE THREAD

**Issue by martino-vic** [glottolog/glottolog#801]
I got an interesting error when cloning this repository onto my Windows 10 system: `fatal: cannot create directory at 'languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/west2968/nzad1235/lwer1234/ding1244/loan1238/klce1234/kiko1235/nucl1804/kiko1234/kamb1321/kila1239/nort3267/laar1238/ghaa1238': Filename too long`

I could overcome this issue by running `git config --system core.longpaths true` before cloning, as explained on [stackoverflow](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows). The problem was that filename length seems to be limited to 260 characters on Windows by default.

I thought I should leave this post here for future reference.

**Comment by xflr6** [comment]
Thanks Victor.

Just in case there is also Windows' own `LongPathsEnabled` which might be needed. See also the test setup for `treedb` on Windows: https://github.com/glottolog/treedb/blob/5bd09814cf6bd7bf5d441cb0f7b6d83c9659f79a/.github/workflows/build.yaml#L43-L51
