### ISSUE TITLE
Bangani lat/mon mixup

### ISSUE THREAD

**Issue by hojucha** [glottolog/glottolog#805]
Hello, I believe Bangani [bang1335] has its lat/lon coordinates mixed up, putting it in Svalbard rather than India. It seems that #773 was supposed to fix this problem, but I think the original coordinates before this change were correct. Right now the coordinates are:
```
latitude = 79.0686
longitude = 29.8692
```
But they should be:
```
latitude = 29.8692
longitude = 79.0686
```

**Comment by d97hah** [comment]
Thanks Hoju! Not sure how the undoing of #773 came about but probably due
to my batch dealings with other changes. Be that as it may,
https://github.com/glottolog/glottolog/pull/806 should refix.

Pada tanggal Sel, 11 Jan 2022 pukul 08.20 Hoju Cha ***@***.***>
menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/pull/806/files#diff-e265295b1c5ef8361041a810de3bdb3e7123170adccf5b51990e7343af3a6f05
