### ISSUE TITLE
Canonical strategy to have an fully numeric Glottocode

### ISSUE THREAD

**Issue by fititnt** [glottolog/glottolog#808]
I'm aware this use case is specific, so it doesn't need to be an official strictly planned numeric alternative. Glottocodes already are _near_ fully numeric so canonical numeric equivalence for the prefixes could already be a win-win.

## A. Use case
On numeration https://numerordinatio.etica.ai/ (https://github.com/EticaAI/numerordinatio, and here https://github.com/EticaAI/multilingual-lexicography-automation) we're already trying to linearize concepts. Numbers are not as friendly for humans, so an ideal user would need attached metadata, but they're very friendly for data conversion.

On humanitarian sector, there is also problem with licenses (and the fact that local information managers tend to not keep their databases as up to date; however one coping mecanism is re-share code tables on several formats and incentive them to keep up to date) so it's really important have some way to no matter how things go bad on international context, some sort of unique identifiers could work, even if have to remove all metadata and take it from public domain sources (such as Wikidata).

Private companies and humanitarian organizations may be trying to exchange linguistic data (such as translations for emergency response and other humanitarian initiatives) with codes that may be not exactly what people think they are. This cannot be solved by attaching an country code to an ISO 639-1 alpha 2 because software only support this (like when using commercial software for humanitarian contexts). With such context, whatever would be codes used, if not for automated checks (and conversions between language codes) but suggest to humans to use interfaces such as https://glottolog.org/ to know what language they are actually compiling, the end result could actually be more well informed. Also note that most challenges happens with non-Latin script, so no matter how well intentioned (and with quality control and even trying to ask professional translators) compiling lots of languages (as opposed to when someone is working only with one or two) means end result is hard to have review.

I could talk more here, but even without numeric equivalent, in my honest opinion any strategy to push Glotocodes and ISO 639-3 and burn ISO 639-1 alpha 2 in hell are really important.

### A.I Great examples already using numeric codes

Our type of use case is more close to UN m49 (https://en.wikipedia.org/wiki/UN_M49) which is even ISO 3166 (https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) cites:

> _ISO 3166-1 numeric – three-digit country codes which are identical to those developed and maintained by the United Nations Statistics Division, with the advantage of script (writing system) independence, and hence useful for people or systems using non-Latin scripts._

The closest to linguistic context is ISO 15924 (https://en.wikipedia.org/wiki/ISO_15924) from Unicode which has a formal numeric version. However, as ironic as it may seem, not even ISO 639-3 have numeric alternatives, so we're already having to create procedural and reversible ways to convert between short already non-numeric codes to fully numeric ones. Glotocodes have both a prefix and one numeric suffix, so it could have a more efficient way (even without waiting for a strictly designed numeric version) to encode/decode Glotocodes.

### A.II Our current generic approach (any non numeric code)
Currently we use the base 60 system and use the least significant digit as a decimal error detection code (https://en.wikipedia.org/wiki/Error_detection_and_correction). I could explain a bit more. But even if the base numbers from 60 to 26 + 10, and the end result could be like less than a 32 signed int (2147483648) such as stan1293 would generate something like 2257966624935. On a base 60 could generate something such as 8200758833817838966, and this almost already is an overflowing 64 bit signed integer, so our strategy to generalize small US-ASCII codes (often 2 to 5 characters) already is near not even work for computers.

In other words: **Glotocode does not compress as well to other codes such as IATA and ICAO**. And since there is no existing place which publishes numeric codes for languages, this is quite relevant. Also, after this issue https://github.com/glottolog/glottolog/issues/797 it seems relevant to work with you here as we have a stable numeric system.

> Trivia: actually a lot of other codes which are composed on several parts actually reuse for example ISO 3166 part 1 alpha 2, so _is possible_ to replace such 2 letters from ISO 3166 part 1 with 3 numbers from UN m49 without any loss of information. This is why for example codes which are near 8 characters (but can be broken, such as prefixes by country or territory) compress quite well with UN m49.

----

## B. Some suggested potential strategies
Ok, after all this context said, here the more practical part.

2 and 3 are similar. 4 is would require much more planning, so either 2 or 3 already seems great to me.

### 1. Compress the entire code with all namespace (36 characters)
This strategy does not work well for Glotocodes as it would work for other smaller codes. But it is one strategy.

### 2. Only compressing the prefix
One strategy could just compress the prefixes. Whatever would be on the dictionary table (60, or 36[a-z0-9] or 26[a-z]) it would work.

This has the advantage of no need for any handcrafted tables. Just documentation. Also the final result would still resemble the existing codes (just prefixes would change).

### 3. Release Glotocodes with dedicated numeric tables with equivalence between all prefixes and handcrafted tables

I'm not sure how many unique prefixes there are, but it is unlikely Glotocodes would use 4 digits with all 26 letters variants ever (26 * 26 * 26 * 26= 456978). So, if the maximum number of variants is likely to be predictable, then a maximum number could be defined, and then manually distribute the handcrafted equivalent table between all prefixes and their letter code.

If this path is decided, then one strategy to build the first version is sort the results alphabetically and distribute the numbers. And every time a new prefix is created, then release a new number for that prefix.

### 4. Fully numeric code (both prefix and suffix) as an entire new code
I don't think this strategy is really necessary. It also has the disadvantage of the end result not resembling the existing Glotocodes. Glotolog 4.5 shows 8155 all encoded languages (which in theory could require as low as 99999 digits on decimal system), but both for room for future use (and to numeric code not be confused with existing numeric suffixes) it would be better not be less than 99999 digits.

> One trivia: ISO 639-3 (if directly making a letter to code transposition, 26 x 26 x 26, here ignoring the non usable spaces) would require a maximum of 17576. So in practice (again, on decimal system) the minimum fully numeric Glotocodes would ideally require would take same space as ISO 639-3

New fully numeric codes (in addition to taking time to decide how to distribute them) would require a massive commit changing every file. Note that even the decision (not the commit) on such change is not as trivial, since for example just assigning numbers one after another have disadvantages. For example UN m49 original paper (https://unstats.un.org/unsd/publication/SeriesM/Series_M49_(1970)_en-fr.pdf) the numbers had a gap between them. One implicit advantage of such a gap (while it is not a dedicated digit for error checking) is that simple human error on a digit can actually generate an non-existent number, so one-after-another wastes this feature. Also, if already assigning numeric codes, the way numbers are distributed could have other features such as allow private use range. The numbers below 10000 could also be avoided (so in decimal systems, such codes would always take 5 characters.

----

Anyway, as for this open issue, my question to others is mostly suggestions on how people from outside could encode Glotocodes in numbers. Potentially there are others which would not fit on these and still be possible to generate the numbers and revert them back.

**Comment by HedvigS** [comment]
I get the idea, but I think glottolog is way too far along for such big changes.

**Comment by xrotwang** [comment]
I think that's out of scope. Pushing usage of the identifiers we have now is already an uphill battle. I wouldn't want to make that any harder by introducing yet another set of identifiers.
