### ISSUE TITLE
more sanskrits please?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#809]
Glottolog current contains one Sanskrit languoid, Sanskrit [sans1269]. Some scholars make further distinctions of varieties, such as "Vedic Sanskrit”, “Classical Sanskrit” and “Epic Sanskrit”. We've found through the Grambank coding that these varieties sometimes exhibit different features. It is obviously hard with ancient languages, especially ones that are so widely known and overlapping to determine mutual intelligibility etc. From our perspective, perhaps a model like for Early Irish would make sense where dialect level glottocodes could be added for these varieties. 

Up to you as editors where to places these languoids, but we'd like to request at least dialect level glottocodes for these varieties please.

**Comment by d97hah** [comment]
See new PR which has vedic and classicial

Pada tanggal Sel, 25 Jan 2022 pukul 10.02 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Dank u wel
