### ISSUE TITLE
can I get permission to branch and make PRs?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#812]
I was wondering if I can get permission to make branches and PRs to this repos? As it is now I'd have to fork to make suggestions, and while that's perfectly possible it's a bit clunky. It'd be easier with branches. I don't need direct edit access to the main branch of course, please keep that protected. I'd make changes in branches and make PRs that you can inspect and evaluate.

**Comment by HedvigS** [comment]
I'm corresponding with various language experts and gathering information about improvements to glottolog. I think that instead of making issues for each suggestion, it'd be easier if I group them thematically and make PRs with each suggestion as a separate commit.

**Comment by xflr6** [comment]
>  As it is now I'd have to fork to make suggestions, and while that's perfectly possible it's a bit clunky.

Not sure I understand correctly, maybe this helps: https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date

**Comment by xrotwang** [comment]
Write access to a repos includes more than just write access to the git repos. Some of these things - like managing pull requests and issues - appear to me as things that's typically done by maintainers - or here editors.

**Comment by HedvigS** [comment]
Right okay. Hm, i'm wondering if there is some way. Seems like a usage case other people should have needed before.

**Comment by HedvigS** [comment]
Neat, I just found out about custom roles :) https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization

**Comment by xrotwang** [comment]
> If your organization uses GitHub Enterprise Cloud, you can have more granular control over the permissions you grant at the repository level by creating up to three custom repository roles.

**Comment by HedvigS** [comment]
> If your organization uses GitHub Enterprise Cloud, you can have more granular control over the permissions you grant at the repository level by creating up to three custom repository roles.

yeah i saw that. I wasn't sure what plan we're on from DLCE.

**Comment by HedvigS** [comment]
but I don't think we should buy something just for little ol' me. I'll just switch between GUI and CLI.
