### ISSUE TITLE
Is Serbian Torlak a candidate for a new dialect?

### ISSUE THREAD

**Issue by xrotwang** [glottolog/glottolog#815]
See https://github.com/autotyp/autotyp-data/pull/42#issuecomment-1048565221

**Comment by d97hah** [comment]
Prizren-South Morava [priz1234] or Timok [timo1264] depending on the exact
provenance

Pada tanggal Rab, 23 Feb 2022 pukul 10.05 Robert Forkel <
***@***.***> menulis:
