### ISSUE TITLE
Include bibs

### ISSUE THREAD

**Issue by psubhashish** [glottolog/glottolog#817]
Requesting to be included in https://github.com/glottolog/glottolog/blob/master/references/BIBFILES.ini. Attached the zipped bib file [here](https://github.com/glottolog/glottolog/files/8175405/ofdn.bib.zip) to be used. I have assumed that the acronym "ofdn" could be used as we also use in multiple places otherwise and could be use useful for consistency but happy to hear other suggestions. Thanks in advance.

[ofdn.bib]
name = OFDN
title = O Foundation
description = The bibliography submitted by the [O Foundation](https://theofdn.org) in February 2022 that contains materials published both by the Foundation and works of other authors that the Foundation catalogued.
abbr = ofdn
# penalize entrytpe 'misc' everywhere
priority = 
url = https://theofdn.org/
curation =

**Comment by d97hah** [comment]
Hi Subhashish! Thanks for this. We're happy to include it. @xrotwang, see
PR https://github.com/glottolog/glottolog/pull/819

Pada tanggal Kam, 3 Mar 2022 pukul 07.19 Subhashish Panigrahi <
***@***.***> menulis:

**Comment by psubhashish** [comment]
Thank you @d97hah for the quick response. Please do let me know if there is anything that might be missing or requires any changes.
