### ISSUE TITLE
Render entries in Lastname, Firstname1 Firstname2 ... FirstnameN format, i.e., Angela Kluge -> Kluge, Angela

### ISSUE THREAD

**Issue by d97hah** [glottolog/glottolog#824]

**Comment by xrotwang** [comment]
Where should this rendering happen? When linearizing the bibtex data, e.g. in https://glottolog.org/resource/reference/id/550018 ? Or do this already in the "raw" bibtex?

**Comment by d97hah** [comment]
Pada tanggal Sen, 21 Mar 2022 pukul 09.39 Robert Forkel <
***@***.***> menulis:

> Where should this rendering happen? When linearizing the bibtex data, e.g.
> in https://glottolog.org/resource/reference/id/550018 ?
>

Yes



> Or do this already in the "raw" bibtex?
>
No, only in the rendering. The following principles should be enough to
parse the name as it may appear in the bibtex to obtain Lastname,
Firstnames:
1. Split the names by " and "
2. If a name has one comma, then the Lastname is what is before the comma
and the Firstname(s) after
3. If a name has two commas, the Lastname is what is before the first comma
and the Firstname(s) after the last comma and the Jr-part in the middle.
The Jr part should be rendered after the lastenames with a comma, e.g.
Forkel, Jr., Robert
4. Otherwise the lastname is the last capitalized token (for script systems
with capitals, otherwise just the last token) plus any preceding sequence
of lowercase de|di|da|du|van|von tokens

**Comment by xrotwang** [comment]
moved to clld/glottolog3
