### ISSUE TITLE
[tll] is NOT the correct ISO 639-3 language code for the [mali1286] "Tlapanec" dialect of [tcf] "Malinaltepec Me'phaa"

### ISSUE THREAD

**Issue by verdy-p** [glottolog/glottolog#826]
"tll" is the correct ISO 639-3 language code for [tll]"Tetela" (a Nkutsuic language, part of Narrow Bantu languages, spoken in Congo DRC.)

But "tll" is NOT an ISO 639-3 language code for the [mali1286] "Tlapanec" dialect of [tcf] "Malinaltepec Me'phaa" (a Mesoamerican language spoken in Central Mexico).

Incorrect langage name aliases for Tetela were introduced by incorrectly importing and checking an informal "comment" line from the UNESCO endangered languages database.

Remove these lines from [tll]:

multitree =
````
	Tlapaneco malinaltepeco
	Tlapanèque de Malinaltepec
````
and
````
[endangerment]
status = threatened
source = UNESCO
date = 2017-08-19T22:02:46
comment = Malinaltepec Tlapanec (698-tll) = Vulnerable
````

These lines, related to the [mali1286] "Tlapanec" dialect of [tcf] "Malinaltepec Me'phaa", have to be moved elsewhere :

https://glottolog.org/resource/languoid/id/mali1286

----

Additionally, if this comes from UNESCO, they should be notified to fix their:
````
comment = Malinaltepec Tlapanec (698-tll) = Vulnerable
````

But it is possible that, for langoids that are now considered in ISO 639-3 as dialects of another parent language, the UNESCO used their own private code (698-tll): this [tll] is then not meant to be ISO 639-3 (if so, it would have to be now [tcf] for Malinaltepec Me'phaa), and in that case, nothing was wrong in UNESCO database, but the UNESCO comment was badly interpreted by an human.

**Comment by xrotwang** [comment]
The alternative names were removed, see
```diff
$ git diff c26a7768f3ca953525dd0134d22d7a83f3858ce6..45a5eb08449c60b01cb53a05d1bba957fc76bcf9  languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/nort3376/inne1246/vieu1234/nkut1239/tete1254/tete1250/md.ini
diff --git a/languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/nort3376/inne1246/vieu1234/nkut1239/tete1254/tete1250/md.ini b/languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/nort3376/inne1246/vieu1234/nkut1239/tete1254/tete1250/md.ini
index 710636826b..29a90ffcea 100644
--- a/languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/nort3376/inne1246/vieu1234/nkut1239/tete1254/tete1250/md.ini
+++ b/languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/nort3376/inne1246/vieu1234/nkut1239/tete1254/tete1250/md.ini
@@ -154,8 +154,6 @@ multitree =
        Otetela
        Sungu
        Tetela
-       Tlapaneco malinaltepeco
-       Tlapanèque de Malinaltepec
 lexvo = 
        Tetela [en]
        Tetela language [en]
```

These changes will only show up at https://glottolog.org once the release is finished.

We have not notified the maintainers of the UNESCO database (in fact I'm not aware that there are any). And no, we didn't check the origin of this import. Over time, Glottolog's own assessment of endangerment status (and that of the ElCat project) will supersede whatever was import from UNESCO.
