### ISSUE TITLE
Levantine Bedawi Arabic

### ISSUE THREAD

**Issue by a455bcd9** [glottolog/glottolog#832]
What are [North Levantine Bedawi Arabic](https://glottolog.org/resource/languoid/id/nort3130) and [South Levantine Bedawi Arabic](https://glottolog.org/resource/languoid/id/sout3112)? I've never seen these terms used anywhere.

And why are they under "Egyptian Arabic" and not under "Levantine Arabic"? (I don't say that this is incorrect, but I'm just surprised and curious)

**Comment by xrotwang** [comment]
Glottolog's dialect inventory started out largely with dialects as aggregated by the [multitree](http://multitree.org/) project. The two you ask about above are such dialects. So someone at some point used these names - and classified the corresponding languoids under `ISO:avl`. It will take a while to get Glottolog's dialects as complete and reliable as we hope the language repository to be (see also http://www.semantic-web-journal.net/content/glottocodes-identifiers-linking-families-languages-and-dialects-comprehensive-reference).

**Comment by d97hah** [comment]
Hi Antoine! Read the references cited, and also note that these are Bedouin
Arabic lects. all the best, H

Pada tanggal Kam, 31 Mar 2022 pukul 13.27 Robert Forkel <
***@***.***> menulis:

**Comment by a455bcd9** [comment]
Hi @d97hah, unfortunately, there are 0 references cited:
* [Dialect: North Levantine Bedawi Arabic](https://glottolog.org/resource/languoid/id/nort3130): "References ⇫ Showing 0 to 0 of 0 entries"
* [Dialect: South Levantine Bedawi Arabic](https://glottolog.org/resource/languoid/id/sout3112): "References ⇫ Showing 0 to 0 of 0 entries"

Which references are you referring to?

**Comment by d97hah** [comment]
Unfortunately references aren't attached to the dialect levels, there might
be a systematic fix for a large number of these cases in the future, but
not as of now. For now, you have to look at the corresponding
language-level (but that doesn't tell you which is which so might take
time), in this case the works on Cantineau. all the best, H

Pada tanggal Sab, 15 Okt 2022 pukul 12.14 Antoine Dusséaux <
***@***.***> menulis:

**Comment by a455bcd9** [comment]
Thanks a lot!
