### ISSUE TITLE
add Toki Pona and Medefaidrin

### ISSUE THREAD

**Issue by janPensa** [glottolog/glottolog#841]
Toki Pona and Medefaidrin are currently the only constructed languages with an ISO 639-3 code that are not included in Glottolog. I propose adding them to the [arti1236](https://github.com/glottolog/glottolog/tree/master/languoids/tree/arti1236) family. You can use these for the md.ini files:

```
# -*- coding: utf-8 -*-
[core]
name = Toki Pona
level = language
iso639-3 = tok
hid = tok
macroareas = 
	North America
links = 
	https://en.wikipedia.org/wiki/Toki_Pona
	https://www.wikidata.org/entity/Q36846
countries = 
	CA
```

```
# -*- coding: utf-8 -*-
[core]
name = Medefaidrin
level = language
iso639-3 = dmf
hid = dmf
macroareas = 
	Africa
links = 
	https://en.wikipedia.org/wiki/Medefaidrin
	https://www.wikidata.org/entity/Q1519764
countries = 
	NG

[altnames]
glottolog =
	Medefidrin
	Obɛri Ɔkaimɛ
```

Note: Medefaidrin's alternative names Medefidrin and Obɛri Ɔkaimɛ are listed in [the ISO 639-3 change request](https://iso639-3.sil.org/sites/iso639-3/files/change_requests/2019/2019-036_dmf.pdf) and on the language's [Wikidata page](https://www.wikidata.org/wiki/Q1519764), in case you want to check.

**Comment by d97hah** [comment]
Hi Jan! They're both already in the version in the repos. all the best, H

Pada tanggal Kam, 5 Mei 2022 pukul 21.21 janPensa ***@***.***>
menulis:

**Comment by janPensa** [comment]
@d97hah Hi!

I can't find either language in the repos in the main branch here on Github, neither in [the arti1236 family folder](https://github.com/glottolog/glottolog/tree/master/languoids/tree/arti1236) nor in the lists at [languages_t.md](https://github.com/glottolog/glottolog/blob/master/languoids/languages_t.md) and [languages_m.md](https://github.com/glottolog/glottolog/blob/master/languoids/languages_m.md). Unless you mean other repos?

**Comment by d97hah** [comment]
Medefaidrin is Medefidrin [mede1238] dmf and re Toki Pona you are excused
for not finding it, I had not checked it in! Sorry! H

Pada tanggal Rab, 11 Mei 2022 pukul 20.28 janPensa ***@***.***>
menulis:
