### ISSUE TITLE
ISO 639-3 nds

### ISSUE THREAD

**Issue by chiarcos** [glottolog/glottolog#845]
Should be at lowg1239, not at nort2627.

Objective: This includes East Low German, but it also applies to North Low Saxon (esp. Nedersaksisch, mentioned at the ISO definition), so it must be at a common ancestor of East and West Low German. 

Note: This makes ISO 639-3 pdt (plau1238) and wep (west2356) descendants of ISO 639-3 nds and this apparent mismatch has probably triggered the current classification. If Glottolog aims for consistency with ISO 639 taxonomy, it would have to create a common parent node for nort2627 and west2357 that excludes west2356. If such a node would be created it should, however, not be called "North Low German" (German "Nordniederdeutsch") as this term seems to be restricted to a specific variety of *West* Low German (References in https://de.wikipedia.org/wiki/Nordniederdeutsch).

**Comment by d97hah** [comment]
I find it difficult to follow your argument here (and what your sources are
for saying something is 'close' to something), and likely the Glottolog
division is not easy to follow either but the bulk seeks to follow
Wiesinger or other references cited (at least Wiesinger will have the kind
of guidance your are asking for) and many choices in dialectal division
*are* arbitrary.

Pada tanggal Kam, 12 Mei 2022 pukul 10.04 Christian Chiarcos <
***@***.***> menulis:

**Comment by d97hah** [comment]
I don't agree. I don't know what the ISO 639-3 definition of [nds] is but
the Ethnologue definition of [nds] has elements that are ambiguous (such as
Nedersaksisch) but predominantly refers to nort2627 rather than lowg1239,
especially in consideration of other entries such as [wep], [pdt], [frs]
etc.

Pada tanggal Rab, 11 Mei 2022 pukul 20.12 Christian Chiarcos <
***@***.***> menulis:

**Comment by xrotwang** [comment]
FWIW, from my point of view ISO codes associated with Glottolog languoids are "just textual metadata", i.e. there's no rule saying an ISO code can only be attached to one node in a lineage. If anywhere at all, such constraints might be attached to the "special" `hid` property. So maybe moving the ISO code `nds` to `lowg1239` while leaving `hid=nds` at `nort2627` would be the proper thing to do. Thughts, @d97hah ?

**Comment by d97hah** [comment]
Pada tanggal Sen, 28 Nov 2022 pukul 16.10 Christian Chiarcos <
***@***.***> menulis:

> Effectively, what you're saying is that [nds] doesn't apply to Western Low
> German. That's not stated publicly anywhere, but it means that there is no
> alternative label for North Low Saxon. In particular, it contradicts the
> intuition of the speakers (e.g., map "Dor warrt Plattdüütsch spraken" at
> the entry page of the Low German Wikipedia,
> https://nds.wikipedia.org/wiki/Wikipedia:H%C3%B6%C3%B6ftsiet), and it
> contradicts the practical use among major resources.
>

I don't think the speakers have an intuition on the scope of the [nds] ISO
639-3 code, but even if they did, your problem would rather like with ISO
639-3 than Glottolog.


>
> As such, both Low German Wikipedias (nds and nds-NL) *prescribe* the use of
> _Western_ Low German as standard variety for writing (
> https://nds.wikipedia.org/wiki/Wikipedia:Platt,_wo_schriev_ik_dat%3F: "Wi
> hebbt seggt, för de plattdüütsche Wikipedia wüllt wi uns geern so’n beten
> an de Schrievwies vun Sass <https://nds.wikipedia.org/wiki/Wikipedia:Sass>
> hollen."; https://nds-nl.wikipedia.org/wiki/Hulpe:Nedersaksisch_schrieven:
> "alle Nedersaksische dialecten *van Nederlaand*" [no Eastern LG there]).
> Likewise, the Low German [nds] Wiktionary uses predominantly North Low
> Saxon orthography (
> https://nds.wiktionary.org/wiki/Wiktionary:H%C3%B6%C3%B6ftsiet: "Den
> skryvwyse dee dat meyst bruked is in Wikiwöörbook-lemmas is de Sass'sche
> Schrievwies
> <
> https://nds.wiktionary.org/w/index.php?title=Sass%27sche_Schrievwies&action=edit&redlink=1
> >,
> en regionale skryvwyse vöär noordsassiske dialekten uut Düütskland.")
>

Great, but again, not of great relevance for Glottolog.


> The argumentation seems to be that a Glottolog languoid with an ISO code
> must not contain another Glottolog languoid with a separate ISO code. Fair
> enough, but this doesn't adequately reflect the nature of ISO codes which
> are not linguistic by nature but a compromise between technical
> requirements, politics and linguistics.


No that's a requirement of ISO 639-3 (save for macro-languages). Like I
said earlier, the [nds] has elements which are contradictory in scope, so
there can be no perfect solution. I would still defend the current mapping
between Glottolog and ISO 693-3, though, as the lesser bad.


> If applied consistently, this
> principle leads to the abandonment of *any* counterpart of [nds] in
> Glottolog. I understand that the creation of such a counterpart has been
> the underlying force for creating "Greater East Low German", but in fact,
> even that one is questionable -- as [pdt] is just a regional variant of Low
> Prussian [lowe1387]. The reason for setting it apart in a separate ISO tag
> is mostly political, geographic and orthographic, but not linguistic
> proper. (Cf. Mitzka, Walter (1930): Die Sprache der deutschen Mennoniten.
> Heimatblätter des Deutschen Heimatbundes, Danzig. 8. Jahrgang, Heft 1.
> Danzig, S.5: "Im Weichsellande haben die ehemals aus den Niederlanden
> gekommenen Mennoniten in den zwei- bis zweieinhalb Jahrhunderten, die bis
> zur russischen Wanderung vergingen, die dortige Mundart [das sog.
> Niederpreußisch] und die deutsche Schriftsprache aufgenommen".)
>

Historically, [pdt] is Eastern Low German yes, but it's not "just a
regional variant" but a variant that has undergone considerable change in
exile, to the degree that it may not be intelligible to Eastern Low German
variants at home. I can't say I have a definite claim to this effect, or
the opposite, but see the discussion in Nieuweboer (1998). If you know for
a fact that they are intelligible, do let me know.


>
> In any case, the current treatment of [nds] in Glottolog contradicts its
> practical application to *both* North Low Saxon and East Low German in
> modern language technology, as much of that is based on Wiktionary and
> Wikipedia -- and any other web corpus, as these are the primary basis for
> building profiles for language identification.
>

This may be so but hardly Glottolog's concern.


>
> Unfortunately, the Ethnolog definition of [nds] isn't public. From the free
> snippet, I don't see anything specific to East Low German, but its redirect
> to OLAC [https://www.ethnologue.com/language/nds] explicitly includes both
> East and West Low German varieties (excluding those with ISO codes on their
> own, esp. West Phalian):
> - eastern: East Prussian, Maerkisch-Brandenburgisch, Mark-Brandenburg,
> Märkisch-Brandenburgisch, Mecklenburg-Anterior Pomerania,
> Mecklenburgisch-Vorpommersch
> - western: Eastphalian, Holsteinisch, Neddersassisch, Nedersaksisch,
> Niedersaechsisch, Northern Low Saxon, Ostfaelisch, Ostfälisch, Low Saxon
> - neutral: Nedderdütsch, Plattdeutsch, Plattdüütsch)
>
> BTW: The term "Nedersaksisch" is not ambiguous, but specifically Low German
> in the Netherlands, as in all LW varieties in Germany I am aware of, -ks-
> becomes assimilated to -ss-.
>

The below is the info on [nds] from Ethnologue 25. It's true that it
includes both W and E Low German but the set of varieties is paraphyletic
with respect to Wiesinger 1983 and the other ISO 639-3 codes [frs], [gos]
and [wep] and all the codes that cover Nedersaksisch (that's what makes the
entry ambiguous, not the term itself). So the option for Glottolog is to
(i) not use [nds] at all, (ii) reinterpret/adjust the scope of [frs],
[gos], [wep], [nds] as per Glottolog, (iii) attach [nds] to a non-language
node. (ii) is the least bad option.

name: Saxon, Low
Writing: Latin script [Latn].
Population Numeric: 301000
Population: 2,201,000 in Germany, all users. L1 users: 1,000 in Germany. L2
users: 2,200,000 (2016). Total users in all countries: 2,501,000 (as L1:
301,000; as L2: 2,200,000).
Other Comments: Printed fairly widely outside Europe, particularly in North
and Latin America, Australia, Southern Africa, and Eastern Europe (Siberia,
Kazakhstan).
Location: Niedersachsen state: north of a line from Aachen to Frankfurt an
der Oder.
Language Use: Officially recognized as a regional (separate) language in 8
states of Germany. Recognized as a regional (separate) language by the
European Charter on Languages. Adults only. Shifting to Standard German
[deu]. Used as L2 by Northern Frisian [frr].
Language Status: 7 (Shifting). Statutory language of national identity
(1998, ECRML, signed in November 1992 and ratified by the Federal Bundestag
Implementation Act, Gazette, page 1314), There are also 6 states that
concede recognized language status to Low Saxon/Low German, and 2 states,
Schleswig-Holstein and Mecklenburg-Vorpommern, afford special protection to
the language in their basic laws.
Language Resources: OLAC resources in and about Saxon, Low
Language Maps: Southern Brazil
Language Development: Dictionary. Bible: 1478–1534.
ISO 639-3: nds
Dialects: Northern Low Saxon (Nordniedersächsisch, North Low Saxon),
Eastphalian (Eastfalian, Ostfaelisch, Ostfälisch, Plattduitsch),
Holsteinisch (Holsatian), Mecklenburg-Anterior Pomerania
(Mecklenburgisch-Vorpommersch, Pomeranian), Mark-Brandenburg (East
Prussian, Maerkisch-Brandenburgisch, Margravian, Märkisch-Brandenburgisch),
Sleswickian (Schleswigsch). Listed dialects are in Germany. The first 3
dialects listed are Western Low Saxon, the other 2 are Eastern Low Saxon.
Not intelligible to speakers of Standard German [deu]. A direct descendant
of Old Saxon, related to English [eng]. 20 to 30 dialects with differing
inherent intelligibility, depending on geographic distance. They did not
experience the second consonantal shift of the 8th and 9th centuries (1976
J. Thiessen). Modern forms have been largely suppressed until recently and
have received much Dutch [nld] or Frisian influence, depending on the area.
Low Saxon varieties are listed separately in the Netherlands, where they
have official status. Pomerano is used in Latin America. Westphalian [wep]
and Plautdietsch [pdt] also have separate entries.
Country: Germany
Classification: Indo-European, Germanic, West, Low Saxon-Low Franconian,
Low Saxon
Autonym: Nedderdüütsch, Plattdüütsch
Alternate Names: Low German, Nedderdütsch, Neddersassisch, Nedersaksisch,
Niederdeutsch, Niedersächsisch, Platt, Plattdeutsch
Also spoken in: {'View other languages of Brazil': {}}
code+name: Saxon, Low [nds]

**Comment by chiarcos** [comment]
>
> I don't think the speakers have an intuition on the scope of the [nds] ISO
> 639-3 code, but even if they did,


They have an intuition as to whether a Wikipedia is theirs or not,
regardless what label it uses. But if that very label is used to define the
language in technology and libraries (= ISO 639-2), and the main variety
(post WWII media almost exclusively featured North Low Saxon) is not
covered, then we have a severe practical problem.


> your problem would rather like with ISO
> 639-3 than Glottolog.
>

Indeed. This comes from ISO 639-2 [nds], where it covers all Low German
and, AFAIK, that used to be the case in ISO 639-3, too, but after the
creation of [wep], etc., ISO 639-3 [nds] just became ill-defined (or, at
least, mismatching from the conventional dialect classification into
Western and Eastern Low German).
Question: Can Glottolog replace the link from to ISO 639-3 [nds] with ISO
639-2 [nds]? That would be less incorrect. Still an issue with ISO 639-3
[nds] in that it claims to be equivalent with ISO 639-2 [nds].
The paraphylactic nature of ISO 639-3 [nds] (in opposition to ISO 639-2
[nds]) is quite clear, but as Robert writes that this is metadata anyway
and not interpreted within Glottolog, is there any practical reason to not
apply one ISO code to two languoids?

If there are technical reasons to not go this route, my recommendation
would be to move [nds] to North Low Saxon as this is the variety with most
data and teaching materials. Linguistically, this is exactly as bad as
limiting it to Eastern Low German, but it's a better fit with what is
actually tagged on the web as [nds].


> > both Low German Wikipedias (nds and nds-NL) *prescribe* the use of
> > _Western_ Low German as standard variety for writing ...
>
> Great, but again, not of great relevance for Glottolog.
>

From my understanding, the relevance of Glottolog comes from providing a
structured access to bibliography, primary data and teaching materials. If
that is a goal, a mismatch with the majority of available data beyond
Glottolog is a bit of an issue. At least, it casts doubt on the objective
of creating an ISO 639 mapping in the first place.


> > The argumentation seems to be that a Glottolog languoid with an ISO code
> > must not contain another Glottolog languoid with a separate ISO code.
> Fair
> > enough, but this doesn't adequately reflect the nature of ISO codes which
> > are not linguistic by nature but a compromise between technical
> > requirements, politics and linguistics.
>
>
> No that's a requirement of ISO 639-3 (save for macro-languages). Like I
> said earlier, the [nds] has elements which are contradictory in scope,


The contradiction is less about what is in scope but about what isn't. In
particular, creating separate tags for West Phalian and all Dutch
sub-dialects in ISO 639-3 was a mistake in that it destroyed the
mappability between ISO 639-2 [nds] and ISO 639-3 [nds]. That process was
probably triggered by a mis-interpretation of ISO 639-2 [frs] -- via the
ISO 639-3 mapping, we now take it to mean East Frisian Low Saxon, but as it
is somewhat underdefined in ISO 639-2, it seems conceivable that this
originally meant to refer to ISO 639-3 [stq] (as in Fort, M. E. (2001). The
East Frisian Dialect of the Saterland. *Handbuch des Friesischen= Handbook
on Frisian Studies. Tübingen: Niemeyer*, 409-422.).
[By "mistake", I don't mean to say I object the creation of these IDs, but
that the internal consistency of ISO 639 is broken.]


> The below is the info on [nds] from Ethnologue 25.


Thank you for sharing that.


> It's true that it includes both W and E Low German

but the set of varieties is paraphyletic with respect to Wiesinger 1983
>
and the other ISO 639-3 codes [frs], [gos]
> and [wep] and all the codes that cover Nedersaksisch (that's what makes the
> entry ambiguous, not the term itself).


For ISO 639-3: yes. For ISO-639-2: no.


> So the option for Glottolog is to
> (i) not use [nds] at all, (ii) reinterpret/adjust the scope of [frs],
> [gos], [wep], [nds] as per Glottolog, (iii) attach [nds] to a non-language
> node. (ii) is the least bad option.
>

From these, (ii) is probably indeed the least bad option, indeed, but it
comes in several flavors:

(ii.a) link [lowg1239] with ISO 639-3 [nds] and accept the applicability of
multiple ISO 639-3 codes to some sub-dialects (via ISO 639-2, these can be
tagged [nds] regardless of their ISO 639-3 code, and preferring ISO 639-2
over ISO 639-3 is best practice anyway, cf.
https://www.rfc-editor.org/rfc/rfc4646.txt).
(ii.b) link German North Low Saxon [nort2628] with ISO 639-3 [nds]
(ii.c) link North Low Saxon [ostf1234 -- the abbreviation in this ID are a
bit of a mis-nomer] with ISO 639-3 [nds] and accept the applicability of
multiple ISO 639-3 codes to some sub-dialects
(ii.d) link East Low German [nort2627] with ISO 639-3 [nds]

From these, (ii.a) would be the least incorrect in that any existing
[nds]-tagged literature or text would fall into a Glottolog languoid that
is actually applicable.
(ii.b) and (ii.d) are equally bad from a linguistic point of view, but
(ii.b) captures more [nds]-tagged data than (ii.d) because the majority of
post-war literature and media production to this day, including all major
digital resources now in existence, focus on West Low German. I added
(ii.c) for the sake of completeness, it correctly accounts for anything
tagged as [nds-NL] or published in the Netherlands, but has all the
downsides of (ii.a) plus missing East Low German.

Two more options:

(iv) instead of linking [lowg1239] with ISO 639-3 [nds], link [lowg1239]
with ISO 639-2 [nds]
(v) link [nort2627] *and* [nort2628] with ISO 639-3 [nds]

As this is not the place to fix ISO 639-3, my suggestion would be to apply
the following ranking to those possibilities:

(v) (if technically feasible: corresponds exactly to the current definition)
(iv) (if technically feasible: does not make incorrect predictions about
the applicability of a languoid for a resource, data or literature tagged
with [nds])
(ii.a) (overgeneralize the ISO 639-3 definition but lose neither data nor
speakers)
(ii.b) (loses half the speaker community but captures more data/literature)
(ii.d) (loses half the speaker community and captures less data/literature)
(iii) I don't know what a "non-language node" is in the context of
Glottolog, but I guess this means that [nds] will be found in Glottolog and
people have a pointer to start their search from and will not be
automatically mislead.
(i)

If (iii) presents itself to the user as something like a disambiguation
dialog, I would actually prefer that over (ii.b) and (ii.d).

Do you need quantitative evidence for the more data/more literature claim?
I can try to provide counts, but it's the immediate consequence from the
(well-known) lack of political support for Low German in Eastern Germany
and its economic decline before and after unification. Today's dominance of
Sass orthography speaks for itself.

**Comment by xrotwang** [comment]
Glottolog doesn't have any other links to ISO 639-2, so rather than introducing this triggered by a very special case, I'd rather remove the link to ISO 639-3 for [nds] entirely - and possibly link to this issue in a comment instead.

**Comment by xrotwang** [comment]
Btw. Glottolog doesn't mandate or control which Glottolog languoids are linked from Wikipedia's language pages. So possibly an alternative ISO-Glottolog mapping could be derived from there or from Wikidata.

**Comment by xrotwang** [comment]
> From my understanding, the relevance of Glottolog comes from providing a structured access to bibliography, primary data and teaching materials.  If that is a goal, a mismatch with the majority of available data beyond
Glottolog is a bit of an issue. At least, it casts doubt on the objective
of creating an ISO 639 mapping in the first place.

I'd agree in so far as I see the ISO 639 mapping as mostly a navigational device. So if an ISO code doesn't get you to the bibliography you expected, it's not particularly useful in the Glottolog realm. Now your quote

> preferring ISO 639-2 over ISO 639-3 is best practice anyway

lead me to the [LOC ISO 639-2 pages](https://www.loc.gov/standards/iso639-2/). It seems ISO 639-2 is to be preferred over ISO 639-3 because of stability - judging from the pages, ISO 639-2 just **doesn't change**. Requesting a new code would require

>  evidence that one agency holds 50 different documents in the language or that five agencies hold a total of 50 different documents among them in the language. Documents include all forms of material and are not limited to text. This is a necessary requirement, but not sufficient in and of itself. 

So, to some extent I'd say that whenever a language has an ISO 639-2 code, it's not one of the "lesser known" languages that Glottolog cares about in particular.

**Comment by chiarcos** [comment]
>
> So, to some extent I'd say that whenever a language has an ISO 639-2 code,
> it's not one of the "lesser known" languages that Glottolog cares about in
> particular.
>
Maybe, but it also depends on how you define "language". Low German lacks a
standard variety and regional differences between dialects can be traced to
the middle ages, so, in synchronic terms, it is more like a macro-language.
That is actually part of the reason why different ISO 639-3 language tags
for different Low German dialects have been proposed in the first place,
just not very systematic ones. For the level of individual varieties, this
is certainly the case (with the exception of North Low Saxon and
Mecklenburgian which have a considerable literature). I guess it would be
rather hard to find an agency with 50 documents in East Phalian,
Plautdietsch, Pomerano or Markian. Not sure about West Phalian, but I guess
this is exactly why these don't have ISO 639-2 language tags.

**Comment by d97hah** [comment]
Just quickly, your ranking of alternatives seems biased to the ISO
639-3 -> Glottolog direction of the mapping, but there's also the
Glottolog -> ISO 639-3 direction. Since [nds] is paraphyletic wrt to
the Glottolog clf, there is no way to get both right.

It's true that we could switch to a many-to-many mapping between
ISO 639-3 codes and language-level languoids. Since there are
not that many cases like [nds] where it might be valuable, it's
nicer for most users to stay with the one-to-one mapping. The needs
of the group(s) you mention could be served by tagging their resources
to Glottocodes rather than (via) ISO 639-3 codes and/or accept some
leeway of error when choosing to use a paraphyletic code.

(Normally highly questionable ISO 639-3 codes are completely discarded
and so explained in Glottolog, but in this case I do not know the
correct solution. I don't know of a publication that discusses
intelligibility between Low German varieties in a comprehensive way,
and not even a lexicostatistical count, but that could be produced.)

all the best, H

Pada tanggal Sel, 29 Nov 2022 pukul 14.25 Christian Chiarcos <
***@***.***> menulis:

**Comment by chiarcos** [comment]
Looking at this again, after a few years, I guess the most consistent way to deal with that situation at the end of ISO 639-3 would be to redefine `nds` as a macro-language and to put the regional identifiers below (in ISO 639-3). (Although I'd personally prefer to just deprecate most dialect-level language tags and continue to work with `nds` and `nds` only, because then we can more easily aggregate resources and data over all varieties.)

BTW: My interest in this comes from a practical need, i.e., to provide BCP47-compliant, but umambiguous and sufficiently fine-grained language tags for lexical data and texts on the web. And that can be easily achieved by adding a Glottolog ID into the private use part of a BCP47 language tag, e.g., `nds-x-dith1234` for the Dithmarschen dialect. In fact, I don't know a better way, and more generally, I would like to push that as a best practice, because Glottolog will never achieve the industry penetration that ISO 639-2 has, but we can still use it, then, without violating BCP47.

As for mutual comprensibility between Plautdietsch and other Low German varieties, Plautdietsch clearly stands out with the systematic lowering of short syllables, delabialisation and the reduction of -en to -a, but these features aren't specific to Plautdietsch, but general Low Prussian traits. But none of the dialects still spoken in Germany do that. A specific trait of Plautdietsch is the East Slavic loan vocabulary and its orthography. To me, it is (judging from some Youtube videos) intelligible, much more so than some varieties of Nedersaksisch, but I'm a linguist, I am aware of systematic sound correspondences and I speak both Russian and East Low Geman (but no Dutch).
