### ISSUE TITLE
Dialects in Betawi language

### ISSUE THREAD

**Issue by Yanzz73** [glottolog/glottolog#858]
Sorry in advance, the Betawi language has two dialects, namely the Middle dialect (Dialek Tengahan/Dialek Jakarta) which is spoken in the center of Jakarta and parts of Tangerang City and the Peripheral dialect (Dialek Pinggiran) or Betawi Ora, the Betawi language dialect which gets a lot of influence and vocabulary from the Sundanese language, this dialect is generally spoken in the city. Depok, Bogor Regency, Bekasi City, Bekasi Regency and Tangerang Regency as well as in the Batujaya and Pakisjaya sub-districts, Karawang. The middle dialect generally ends in "é" while the periphery dialect ends in "a". The suburban dialect is also subdivided into six sub-dialects, namely the Parung sub-dialect which is spoken in the northern district of Bogor and its surroundings, the Depok sub-dialect which is spoken in the city of Depok and Cibinong district, the Bekasi sub-dialect which is spoken in the Bekasi city and Bekasi district, and the Tangerang coastal sub-dialect spoken in the southern part. North Tangerang Regency, Serpong sub-dialect spoken in South Tangerang City, and Rengasdengklok sub-dialect spoken in eastern Bekasi Regency and northern part of Karawang Regency.

**Comment by d97hah** [comment]
Do you have a reference for this dialect division?

Pada tanggal Kam, 26 Mei 2022 pukul 18.42 Yanzz73 ***@***.***>
menulis:
