### ISSUE TITLE
Wrong coordinates for Saponi [sapo1254]?

### ISSUE THREAD

**Issue by barlowrussell** [glottolog/glottolog#865]
Saponi (of the Far West Lakes Plain group) is looking a little--well--east :) As far as I can tell from the scant sources, it was spoken in Botawa village, Waropen regency, Indonesia (Clouse 1997: 164; Ethnologue 25). I don't have Jones (1987), so I might be missing something here though. Anyway, if I've identified the right "Botawa", then I think the coordinates should be more like: -2.385, 136.497.

**Comment by d97hah** [comment]
You are right. Thanks for catching this. I have Jones (1987) and the
contents is the same as that you cite. Darsih (2012) did some research on
Demisa in that same Botawa village (you have identified the right one).
I'll fix the coordinate. Thanks again! H

Pada tanggal Kam, 2 Jun 2022 pukul 11.11 barlowrussell <
***@***.***> menulis:
