### ISSUE TITLE
Gulf Coast French (gulf1242) likely extinct as of 2005 according to University of Mississippi panel

### ISSUE THREAD

**Issue by Arctic-Circle-System** [glottolog/glottolog#871]
According to a linguistics panel at the University of Mississippi, Gulf Coast French likely went extinct in 2005 due to the impact of Hurricane Katrina. https://www.newswise.com/articles/linguistics-panel-examines-katrinas-impact-on-gulf-coast-languages

**Comment by d97hah** [comment]
The youngest speaker was born in 1924 (Moreton 2001:34) so should indeed be
extinct by now, regardless of Katrina. I'll adjust for next version. all
the best, H

Pada tanggal Kam, 7 Jul 2022 pukul 15.32 Arctic Circle System <
***@***.***> menulis:

**Comment by Arctic-Circle-System** [comment]
Thank you. Is there anywhere I can read up on the reasoning for why Gulf Coast French is considered a language rather than a dialect of French in this database? ~Sol

**Comment by Arctic-Circle-System** [comment]
Accidentally closed, whoops. ~Sol

**Comment by d97hah** [comment]
Moreton 2001

Pada tanggal Jum, 8 Jul 2022 pukul 04.46 Arctic Circle System <
***@***.***> menulis:
