### ISSUE TITLE
Feu, Veronica Du -> Du Feu, Veronica

### ISSUE THREAD

**Issue by hojucha** [glottolog/glottolog#882]
The name of the author of [134734](https://glottolog.org/resource/reference/id/134734) should be `Du Feu, Veronica`, rather than `Feu, Veronica Du`.

**Comment by d97hah** [comment]
Thanks I've fixed that for next version! H

Pada tanggal Sel, 30 Agu 2022 pukul 13.35 Hoju Cha ***@***.***>
menulis:
