### ISSUE TITLE
refs for popolocan subgroup

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#883]
Regarding classifcation references for popo1292, Popolocan expert Shun Nakamoto says that

_Campbell (2017) is a useful survey but that classification comes from Fernández de Miranda (1951), Gudschinsky (1958) and Hamp (1958, 1960). [..]  E. Campbell (2017) is a survey and not a first-hand classification, the Glottolog classification of Popolocan (current "Popolocan-Mazatecan") is in accordance with the literature. E. Campbell (2017) basically reworded Terrence Kaufman's (1988-2004) _

**Comment by d97hah** [comment]
Glottolog often cites later surveys if they cover the earlier actual
classification work. It is desired behaviour and adds a temporal layer.


Pada tanggal Kam, 1 Sep 2022 pukul 07.14 Hedvig Skirgård <
***@***.***> menulis:
