### ISSUE TITLE
Bathi and Bhatiyana - where do these Punjabi dialect names come from?

### ISSUE THREAD

**Issue by bgo-eiu** [glottolog/glottolog#885]
I am curious where the names of these entries come from:
* https://glottolog.org/resource/languoid/id/bath1239
* https://glottolog.org/resource/languoid/id/bhat1264

As far as I can tell Bathi and Bhatiyana are names of geographic regions rather than dialect names. However, even in *Linguistic Atlas of the Punjab* (H. S. Gill, 1973), one of the only comprehensive regional dialect surveys of Punjabi, this is not a distinction which is brought up. Maybe something has been written about this but there are no references listed to find where this comes from

**Comment by bgo-eiu** [comment]
I found a hint related to this just now. Here, Bhattiani is listed as recognized by both the Languages Dept of Punjab and Punjabi University, Patiala
https://www.learnpunjabi.org/intro1.asp

**Comment by d97hah** [comment]
See e.g., Bhatia 1993, it ultimately seems to go back to:

Singh, A. (1970) ‘An introduction to the dialects of Punjabi’, Pakha Sanjam
3(1-2): 120-52

But I don't have access to this original paper. Bathi is a typo for Rathi
and Bhattiyani is misspelled, I'll fix that for next version. all the best,
H

Pada tanggal Jum, 2 Sep 2022 pukul 19.46 bgo-eiu ***@***.***>
menulis:

**Comment by bgo-eiu** [comment]
Thank you, that answers my question and is enough to investigate further. I suppose this can be closed when the corrections are made for the next version
