### ISSUE TITLE
Bhariati language

### ISSUE THREAD

**Issue by bgo-eiu** [glottolog/glottolog#886]
I was going to make a pull request but I am not quite familiar with the process for adding references or using BibTeX yet.

The language named in the Glottolog database as Bharia is called Bhariati. The people who speak Bhariati are the Bharia people. We can still say "the Bharia language" to mean "the language of the Bharia people," but the language itself does have a name which follows the pattern of other Indic language names like Hindi, Punjabi, Gujarati, etc.

The Wikipedia page has been moved to Bhariati language so this can be updated in the file.

Publications on this language are scarce, but this is one of the best sources I have come across (hosted on a website containing some Bhariati writing as well):

https://www.bharia.in/sites/www.bharia.in/files/PDF/Bhariati%20Grammar%20Write-up%20on%20March-2017.pdf

Kumar, P. and Grace, G. V. (2017). A write-up of Bhariati grammar. Dehradun, India: _ILL_.

**Comment by d97hah** [comment]
Thanks for bringing this title to my attention. I'll add the reference and
adjust the name for next version of Glottolog. all the best, H

Pada tanggal Jum, 2 Sep 2022 pukul 19.35 bgo-eiu ***@***.***>
menulis:
