### ISSUE TITLE
A writing system VN Song Song (CVNSS4.0) - 

### ISSUE THREAD

**Issue by adminvsrm** [glottolog/glottolog#890]
Writing System Vietnamese language (CVNSS4.0) - **Vietnamese bilingual/auxiliary language?**
------------------------
The 4.0 revolution (Industry 4.0) can be summarized in the following manner: First Industrial Revolution: Mechanization; Second Industrial Revolution: Electrification; Third Industrial Revolution: Automation; Fourth Industrial Revolution: Digitization. The process of transferring paper-based information and manual procedures into digital format is called digitization. Data management, mining, processing, storage, and transport all rely heavily on digitization.

For instance, we use OCR technology to digitize the reading of text (words) in picture files. OCR is a digital scanning tool that specializes in identifying characters, handwriting, or typed letters in order to communicate technical information. In several sorts of paperwork, including invoices, passports, business cards, and documents... However, depending on the quality of the picture utilized and the treatment of Vietnamese accents, handwriting remains the most challenging word pattern to recognize. The authors have built Cvnss4.0 as a regular notation system; it is analogous to a mathematical theorem system in a computer environment and serves as a "stepping stone" for transforming the values of contemporary Vietnamese words have not yet been favored by the real-world system of social customs.
Source: https://chuvnsongsong.com/

**Comment by xrotwang** [comment]
I think this is not really in scope for Glottolog.
