### ISSUE TITLE
Talian language

### ISSUE THREAD

**Issue by guilhermegarcia** [glottolog/glottolog#891]
Hello,

Talian (Brazilian Veneto) could be added to the catalogue.

Guzzo, N. (2022). Brazilian Veneto (Talian). _Journal of the International Phonetic Association_, 1-15. doi:10.1017/S002510032200010X

**Comment by d97hah** [comment]
Thanks, I've added it for next version!

Pada tanggal Kam, 15 Sep 2022 pukul 22.23 Guilherme D. Garcia <
***@***.***> menulis:
