### ISSUE TITLE
fiji1243 name "East Fijian"

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#893]
Could fiji1243 please get the default name "East Fijian" to make it harmonious with west2518 "West Fijian".

Thank you.

**Comment by d97hah** [comment]
That would seem to clash with East Fijian [east2446]

Pada tanggal Min, 18 Sep 2022 pukul 04.05 Hedvig Skirgård <
***@***.***> menulis:

**Comment by xrotwang** [comment]
I think making family names more meaningful (or harmonious) is a slippery slope towards getting them on track for "can't ever be removed".

**Comment by HedvigS** [comment]
@xrotwang Sure.

In this case, I think that one language getting the name "Fijian" when there are several languages spoken in the Fijian archipelago is unnecessarily confusing.

**Comment by HedvigS** [comment]
If you want to be more precise, here's another option:

fiji1243 -> Fijian (East Viti Levu)
west2518 -> Fijian (West Viti Levu)

Since it's really about VIti Levu and not all of Fiji :)

**Comment by d97hah** [comment]
It's about all Fiji, not just Viti Levu. The names Eastern and Western
Fijian in the literature are strongly connected to the larger sets. The ISO
639-3 division is not in harmony with Geraghty 1983's detailed study, but I
hesitate to rip it apart without seeing Schutz 1962, which I don't yet have
access to. In the meantime, a better name for west2518 may be Western Viti
Levu-Yasawas Fijian but there is no good short name for fiji1243 unless one
wants to do something like East Viti Levu-Kadavu-Vanua Levu. Fijian, as
used in the literature, is a reasonably good match for fiji1243, so I think
we'll have to keep that one. I've cleaned up the dialect listings of all
Fijians for next version in a PR to be pushed shortly. all the best, H

Pada tanggal Sen, 19 Sep 2022 pukul 09.50 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Okay, your call. I think having one be "Fijian" is a bit confusing but your call.

What's the title of Schutz 1962?

**Comment by d97hah** [comment]
If you have less confusing names feel free to suggest them, but check the
denotations and literature first. Possibly Eastern/Western Fijiic would be
a small improvement to E/W Fijian in spite of the established use of Fijian
in the literature in these cases.

Schütz, Albert J. (1962) A dialect survey of Viti Levu. Ithaca: Cornell
University doctoral dissertation.

Pada tanggal Kam, 29 Sep 2022 pukul 02.05 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Ok!

I still stand by this suggestion:

> east2446 -> East Fijian-Lau-Gone Dau-Lomaiviti 
> fiji1243 -> East Fijian

**Comment by d97hah** [comment]
That's great but then you didn't read the literature...

Pada tanggal Kam, 29 Sep 2022 pukul 08.41 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
I have read the literature, I just don't give that as much weight as you.

I have email conversations about Fiji sometimes with Andy Pawley and Paul Geraghty. I can check with them what they think if you want?
