### ISSUE TITLE
Hattic Icon on Map Way Out of Range

### ISSUE THREAD

**Issue by rvat2003** [glottolog/glottolog#896]
The icon for Hattic on the map is WAY out of Hattusa's vicinity. It's currently between Syria and Iraq but the language is from inside the Anatolian peninsula.

**Comment by d97hah** [comment]
Thanks, it seems the lat/lon were reversed. I'll fix it for next version.
all the best, H

Pada tanggal Sab, 15 Okt 2022 pukul 18.51 Rohann Von Taduran <
***@***.***> menulis:
