### ISSUE TITLE
Family: Siraikic

### ISSUE THREAD

**Issue by mpQadir** [glottolog/glottolog#897]
In this family there are two languages. It is suggested that Jangli, Jafri and khetrani be added here. Then there will be five languages. 

In Saraiki the following are same and alternate names so be deleted please: 
[Bahawalpuri](https://glottolog.org/resource/languoid/id/baha1254)
[Derawali](https://glottolog.org/resource/languoid/id/dera1244)
[Jatki](https://glottolog.org/resource/languoid/id/jatk1238)
[Multani](https://glottolog.org/resource/languoid/id/mult1243)
[Siraiki Hindki](https://glottolog.org/resource/languoid/id/sira1262)
[Thali](https://glottolog.org/resource/languoid/id/thal1241)

These 6 are extra so these six be deleted and these are alternate names for Saraiki.

**Comment by d97hah** [comment]
Hi! Thanks for your input, what is the source for considering Khetrani a
Siraikic languages? Re the alternate, names, I understand Multani, Thali,
Derawali (of Dera Ismail Khan) to be different localities rather than
alternative names? Is this not so? all the best, H

Pada tanggal Rab, 19 Okt 2022 pukul 08.03 mpQadir ***@***.***>
menulis:

**Comment by d97hah** [comment]
The LSI's view of Khetrani is outdated, see Birmani & Ahmed (2017) which
cited as the clf ref in Glottolog. There are things that point to
Siraiki and things that point to Sindhi, I think the numeral 'two' in b-
that sides with Sindhi is the decider.

Yes Jatki and Siraiki Hindki are superfluous but the regional varieties are
not, are there is regional variation as clearly stated in e.g. LSI.

Pada tanggal Rab, 19 Okt 2022 pukul 09.40 mpQadir ***@***.***>
menulis:

**Comment by mpQadir** [comment]
Ok, 
Jangli and Jafri be added in family. 
In the family there will be four entries. 

In Saraiki all extras be deleted. and may be put in other / old names.

**Comment by aryamanarora** [comment]
The name Multani is still used by diasporic speakers in India who migrated after Partition.

**Comment by mpQadir** [comment]
Yes, Multani is alternate name for Saraiki.
