### ISSUE TITLE
Reference 27788 linked to wrong language

### ISSUE THREAD

**Issue by hojucha** [glottolog/glottolog#903]
Reference [27788](https://glottolog.org/resource/reference/id/27788) is erroneously linked to Banda (Indonesia) [bnd]. It should be linked to Mono (Democratic Republic of Congo) [mnh] only. Also, its macroarea should be Africa only.

**Comment by d97hah** [comment]
Thanks I'll fix that for next version!

Pada tanggal Rab, 23 Nov 2022 pukul 10.18 Hoju Cha ***@***.***>
menulis:
