### ISSUE TITLE
adding reference for Classical Tibetan

### ISSUE THREAD

**Issue by eroux** [glottolog/glottolog#923]
Joanna Bialek's "A Textbook in Classical Tibetan" (2022) is a great reference for Classical Tibetan.

I think it should be added but I must say I'm not entirely sure how... should I make a PR against https://github.com/glottolog/glottolog/blob/master/references/bibtex/hh.bib ?

**Comment by d97hah** [comment]
I'll add it. all the best, H

Pada tanggal Min, 15 Jan 2023 pukul 19.23 Elie Roux <
***@***.***> menulis:
