### ISSUE TITLE
Added Sundanese dialect

### ISSUE THREAD

**Issue by JoeMustafa73** [glottolog/glottolog#924]
Actually there are several Sundanese dialects that have not been written in Glottolog, I get several dialects from the results of the reference source. Among them, the Cianjur dialect which belongs to the Sundanese Priangan, the Karawang, Subang and Cikarang dialects which belong to the Northern Sundanese dialect along with the Bogor dialect, the extinct Banyumas dialect belongs to a separate dialect as well as the Jasinga dialect, Pandeglang dialect, and Rangkasbitung dialect which belongs to Sundanese Banten.

Sources: https://petabahasa.kemdikbud.go.id/infobahasa.php?idb=56
http://repository.unj.ac.id/10078/1/COVER.pdf.pdf
https://repositori.kemdikbud.go.id/16132/
https://onesearch.id/Record/IOS14013.21571?widget=1&repository_id=2488
https://onesearch.id/Record/IOS3644.slims-8325
https://onesearch.id/Record/IOS2744.54267

**Comment by d97hah** [comment]
Not sure what you intend to say. Not every locality needs its own glottolog
dialect entry. Glottolog largely follows Nothofer where the localities you
mention are taken up. all the best, H

Pada tanggal Sen, 23 Jan 2023 pukul 16.36 JoeMustafa73 <
***@***.***> menulis:

**Comment by JoeMustafa73** [comment]
Actually, the dialect that I mentioned earlier refers to the source of the Language Map by the Indonesian Ministry of Education and Culture. Then a Sundanese observer named Satjadibrata also stated that Sundanese is divided into 9 dialects. Maybe that's the reference source that I use in this argument.

Thank you.

**Comment by d97hah** [comment]
If you are referring to
https://petabahasa.kemdikbud.go.id/infobahasa.php?idb=56 it says there are
two dialects, spoken in various localities. all the best, H



Pada tanggal Sel, 24 Jan 2023 pukul 03.27 JoeMustafa73 <
***@***.***> menulis:
