### ISSUE TITLE
Change Melayu Sini dialect

### ISSUE THREAD

**Issue by JoeMustafa73** [glottolog/glottolog#925]
It is better if the Melayu Sini dialect in Ambonese Malay is changed to Masohi Malay. The word "Sini" in the Malay language itself shows high ambiguity, "Sini" can mean here, locally, or alone. Whereas the Masohi Malay dialect is clearer because it is spoken in Masohi City, Central Maluku. Thank you.

**Comment by JoeMustafa73** [comment]
Oh yes, one more thing, the Orang Pulo language might be included in the Vehicular Malay section because of its connection with Malay and most of the vocabulary is Creole Malay. This language is used by the Pulo people in the Thousand Islands, Jakarta.

**Comment by d97hah** [comment]
Melayu Sini refers to the Ambonese Malay spoken by the immigrant community
that came to the Netherlands in the 50s. I agree it's ambiguous but that is
the name used in the literature.

Pada tanggal Sel, 24 Jan 2023 pukul 04.49 JoeMustafa73 <
***@***.***> menulis:

**Comment by d97hah** [comment]
The variety described by Hudaa et al. 2021 is like Indonesian but with
minor lexical and phonological variation and so would fit there if
anywhere. all the best, H

Pada tanggal Sel, 24 Jan 2023 pukul 04.55 JoeMustafa73 <
***@***.***> menulis:
