### ISSUE TITLE
North Levantine and South Levantine have been merged

### ISSUE THREAD

**Issue by a455bcd9** [glottolog/glottolog#926]
ajp is deprecated and apc is now "Levantine Arabic" (as a whole): https://iso639-3.sil.org/code/apc

**Comment by d97hah** [comment]
I'll adjust accordingly

Pada tanggal Sab, 28 Jan 2023 pukul 14.18 Antoine Dusséaux <
***@***.***> menulis:

**Comment by a455bcd9** [comment]
Thanks @d97hah!

FYI, here's the newly updated Levantine [apc] page on Ethnologue post merge (released yesterday): https://www.ethnologue.com/language/apc/
