### ISSUE TITLE
Add Róna-Tas (2011) to bibliography

### ISSUE THREAD

**Issue by martino-vic** [glottolog/glottolog#930]
This is the bibtex-key:

```
@Book{RonaTas2011,
  author    = {R\'{o}na-Tas, Andr\'{a}s and Berta, \'{A}rp\'{a}d},
  title     = {West Old Turkic. Turkic loanwords in Hungarian},
  year      = {2011},
  publisher = {Harrassowitz},
  address   = {Wiesbaden},
}
```

After it has been added it could be listed as a source for Old Ossetic in [this file](https://github.com/glottolog/glottolog/blob/d68f7280c0792e7f09d51b48908fefbce3bcf84b/languoids/tree/indo1319/clas1257/indo1320/iran1269/cent2317/sogd1247/osse1245/oldo1234/md.ini) under ``[sources]``. A list of Alanian (= [Old Ossetic](https://github.com/glottolog/glottolog/blob/d68f7280c0792e7f09d51b48908fefbce3bcf84b/languoids/tree/indo1319/clas1257/indo1320/iran1269/cent2317/sogd1247/osse1245/oldo1234/md.ini#L57)) words is provided on pages 1331-1339, see for example screenshot: ![Alanian](https://user-images.githubusercontent.com/53435298/218578333-56a6b06a-e987-45df-b9b6-68cb5ffcac5c.png)

**Comment by d97hah** [comment]
Ok will do

Pada tanggal Sen, 13 Feb 2023 pukul 22.30 Viktor Martinović <
***@***.***> menulis:
