### ISSUE TITLE
Add Jassic as third dialect to modern Ossetic?

### ISSUE THREAD

**Issue by martino-vic** [glottolog/glottolog#931]
See [Wikipedia](https://en.wikipedia.org/wiki/Jassic_dialect) and Róna-Tas (2011, p. 476, see screenshot below): "A group that lived in the Pilis mountains Northeast fr the city of Pest was visited in 1422 by a person who compiled a short Yas–Lat word list (Koszta–Nyitrai in Kristó 1994: 301). This word list of about 40 words has been published by Németh (1959)." 

I still need to check the two primary sources, the bibtex keys of which are:

```
@Book{Kristo1994,
  title={A K{\'a}rp{\'a}t-medence {\'e}s a magyars{\'a}g r{\'e}gm{\'u}ltja [The Carpathian Basin and Hungarians' ancient past]},
  author={Krist{\'o}, Gy},
  year={1994},
  publisher={Szegedi K{\"o}z{\'e}pkor{\'a}sz Muhely Szeged, Hungary}
}

@Article{Nemeth1959,
  title={Eine W{\"o}rterliste der Jassen, der ungarl{\"a}ndischen Alanen: Abhandlungen der Deutschen Akademie der Wissenschaften zu Berlin, Klasse f{\"u}r Sprachen, Literatur und Kunst},
  author={N{\'e}meth, Gyula},
  year={1959},
  publisher={Akad.-Verl.(Berlin)}
}

```
![Jász](https://user-images.githubusercontent.com/53435298/218592392-3e6bdf42-c91e-4249-a374-d14014676554.png)

**Comment by d97hah** [comment]
It's already there (it's a dialect of Digor) Jassic [jass1238]

Pada tanggal Sel, 14 Feb 2023 pukul 00.08 Viktor Martinović <
***@***.***> menulis:

**Comment by martino-vic** [comment]
Ohh, fantastic! sorry, I don't know why I didn't see this.
