### ISSUE TITLE
Classification of Mangayat

### ISSUE THREAD

**Issue by Baerman** [glottolog/glottolog#932]
Mangayat (mang1387), a Ubangian language of South Sudan, seems to have gotten itself on a classification list with the "Khoisan" languages. (Judging by the bibliographical references it pulls up.)

**Comment by d97hah** [comment]
That's a glitch with an older auto-translation. I'll fix it for next
version. Thanks for spotting.

Pada tanggal Sel, 14 Feb 2023 pukul 13.50 Baerman ***@***.***>
menulis:
