### ISSUE TITLE
Sundanese branch (sund1252)

### ISSUE THREAD

**Issue by HaikalFK** [glottolog/glottolog#941]
Why don't we distinguish the grouping between Old Sundanese and Sundanese dialects. Sundanese dialects such as Banten, North Coast, Cirebon/East and Priangan should be grouped into a separate group, namely Modern Sundanese. The Badui language should technically be named as a language, not as a dialect.

**Comment by d97hah** [comment]
What are the shared innovations that would motivate a Modern Sundanese
subgroup?

Pada tanggal Jum, 10 Mar 2023 pukul 05.28 Haikal ***@***.***>
menulis:

**Comment by HaikalFK** [comment]
Maybe to emphasize that Sundanese has undergone language development, and Old Sundanese has quite significant differences from Modern Sundanese. Some examples are innovations in eu-u phonotactics in Old Sundanese to become i-u in standard Sundanese, and o-u or a-u in non-standard dialects. This eu-u phonotactic has been discussed by J. Noorduyn and A. Teeuw in Three Old Sundanese Poem (2006) [https://books.google.co.id/books?id=C2xPEAAAQBAJ&printsec=frontcover&hl=id&source=gbs_ge_summary_r&cad=0# v=snippet&q=eu-u&f=false]

**Comment by HaikalFK** [comment]
I suggest branching like this:
Malayo-Sumbawan
* Maduresic
* North and East Malayo-Sumbawan
* Sundanese-Badui or Sundanesic? or Sundanic?
** Modern Sundanese
*** Badui
*** Sundanese
**** Banten
***** Pandeglang
***** Serang Sundanese
***** Tangerang Sundanese
**** Mid-East Sundanese
***** Brebes
***** Cirebon Sundanese
***** Indramayu Sundanese
***** Kuningan Sundanese
***** Majalengka Sundanese
**** North Coast Sundanese
***** Binong Sundanese
***** Bogor
***** Karawang Sundanese
**** Priangan
***** Bandung Sundanese
***** Ciamis
***** Garut
***** Sumedang
***** Tasikmalaya
** Old Sundanese

**Comment by d97hah** [comment]
This is thus not an example of a shared innovation in the modern dialects.
all the best, H

Pada tanggal Sab, 11 Mar 2023 pukul 05.53 Haikal ***@***.***>
menulis:

**Comment by d97hah** [comment]
Thanks for the suggestion but since you do not say what it is based on and
it contradicts e.g. Nothofer's survey, I will ignore it.

Pada tanggal Sab, 11 Mar 2023 pukul 06.24 Haikal ***@***.***>
menulis:
