### ISSUE TITLE
Sundanese-Badui Family

### ISSUE THREAD

**Issue by HaikalFK** [glottolog/glottolog#942]
Why was the Sundanese-Badui language family removed? Wouldn't it be better to think of both as separate languages? Both have different ISO 639-3 codes. This is similar to the grouping of Korean and Jeju languages.

**Comment by d97hah** [comment]
See the cited dialect survey by Nothofer. The case is not similar to Korean
and Jeju which are not mutually intelligible.

Pada tanggal Jum, 10 Mar 2023 pukul 05.33 Haikal ***@***.***>
menulis:
