### ISSUE TITLE
Sunda Kuno or Old Sundanese?

### ISSUE THREAD

**Issue by HaikalFK** [glottolog/glottolog#943]
For md.ini in sund1255, Shouldn't we use the term "Old Sundanese"? Based on the ISO 639-3 osn code (https://iso639-3.sil.org/code/osn) and classifies it as a "language", not a "dialect".

**Comment by d97hah** [comment]
The name can be Old Sundanese. It should perhaps be classified as a
language but the basis cannot be ISO 639-3 as they do not provide an
adequate reason for considering it a language using their own definition.
all the best, H

Pada tanggal Sab, 11 Mar 2023 pukul 05.45 Haikal ***@***.***>
menulis:

**Comment by HaikalFK** [comment]
yeah, "Old Sundanese" is better, and probably shouldn't be coded sund1255, but maybe something like olds1255 or something to match, I don't know if this is right or wrong. At least so that there is conformity between Glottolog with ISO 639-3 and Ethnologue.
