### ISSUE TITLE
Add Dili Malay

### ISSUE THREAD

**Issue by JoeMustafa73** [glottolog/glottolog#947]
Add Dili Malay, a creole-based Malay spoken in the Kampung Alor, Dili. 

Biblography:
Yos Fernandez, Inyo (1994) Beberapa Catatan Tentang Bahasa Melayu Dili: Studi Awal Mengenai Bahasa Melayu Di Timor Timur. https://www.neliti.com/publications/12202/beberapa-catatan-tentang-bahasa-melayu-dili-studi-awal-mengenai-bahasa-melayu-di

**Comment by d97hah** [comment]
Already there as
https://glottolog.org/resource/languoid/id/alor1252

Pada tanggal Min, 19 Mar 2023 pukul 19.45 JoeMustafa73 <
***@***.***> menulis:

**Comment by d97hah** [comment]
Yes, sorry, you are right. I will add Dili Malay for the next version. all
the best, H

Pada tanggal Sen, 20 Mar 2023 pukul 11.44 JoeMustafa73 <
***@***.***> menulis:
