### ISSUE TITLE
References for Dan (east2794)

### ISSUE THREAD

**Issue by IanMaddieson** [glottolog/glottolog#950]
The two most important referencers for Dan seem to be absent form the bibliography:

Bearth, Thomas. and Zemp, H. 1967. The phonology of Dan (Santa). Journal of African Languages 6: 9-29.

Flik, Eva. 1977. Tone glides and registers in five Dan dialects. Linguistics 201: 5-59.

**Comment by d97hah** [comment]
Thanks, they're there but apparently not linked to Dan. Will fix for next
version! H

Pada tanggal Sen, 10 Apr 2023 pukul 18.10 IanMaddieson <
***@***.***> menulis:
