### ISSUE TITLE
Added Poso Pesisir

### ISSUE THREAD

**Issue by JoeMustafa73** [glottolog/glottolog#956]
Please add the Poso Pesisir language to the Pamona-Tombelala language family. This language is also known as Northern Pamona, Pantai Bare'e (Bare'e Beach), or Coastal Poso.

Biblography:
1. Adriani, Nicolaus (2012). Overview of Pamona dialects (per Nicolaus Adriani)(http://sulang.org/resources/survey-reports/002). Translated by Mead, David. Sulawesi Language Alliance.
2.  Kruyt, Albertus Christiaan (1914). De Bare'e-sprekende Toradja's van Midden-Celebes (https://books.google.co.id/books?id=jostMQAACAAJ). Batavia: Landsdrukkerij.

**Comment by d97hah** [comment]
Thanks I'll add Coastal Poso (as "Poso-Tojo") to the list of
Pamona dialects for next edition of Glottolog. all the best, H

Pada tanggal Sab, 6 Mei 2023 pukul 18.58 JoeMustafa73 <
***@***.***> menulis:
