### ISSUE TITLE
Kalkatungu / Kalkadoon rather than Kalkutung

### ISSUE THREAD

**Issue by chirila** [glottolog/glottolog#957]
https://grambank.clld.org/languages/kalk1246 uses the spelling Kalkutung for this name, which seems to be a compromise between Kalkatungu (what linguists standardly call this language) and Kalkadoon (in the older anthropological literature). This name seems to originate with either glottolog or ethnologue. Suggest changing the reference name to Kalkatungu and having some public information about the choice of names where there are multiple choices

**Comment by haspelmath** [comment]
Yes, this should be changed to "Kalkatungu" in Glottolog.

**Comment by d97hah** [comment]
I've fixed that for next versioN! H

Pada tanggal Sab, 13 Mei 2023 pukul 18.31 Martin Haspelmath <
***@***.***> menulis:
