### ISSUE TITLE
name change: Karok -> Karuk

### ISSUE THREAD

**Issue by elangokumaran** [glottolog/glottolog#970]
The modern spelling for the language's name is 'Karuk'. See e.g. Bright and Gehr's (2005) 'Karuk dictionary', recent UC Berkeley dissertations by Sandy (2017) and Maier (2022), and the online corpus at linguistics.berkeley.edu/~karuk

**Comment by d97hah** [comment]
I'll change it for next version

Pada tanggal Sen, 10 Jul 2023 pukul 22.37 Elango Kumaran <
***@***.***> menulis:

**Comment by elangokumaran** [comment]
thanks!

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/commit/1f44abddb793b9779a6e67afb62854ca9077b2af#diff-601569805f5c9b4c5785020440faef84db4284f1fc4d6993ff074bcfb737103d
