### ISSUE TITLE
Clades where all languages have dialects listed don't expand when clicking Expand All

### ISSUE THREAD

**Issue by Arctic-Circle-System** [glottolog/glottolog#974]
Action: Pressing "Expand All" button in a language family
Expected behavior: All clades should expand to show all languages in the tree for that family
Actual behavior: When pressing "Expand All", clades in which all languages have dialects listed do not expand. Language families are not a factor. If a clade has a language and a language family in it, and one of the languages in that language family doesn't have dialects listed, the clade will fully expand.
Examples: https://glottolog.org/resource/languoid/id/insu1254 When pressing "Expand All", Goidelic fully expands while Brythonic does not.

**Comment by xrotwang** [comment]
Moved to the repos for the web app source, see https://github.com/clld/glottolog3/issues/151
