### ISSUE TITLE
Siberian Ingrian Finnish listed only as a dialect of Ingrian rather than as a mixed Lower Luga Ingrian Finnish - Lower Luga Ingrian variety

### ISSUE THREAD

**Issue by Arctic-Circle-System** [glottolog/glottolog#975]
As per #944, Siberian Ingrian Finnish is a mixed variety with features of Lower Luga Ingrian Finnish and Lower Luga Ingrian. However, [its entry](https://glottolog.org/resource/languoid/id/sibe1253) only lists it as a dialect of Ingrian within a Lower Luga group with no mention of it being a mix between Lower Luga Ingrian and Lower Luga Ingrian Finnish. I'm not sure exactly how to remedy this considering that the way mixed languages are often listed is inconsistent, with [Michif](https://glottolog.org/resource/languoid/id/mich1243) being listed with Plains Cree, [Shelta](https://glottolog.org/resource/languoid/id/shel1236) being listed under "Irish-English" in "Speech Register", and [Lomavren](https://glottolog.org/resource/languoid/id/loma1235) being listed under "Indo-European Speech Register". Michif has some comments on subclassification which are helpful in seeing why it's classified the way it is, though I'm not so sure about Lomavren or Shelta.

**Comment by d97hah** [comment]
Truly intertwined dialects (if they exist), like dialects/languages with
some horizontal transfer in their history get no special marking. There is
no inconsistency in the handling of mixed languages if there is enough
information on the language in question. If you are not sure about
Shelta/Lomavren, here's a wild idea, read the sources!

Pada tanggal Sel, 11 Jul 2023 pukul 23.10 Arctic Circle System <
***@***.***> menulis:
