### ISSUE TITLE
Divergent dialects not listed as parts of the dialect group they originated from

### ISSUE THREAD

**Issue by Arctic-Circle-System** [glottolog/glottolog#976]
I've noticed that dialects that are considered divergent enough to be listed as separate languages within the Glottolog database are not listed as being closely related to other dialects within their dialect group. I have no issue with listing such divergent dialects as languages, that's more than fine. But I'm not sure it's accurate to say that [Slavomolisano](https://glottolog.org/resource/languoid/id/slav1254) isn't part of the larger Shtokavian dialect group as well as being a distinct language from Serbo-Croatian, or that [Gardiol](https://glottolog.org/resource/languoid/id/gard1245) isn't part of the Vivaro-Alpine dialect group. There are more examples of this scattered about, such as [Kagoshima](https://glottolog.org/resource/languoid/id/sats1241) and [Tsugaru](https://glottolog.org/resource/languoid/id/tsug1237), which should be listed as part of the Kyūshū and Northern Tōhoku dialect groups respectively.

**Comment by d97hah** [comment]
Yes, it's a known feature. I think it's mentioned somewhere. all the best, H

Pada tanggal Sel, 11 Jul 2023 pukul 23.28 Arctic Circle System <
***@***.***> menulis:
