### ISSUE TITLE
Add Schliefer dialect (transitional between Lower and Upper Sorbian) and Muskau dialect

### ISSUE THREAD

**Issue by Arctic-Circle-System** [glottolog/glottolog#978]
The English Wikipedia article on Schliefer can be found [here](https://en.wikipedia.org/wiki/Schleifer_dialect), while the German Wikipedia article on Muskau can be found [here](https://de.wikipedia.org/wiki/Muskauer_Dialekt). Hopefully this bibliography should contain enough information.

Schliefer bibliography:
Trudla Malinkowa (2011). Der alte Friedhof in Rohne/Stare pohrjebnišco w Rownom. Eine Dokumentation (in German). Bautzen: Lusatia Verlag. ISBN: 978-3-936758-72-6
["Kolesko z.t. - Verein"](https://www.kolesko.de/verein/verein) (in German). association Kólesko.
["Juliana Kaulfürst und Dieter Reddo erhalten Zejler-Preis 2018"](https://www.medienservice.sachsen.de/medien/news/217311) (in German). Sächsische Staatskanzlei. 18 April 2018. "Wie Kunstministerin Dr. Eva-Maria Stange heute bekannt gab, werden Juliana Kaulfürst und Dieter Reddo mit dem diesjährigen Preis für sorbische Sprache, dem Zejler-Preis, geehrt."

Muskau bibliography:
[L. V. Ščerba](https://de.wikipedia.org/wiki/Lew_Wladimirowitsch_Schtscherba): Vostočnolužickoe narečie. Domowina-Verlag, Bautzen 1973 (Fotomechanischer Neudruck, russisch mit deutschem Vorwort).
[Julius Eduard Wjelan](https://de.wikipedia.org/w/index.php?title=Julius_Eduard_Wjelan&action=edit&redlink=1): Namjezno-Mužakowska wotnožka serbšćiny. In: [Časopis Maćicy Serbskeje](https://de.wikipedia.org/wiki/%C4%8Casopis_Ma%C4%87icy_Serbskeje). Band 22, 1869, S. 57–93 (niedersorbisch, [Digitalisat](https://www.serbski-institut.de/mat/dnlarchiv/cms1869_526.pdf#page=57) beim [Sorbischen Institut](https://de.wikipedia.org/wiki/Sorbisches_Institut)).

**Comment by d97hah** [comment]
I'll add a full-ish Sorbian dialect division for next version (NB:
Schleife-Muskau are L Sorbian more than they are U Sorbian, see
Schuster-Sewc 1996:245-248)

Pada tanggal Rab, 12 Jul 2023 pukul 00.02 Arctic Circle System <
***@***.***> menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/commit/1f44abddb793b9779a6e67afb62854ca9077b2af#diff-0765a798610ccce982c8e8d9baaeb501d22f5433b0152cca55dda1c136909cad
