### ISSUE TITLE
Aikanã phonology

### ISSUE THREAD

**Issue by hafaew** [glottolog/glottolog#982]
Hello,

I'm creating this issue to communicate that new work on Aikanã phonetics and phonology (a doctoral dissertation) was defended last year. It would be awesome to see it listed on the Aikanã reference page. Here is the link for public access: 
https://repositorio.ufpe.br/handle/123456789/49913 The title is: Fonética e Fonologia da Língua Aikanã, for reference.

**Comment by d97hah** [comment]
This UFPE site is down for maintenance at the moment but I'll add once it's
up. Thanks, H

Pada tanggal Min, 16 Jul 2023 pukul 21.02 hafaew ***@***.***>
menulis:

**Comment by hafaew** [comment]
Hello. It looks like the website is up again. Re-sharing the link: https://repositorio.ufpe.br/handle/123456789/49913. Thanks

**Comment by d97hah** [comment]
Still in maintenance...

Pada tanggal Sab, 22 Jul 2023 pukul 19.04 hafaew ***@***.***>
menulis:

**Comment by Arctic-Circle-System** [comment]
It's up on my end if you want to check now.

**Comment by d97hah** [comment]
Thanks, it's been added in the meantime! H

Pada Kam, 26 Okt 2023 pukul 22.30 Arctic Circle System <
***@***.***> menulis:

**Comment by xrotwang** [comment]
See https://github.com/glottolog/glottolog/commit/1f44abddb79#diff-10734eff36dea31b55c3a24b82a3f94d3f5ba6e967c65e9e87992dc217c08ae1R994470
